var com_netsuite_webservices_transactions_general_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_transactions_general_2019_2 = {
    name: 'com_netsuite_webservices_transactions_general_2019_2',
    defaultElementNamespaceURI: 'urn:general_2019_2.transactions.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2'],
    typeInfos: [{
        localName: 'InterCompanyJournalEntryAccountingBookDetailList',
        propertyInfos: [{
            name: 'interCompanyJournalEntryAccountingBookDetail',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InterCompanyJournalEntryAccountingBookDetail'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'StatisticalJournalEntryLineList',
        propertyInfos: [{
            name: 'statisticalJournalEntryLine',
            minOccurs: 0,
            collection: true,
            typeInfo: '.StatisticalJournalEntryLine'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'JournalEntryLine',
        propertyInfos: [{
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'debit',
            typeInfo: 'Double'
          }, {
            name: 'credit',
            typeInfo: 'Double'
          }, {
            name: 'taxAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lineTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lineTaxRate',
            typeInfo: 'Double'
          }, {
            name: 'debitTax',
            typeInfo: 'Double'
          }, {
            name: 'creditTax',
            typeInfo: 'Double'
          }, {
            name: 'taxBasis',
            typeInfo: 'Double'
          }, {
            name: 'totalAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revenueRecognitionRule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'eliminate',
            typeInfo: 'Boolean'
          }, {
            name: 'schedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'residual'
          }, {
            name: 'scheduleNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'tax1Acct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'AdvInterCompanyJournalEntryAccountingBookDetail',
        propertyInfos: [{
            name: 'accountingBook',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'AdvInterCompanyJournalEntryAccountingBookDetailList',
        propertyInfos: [{
            name: 'interCompanyJournalEntryAccountingBookDetail',
            minOccurs: 0,
            collection: true,
            typeInfo: '.AdvInterCompanyJournalEntryAccountingBookDetail'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'JournalEntry',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'tranId'
          }, {
            name: 'reversalDate',
            typeInfo: 'DateTime'
          }, {
            name: 'reversalDefer',
            typeInfo: 'Boolean'
          }, {
            name: 'parentExpenseAlloc',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBookSpecific',
            typeInfo: 'Boolean'
          }, {
            name: 'accountingBook',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'reversalEntry'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'memo'
          }, {
            name: 'toSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approved',
            typeInfo: 'Boolean'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lineList',
            typeInfo: '.JournalEntryLineList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AdvInterCompanyJournalEntryLineList',
        propertyInfos: [{
            name: 'line',
            minOccurs: 0,
            collection: true,
            typeInfo: '.AdvInterCompanyJournalEntryLine'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PeriodEndJournal',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'transactionNumber'
          }, {
            name: 'accountingBook',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'trandate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'sourceSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'mainAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'creditTotal',
            typeInfo: 'Double'
          }, {
            name: 'debitTotal',
            typeInfo: 'Double'
          }, {
            name: 'lineList',
            typeInfo: '.PeriodEndJournalLineList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AdvInterCompanyJournalEntry',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'reversalDate',
            typeInfo: 'DateTime'
          }, {
            name: 'reversalDefer',
            typeInfo: 'Boolean'
          }, {
            name: 'parentExpenseAlloc',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBookSpecific',
            typeInfo: 'Boolean'
          }, {
            name: 'accountingBook',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'reversalEntry'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'approved',
            typeInfo: 'Boolean'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'performAutoBalance',
            typeInfo: 'Boolean'
          }, {
            name: 'lineList',
            typeInfo: '.AdvInterCompanyJournalEntryLineList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: '.AdvInterCompanyJournalEntryAccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InterCompanyJournalEntryLineList',
        propertyInfos: [{
            name: 'line',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InterCompanyJournalEntryLine'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'StatisticalJournalEntryLine',
        propertyInfos: [{
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'scheduleNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'debit',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lineUnit',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'previewDebit'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'InterCompanyJournalEntryAccountingBookDetail',
        propertyInfos: [{
            name: 'accountingBook',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'InterCompanyJournalEntry',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'tranId'
          }, {
            name: 'reversalDate',
            typeInfo: 'DateTime'
          }, {
            name: 'reversalDefer',
            typeInfo: 'Boolean'
          }, {
            name: 'parentExpenseAlloc',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBookSpecific',
            typeInfo: 'Boolean'
          }, {
            name: 'accountingBook',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'reversalEntry'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'toSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approved',
            typeInfo: 'Boolean'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lineList',
            typeInfo: '.InterCompanyJournalEntryLineList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: '.InterCompanyJournalEntryAccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InterCompanyJournalEntryLine',
        propertyInfos: [{
            name: 'lineSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'debit',
            typeInfo: 'Double'
          }, {
            name: 'credit',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'schedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revenueRecognitionRule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'eliminate',
            typeInfo: 'Boolean'
          }, {
            name: 'residual'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'scheduleNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'tax1Acct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'AdvInterCompanyJournalEntryLine',
        propertyInfos: [{
            name: 'lineSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'debit',
            typeInfo: 'Double'
          }, {
            name: 'credit',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'dueToFromSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'schedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revenueRecognitionRule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'eliminate',
            typeInfo: 'Boolean'
          }, {
            name: 'residual'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'scheduleNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'tax1Acct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lineFxRate',
            typeInfo: 'Double'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'JournalEntryLineList',
        propertyInfos: [{
            name: 'line',
            minOccurs: 0,
            collection: true,
            typeInfo: '.JournalEntryLine'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'StatisticalJournalEntry',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'parentExpenseAlloc',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approved',
            typeInfo: 'Boolean'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'reversalDate',
            typeInfo: 'DateTime'
          }, {
            name: 'memo'
          }, {
            name: 'reversalDefer',
            typeInfo: 'Boolean'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'unitsType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lineList',
            typeInfo: '.StatisticalJournalEntryLineList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PeriodEndJournalLine',
        propertyInfos: [{
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'debit',
            typeInfo: 'Double'
          }, {
            name: 'credit',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PeriodEndJournalLineList',
        propertyInfos: [{
            name: 'periodEndJournalLine',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PeriodEndJournalLine'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }],
    elementInfos: [{
        typeInfo: '.PeriodEndJournal',
        elementName: 'periodEndJournal'
      }, {
        typeInfo: '.JournalEntry',
        elementName: 'JournalEntry'
      }, {
        typeInfo: '.InterCompanyJournalEntry',
        elementName: 'InterCompanyJournalEntry'
      }, {
        typeInfo: '.AdvInterCompanyJournalEntry',
        elementName: 'AdvInterCompanyJournalEntry'
      }, {
        typeInfo: '.StatisticalJournalEntry',
        elementName: 'StatisticalJournalEntry'
      }]
  };
  return {
    com_netsuite_webservices_transactions_general_2019_2: com_netsuite_webservices_transactions_general_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_transactions_general_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_transactions_general_2019_2_Module = com_netsuite_webservices_transactions_general_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_transactions_general_2019_2 = com_netsuite_webservices_transactions_general_2019_2_Module.com_netsuite_webservices_transactions_general_2019_2;
  }
  else {
    var com_netsuite_webservices_transactions_general_2019_2 = com_netsuite_webservices_transactions_general_2019_2_Module.com_netsuite_webservices_transactions_general_2019_2;
  }
}