var com_netsuite_webservices_transactions_bank_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_transactions_bank_2019_2 = {
    name: 'com_netsuite_webservices_transactions_bank_2019_2',
    defaultElementNamespaceURI: 'urn:bank_2019_2.transactions.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_platform_common_2019_2_types'],
    typeInfos: [{
        localName: 'CheckItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CheckItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositCashBack',
        propertyInfos: [{
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }]
      }, {
        localName: 'CheckExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CheckExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositPaymentList',
        propertyInfos: [{
            name: 'depositPayment',
            minOccurs: 0,
            collection: true,
            typeInfo: '.DepositPayment'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositPayment',
        propertyInfos: [{
            name: 'deposit',
            typeInfo: 'Boolean'
          }, {
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'docDate',
            typeInfo: 'DateTime'
          }, {
            name: 'type'
          }, {
            name: 'docNumber'
          }, {
            name: 'memo'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'refNum'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transactionAmount',
            typeInfo: 'Double'
          }, {
            name: 'paymentAmount',
            typeInfo: 'Double'
          }, {
            name: 'lineId',
            typeInfo: 'Long'
          }]
      }, {
        localName: 'CheckItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vendorName'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'description'
          }, {
            name: 'binNumbers'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'rate'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'landedCost',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LandedCost'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'CheckLandedCostList',
        propertyInfos: [{
            name: 'landedCost',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LandedCostSummary'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositCashBackList',
        propertyInfos: [{
            name: 'depositCashBack',
            minOccurs: 0,
            collection: true,
            typeInfo: '.DepositCashBack'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CheckExpense',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'Deposit',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currencyName'
          }, {
            name: 'tranId'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentList',
            typeInfo: '.DepositPaymentList'
          }, {
            name: 'otherList',
            typeInfo: '.DepositOtherList'
          }, {
            name: 'cashBackList',
            typeInfo: '.DepositCashBackList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositOtherList',
        propertyInfos: [{
            name: 'depositOther',
            minOccurs: 0,
            collection: true,
            typeInfo: '.DepositOther'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Check',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'status'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'balance',
            typeInfo: 'Double'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'address'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'voidJournal',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'tranId'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'userTotal',
            typeInfo: 'Double'
          }, {
            name: 'landedCostMethod',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.LandedCostMethod'
          }, {
            name: 'landedCostPerLine',
            typeInfo: 'Boolean'
          }, {
            name: 'transactionNumber'
          }, {
            name: 'expenseList',
            typeInfo: '.CheckExpenseList'
          }, {
            name: 'itemList',
            typeInfo: '.CheckItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'landedCostsList',
            typeInfo: '.CheckLandedCostList'
          }, {
            name: 'billPay',
            typeInfo: 'Boolean'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositOther',
        propertyInfos: [{
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'refNum'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }]
      }],
    elementInfos: [{
        typeInfo: '.Deposit',
        elementName: 'deposit'
      }, {
        typeInfo: '.Check',
        elementName: 'Check'
      }]
  };
  return {
    com_netsuite_webservices_transactions_bank_2019_2: com_netsuite_webservices_transactions_bank_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_transactions_bank_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_transactions_bank_2019_2_Module = com_netsuite_webservices_transactions_bank_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_transactions_bank_2019_2 = com_netsuite_webservices_transactions_bank_2019_2_Module.com_netsuite_webservices_transactions_bank_2019_2;
  }
  else {
    var com_netsuite_webservices_transactions_bank_2019_2 = com_netsuite_webservices_transactions_bank_2019_2_Module.com_netsuite_webservices_transactions_bank_2019_2;
  }
}