var com_netsuite_webservices_transactions_customers_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_transactions_customers_2019_2 = {
    name: 'com_netsuite_webservices_transactions_customers_2019_2',
    defaultElementNamespaceURI: 'urn:customers_2019_2.transactions.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_transactions_customers_2019_2_types', 'com_netsuite_webservices_platform_common_2019_2_types'],
    typeInfos: [{
        localName: 'ReturnAuthorizationSalesTeamList',
        propertyInfos: [{
            name: 'salesTeam',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ReturnAuthorizationSalesTeam'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CreditMemoApply',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'job'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }]
      }, {
        localName: 'CustomerPaymentDepositList',
        propertyInfos: [{
            name: 'deposit',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CustomerPaymentDeposit'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerRefundApply',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'ReturnAuthorization',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vatRegNum'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'source'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'intercoTransaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'intercoStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.IntercoStatus'
          }, {
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'partner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'otherRefNum'
          }, {
            name: 'leadSource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'drAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'fxAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesEffectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revRecSchedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'totalCostEstimate',
            typeInfo: 'Double'
          }, {
            name: 'estGrossProfit',
            typeInfo: 'Double'
          }, {
            name: 'estGrossProfitPercent',
            typeInfo: 'Double'
          }, {
            name: 'revRecStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'revRecEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'excludeCommission',
            typeInfo: 'Boolean'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'currencyName'
          }, {
            name: 'discountItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'discountRate'
          }, {
            name: 'taxItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate',
            typeInfo: 'Double'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'toBeEmailed',
            typeInfo: 'Boolean'
          }, {
            name: 'toBeFaxed',
            typeInfo: 'Boolean'
          }, {
            name: 'messageSel',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'message'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipAddress'
          }, {
            name: 'salesGroup',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'syncSalesTeams',
            typeInfo: 'Boolean'
          }, {
            name: 'revenueStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RevenueStatus'
          }, {
            name: 'recognizedRevenue',
            typeInfo: 'Double'
          }, {
            name: 'deferredRevenue',
            typeInfo: 'Double'
          }, {
            name: 'revRecOnRevCommitment',
            typeInfo: 'Boolean'
          }, {
            name: 'revCommitStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RevenueCommitStatus'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'creditCard',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'ccNumber'
          }, {
            name: 'altSalesTotal',
            typeInfo: 'Double'
          }, {
            name: 'ccExpireDate',
            typeInfo: 'DateTime'
          }, {
            name: 'ccName'
          }, {
            name: 'ccStreet'
          }, {
            name: 'ccZipCode'
          }, {
            name: 'ccApproved',
            typeInfo: 'Boolean'
          }, {
            name: 'pnRefNum'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'discountTotal',
            typeInfo: 'Double'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'creditCardProcessor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'payPalAuthId'
          }, {
            name: 'payPalProcess',
            typeInfo: 'Boolean'
          }, {
            name: 'email'
          }, {
            name: 'fax'
          }, {
            name: 'debitCardIssueNo'
          }, {
            name: 'isTaxable',
            typeInfo: 'Boolean'
          }, {
            name: 'promoCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'status'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'validFrom',
            typeInfo: 'DateTime'
          }, {
            name: 'orderStatus',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.ReturnAuthorizationOrderStatus'
          }, {
            name: 'salesRep',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'giftCert',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contribPct'
          }, {
            name: 'giftCertTotal',
            typeInfo: 'Double'
          }, {
            name: 'giftCertApplied',
            typeInfo: 'Double'
          }, {
            name: 'giftCertAvailable',
            typeInfo: 'Double'
          }, {
            name: 'tranIsVsoeBundle',
            typeInfo: 'Boolean'
          }, {
            name: 'vsoeAutoCalc',
            typeInfo: 'Boolean'
          }, {
            name: 'syncPartnerTeams',
            typeInfo: 'Boolean'
          }, {
            name: 'itemList',
            typeInfo: '.ReturnAuthorizationItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'salesTeamList',
            typeInfo: '.ReturnAuthorizationSalesTeamList'
          }, {
            name: 'partnersList',
            typeInfo: '.ReturnAuthorizationPartnersList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerRefundApplyList',
        propertyInfos: [{
            name: 'apply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CustomerRefundApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositApplication',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'arAcct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'status'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'deposit',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'depDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'applied',
            typeInfo: 'Double'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'unapplied',
            typeInfo: 'Double'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'applyList',
            typeInfo: '.DepositApplicationApplyList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerPaymentApplyList',
        propertyInfos: [{
            name: 'apply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CustomerPaymentApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ChargeSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ChargeSearchBasic'
          }, {
            name: 'billingAccountJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.BillingAccountSearchBasic'
          }, {
            name: 'billingScheduleJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.BillingScheduleSearchBasic'
          }, {
            name: 'chargeEmployeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'invoiceJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'salesOrderJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'usageJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.UsageSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'CreditMemo',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vatRegNum'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesRep',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'partner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contribPct'
          }, {
            name: 'otherRefNum'
          }, {
            name: 'memo'
          }, {
            name: 'excludeCommission',
            typeInfo: 'Boolean'
          }, {
            name: 'leadSource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'balance',
            typeInfo: 'Double'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'onCreditHold'
          }, {
            name: 'amountPaid',
            typeInfo: 'Double'
          }, {
            name: 'salesEffectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'totalCostEstimate',
            typeInfo: 'Double'
          }, {
            name: 'estGrossProfit',
            typeInfo: 'Double'
          }, {
            name: 'estGrossProfitPercent',
            typeInfo: 'Double'
          }, {
            name: 'currencyName'
          }, {
            name: 'promoCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amountRemaining',
            typeInfo: 'Double'
          }, {
            name: 'discountItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'source'
          }, {
            name: 'discountRate'
          }, {
            name: 'isTaxable',
            typeInfo: 'Boolean'
          }, {
            name: 'taxItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate',
            typeInfo: 'Double'
          }, {
            name: 'unapplied',
            typeInfo: 'Double'
          }, {
            name: 'autoApply',
            typeInfo: 'Boolean'
          }, {
            name: 'applied',
            typeInfo: 'Double'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'toBeEmailed',
            typeInfo: 'Boolean'
          }, {
            name: 'email'
          }, {
            name: 'toBeFaxed',
            typeInfo: 'Boolean'
          }, {
            name: 'fax'
          }, {
            name: 'messageSel',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'message'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shippingCost',
            typeInfo: 'Double'
          }, {
            name: 'shippingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'shippingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shippingTax2Rate'
          }, {
            name: 'handlingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'handlingTax2Rate'
          }, {
            name: 'handlingCost',
            typeInfo: 'Double'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'discountTotal',
            typeInfo: 'Double'
          }, {
            name: 'revenueStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RevenueStatus'
          }, {
            name: 'recognizedRevenue',
            typeInfo: 'Double'
          }, {
            name: 'deferredRevenue',
            typeInfo: 'Double'
          }, {
            name: 'revRecOnRevCommitment',
            typeInfo: 'Boolean'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'altShippingCost',
            typeInfo: 'Double'
          }, {
            name: 'altHandlingCost',
            typeInfo: 'Double'
          }, {
            name: 'isMultiShipTo',
            typeInfo: 'Boolean'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'salesGroup',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'syncSalesTeams',
            typeInfo: 'Boolean'
          }, {
            name: 'status'
          }, {
            name: 'giftCert',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'giftCertTotal',
            typeInfo: 'Double'
          }, {
            name: 'giftCertApplied',
            typeInfo: 'Double'
          }, {
            name: 'giftCertAvailable',
            typeInfo: 'Double'
          }, {
            name: 'tranIsVsoeBundle',
            typeInfo: 'Boolean'
          }, {
            name: 'vsoeAutoCalc',
            typeInfo: 'Boolean'
          }, {
            name: 'syncPartnerTeams',
            typeInfo: 'Boolean'
          }, {
            name: 'salesTeamList',
            typeInfo: '.CreditMemoSalesTeamList'
          }, {
            name: 'itemList',
            typeInfo: '.CreditMemoItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'partnersList',
            typeInfo: '.CreditMemoPartnersList'
          }, {
            name: 'applyList',
            typeInfo: '.CreditMemoApplyList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ChargeSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.ChargeSearch'
          }, {
            name: 'columns',
            typeInfo: '.ChargeSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ReturnAuthorizationItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ReturnAuthorizationItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CashRefundItem',
        propertyInfos: [{
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'binNumbers'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'description'
          }, {
            name: 'price',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1'
          }, {
            name: 'taxRate2'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'isTaxable',
            typeInfo: 'Boolean'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revRecSchedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revRecStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'revRecEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'catchUpPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'deferRevRec',
            typeInfo: 'Boolean'
          }, {
            name: 'giftCertFrom'
          }, {
            name: 'costEstimateType',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.ItemCostEstimateType'
          }, {
            name: 'costEstimate',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'giftCertRecipientName'
          }, {
            name: 'giftCertRecipientEmail'
          }, {
            name: 'giftCertMessage'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'giftCertNumber'
          }, {
            name: 'vsoeSopGroup',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoeSopGroup'
          }, {
            name: 'vsoeIsEstimate',
            typeInfo: 'Boolean'
          }, {
            name: 'vsoePrice',
            typeInfo: 'Double'
          }, {
            name: 'vsoeAmount',
            typeInfo: 'Double'
          }, {
            name: 'vsoeAllocation',
            typeInfo: 'Double'
          }, {
            name: 'vsoeDeferral',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoeDeferral'
          }, {
            name: 'vsoePermitDiscount',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoePermitDiscount'
          }, {
            name: 'vsoeDelivered',
            typeInfo: 'Boolean'
          }, {
            name: 'chargeType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'chargesList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'CustomerRefund',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'status'
          }, {
            name: 'transactionNumber'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'balance',
            typeInfo: 'Double'
          }, {
            name: 'arAcct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currencyName'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'address'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'voidJournal',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'tranId'
          }, {
            name: 'debitCardIssueNo'
          }, {
            name: 'creditCardProcessor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'chargeIt',
            typeInfo: 'Boolean'
          }, {
            name: 'pnRefNum'
          }, {
            name: 'validFrom',
            typeInfo: 'DateTime'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentOption',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inputAuthCode'
          }, {
            name: 'inputReferenceCode'
          }, {
            name: 'checkNumber'
          }, {
            name: 'paymentCardCsc'
          }, {
            name: 'paymentProcessingProfile',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingMode',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CustomerRefundHandlingMode'
          }, {
            name: 'outputAuthCode'
          }, {
            name: 'outputReferenceCode'
          }, {
            name: 'paymentOperation',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CustomerRefundPaymentOperation'
          }, {
            name: 'dynamicDescriptor'
          }, {
            name: 'creditCard',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'ccIsPurchaseCardBin',
            typeInfo: 'Boolean'
          }, {
            name: 'ccNumber'
          }, {
            name: 'ccProcessAsPurchaseCard',
            typeInfo: 'Boolean'
          }, {
            name: 'ccExpireDate',
            typeInfo: 'DateTime'
          }, {
            name: 'ccName'
          }, {
            name: 'ccStreet'
          }, {
            name: 'ccZipCode'
          }, {
            name: 'ccApproved',
            typeInfo: 'Boolean'
          }, {
            name: 'applyList',
            typeInfo: '.CustomerRefundApplyList'
          }, {
            name: 'depositList',
            typeInfo: '.CustomerRefundDepositList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ReturnAuthorizationItem',
        propertyInfos: [{
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'quantityReceived',
            typeInfo: 'Double'
          }, {
            name: 'quantityBilled',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'description'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'price',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'revRecTermInMonths',
            typeInfo: 'Long'
          }, {
            name: 'deferRevRec',
            typeInfo: 'Boolean'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'isDropShipment',
            typeInfo: 'Boolean'
          }, {
            name: 'inventoryLocation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventorySubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'catchUpPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'costEstimateType',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.ItemCostEstimateType'
          }, {
            name: 'costEstimate',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revRecSchedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revRecStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'revRecEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'isTaxable',
            typeInfo: 'Boolean'
          }, {
            name: 'giftCertFrom'
          }, {
            name: 'giftCertRecipientName'
          }, {
            name: 'giftCertRecipientEmail'
          }, {
            name: 'giftCertMessage'
          }, {
            name: 'giftCertNumber'
          }, {
            name: 'vsoeSopGroup',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoeSopGroup'
          }, {
            name: 'vsoeIsEstimate',
            typeInfo: 'Boolean'
          }, {
            name: 'vsoePrice',
            typeInfo: 'Double'
          }, {
            name: 'vsoeAmount',
            typeInfo: 'Double'
          }, {
            name: 'altSalesAmt',
            typeInfo: 'Double'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'vsoeAllocation',
            typeInfo: 'Double'
          }, {
            name: 'vsoeDeferral',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoeDeferral'
          }, {
            name: 'vsoePermitDiscount',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoePermitDiscount'
          }, {
            name: 'vsoeDelivered',
            typeInfo: 'Boolean'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'CustomerPaymentDeposit',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'depositDate',
            typeInfo: 'DateTime'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'remaining',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CustomerPayment',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'arAcct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'balance',
            typeInfo: 'Double'
          }, {
            name: 'pending',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'payment',
            typeInfo: 'Double'
          }, {
            name: 'autoApply',
            typeInfo: 'Boolean'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'ccIsPurchaseCardBin',
            typeInfo: 'Boolean'
          }, {
            name: 'memo'
          }, {
            name: 'ccProcessAsPurchaseCard',
            typeInfo: 'Boolean'
          }, {
            name: 'checkNum'
          }, {
            name: 'currencyName'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'creditCard',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'chargeIt',
            typeInfo: 'Boolean'
          }, {
            name: 'ccNumber'
          }, {
            name: 'ccExpireDate',
            typeInfo: 'DateTime'
          }, {
            name: 'ccName'
          }, {
            name: 'ccStreet'
          }, {
            name: 'ccZipCode'
          }, {
            name: 'ccApproved',
            typeInfo: 'Boolean'
          }, {
            name: 'authCode'
          }, {
            name: 'ccAvsStreetMatch',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.AvsMatchCode'
          }, {
            name: 'ccAvsZipMatch',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.AvsMatchCode'
          }, {
            name: 'isRecurringPayment',
            typeInfo: 'Boolean'
          }, {
            name: 'ccSecurityCode'
          }, {
            name: 'ignoreAvs',
            typeInfo: 'Boolean'
          }, {
            name: 'ccSecurityCodeMatch',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.AvsMatchCode'
          }, {
            name: 'threeDStatusCode'
          }, {
            name: 'pnRefNum'
          }, {
            name: 'creditCardProcessor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'debitCardIssueNo'
          }, {
            name: 'validFrom',
            typeInfo: 'DateTime'
          }, {
            name: 'undepFunds',
            typeInfo: 'Boolean'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'applied',
            typeInfo: 'Double'
          }, {
            name: 'unapplied',
            typeInfo: 'Double'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentOption',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inputAuthCode'
          }, {
            name: 'inputReferenceCode'
          }, {
            name: 'checkNumber'
          }, {
            name: 'paymentCardCsc'
          }, {
            name: 'paymentProcessingProfile',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingMode',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CustomerPaymentHandlingMode'
          }, {
            name: 'outputAuthCode'
          }, {
            name: 'outputReferenceCode'
          }, {
            name: 'paymentOperation',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CustomerPaymentPaymentOperation'
          }, {
            name: 'dynamicDescriptor'
          }, {
            name: 'status'
          }, {
            name: 'applyList',
            typeInfo: '.CustomerPaymentApplyList'
          }, {
            name: 'creditList',
            typeInfo: '.CustomerPaymentCreditList'
          }, {
            name: 'depositList',
            typeInfo: '.CustomerPaymentDepositList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CreditMemoApplyList',
        propertyInfos: [{
            name: 'apply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CreditMemoApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CashRefundSalesTeam',
        propertyInfos: [{
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesRole',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isPrimary',
            typeInfo: 'Boolean'
          }, {
            name: 'contribution',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CustomerPaymentCredit',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'creditDate',
            typeInfo: 'DateTime'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'appliedTo'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CustomerDeposit',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'status'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesOrder',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'payment',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'ccIsPurchaseCardBin',
            typeInfo: 'Boolean'
          }, {
            name: 'memo'
          }, {
            name: 'ccProcessAsPurchaseCard',
            typeInfo: 'Boolean'
          }, {
            name: 'currencyName'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'checkNum'
          }, {
            name: 'creditCardProcessor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'creditCard',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'ccSecurityCode'
          }, {
            name: 'ccNumber'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paymentOption',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inputAuthCode'
          }, {
            name: 'inputReferenceCode'
          }, {
            name: 'checkNumber'
          }, {
            name: 'paymentCardCsc'
          }, {
            name: 'paymentProcessingProfile',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingMode',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CustomerDepositHandlingMode'
          }, {
            name: 'outputAuthCode'
          }, {
            name: 'outputReferenceCode'
          }, {
            name: 'paymentOperation',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CustomerDepositPaymentOperation'
          }, {
            name: 'dynamicDescriptor'
          }, {
            name: 'ccExpireDate',
            typeInfo: 'DateTime'
          }, {
            name: 'debitCardIssueNo'
          }, {
            name: 'validFrom',
            typeInfo: 'DateTime'
          }, {
            name: 'ccName'
          }, {
            name: 'ccStreet'
          }, {
            name: 'ccZipCode'
          }, {
            name: 'chargeIt',
            typeInfo: 'Boolean'
          }, {
            name: 'ccApproved',
            typeInfo: 'Boolean'
          }, {
            name: 'pnRefNum'
          }, {
            name: 'authCode'
          }, {
            name: 'ccAvsStreetMatch',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.AvsMatchCode'
          }, {
            name: 'softDescriptor'
          }, {
            name: 'ccAvsZipMatch',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.AvsMatchCode'
          }, {
            name: 'isRecurringPayment',
            typeInfo: 'Boolean'
          }, {
            name: 'ccSecurityCodeMatch',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.AvsMatchCode'
          }, {
            name: 'threeDStatusCode'
          }, {
            name: 'ignoreAvs',
            typeInfo: 'Boolean'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'undepFunds',
            typeInfo: 'Boolean'
          }, {
            name: 'tranId'
          }, {
            name: 'applyList',
            typeInfo: '.CustomerDepositApplyList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerDepositApplyList',
        propertyInfos: [{
            name: 'customerDepositApply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CustomerDepositApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositApplicationApplyList',
        propertyInfos: [{
            name: 'apply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.DepositApplicationApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerPaymentApply',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'job'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'discDate',
            typeInfo: 'DateTime'
          }, {
            name: 'discAmt',
            typeInfo: 'Double'
          }, {
            name: 'disc',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'ReturnAuthorizationPartnersList',
        propertyInfos: [{
            name: 'partners',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Partners'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CashRefundSalesTeamList',
        propertyInfos: [{
            name: 'salesTeam',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CashRefundSalesTeam'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CreditMemoItem',
        propertyInfos: [{
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'description'
          }, {
            name: 'binNumbers'
          }, {
            name: 'price',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'isTaxable',
            typeInfo: 'Boolean'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'shipAddress',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipCarrier',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.ShippingCarrier'
          }, {
            name: 'shipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'costEstimateType',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.ItemCostEstimateType'
          }, {
            name: 'costEstimate',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'revRecSchedule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revRecStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'revRecTermInMonths',
            typeInfo: 'Long'
          }, {
            name: 'revRecEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'deferRevRec',
            typeInfo: 'Boolean'
          }, {
            name: 'giftCertFrom'
          }, {
            name: 'giftCertRecipientName'
          }, {
            name: 'giftCertRecipientEmail'
          }, {
            name: 'giftCertMessage'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'giftCertNumber'
          }, {
            name: 'vsoeSopGroup',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoeSopGroup'
          }, {
            name: 'vsoeIsEstimate',
            typeInfo: 'Boolean'
          }, {
            name: 'vsoePrice',
            typeInfo: 'Double'
          }, {
            name: 'vsoeAmount',
            typeInfo: 'Double'
          }, {
            name: 'vsoeAllocation',
            typeInfo: 'Double'
          }, {
            name: 'vsoeDeferral',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoeDeferral'
          }, {
            name: 'vsoePermitDiscount',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.VsoePermitDiscount'
          }, {
            name: 'vsoeDelivered',
            typeInfo: 'Boolean'
          }, {
            name: 'catchUpPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'chargeType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subscriptionLine',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'chargesList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'CashRefundItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CashRefundItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CashRefundPartnersList',
        propertyInfos: [{
            name: 'partners',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Partners'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CreditMemoSalesTeam',
        propertyInfos: [{
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesRole',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isPrimary',
            typeInfo: 'Boolean'
          }, {
            name: 'contribution',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CashRefund',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vatRegNum'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'source'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'leadSource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesRep',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'partner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contribPct'
          }, {
            name: 'otherRefNum'
          }, {
            name: 'memo'
          }, {
            name: 'salesEffectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'refundCheck',
            typeInfo: 'Boolean'
          }, {
            name: 'toPrint2',
            typeInfo: 'Boolean'
          }, {
            name: 'excludeCommission',
            typeInfo: 'Boolean'
          }, {
            name: 'totalCostEstimate',
            typeInfo: 'Double'
          }, {
            name: 'estGrossProfit',
            typeInfo: 'Double'
          }, {
            name: 'estGrossProfitPercent',
            typeInfo: 'Double'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'currencyName'
          }, {
            name: 'promoCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'discountItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'discountRate'
          }, {
            name: 'isTaxable',
            typeInfo: 'Boolean'
          }, {
            name: 'taxItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate',
            typeInfo: 'Double'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'toBeEmailed',
            typeInfo: 'Boolean'
          }, {
            name: 'email'
          }, {
            name: 'toBeFaxed',
            typeInfo: 'Boolean'
          }, {
            name: 'fax'
          }, {
            name: 'messageSel',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'message'
          }, {
            name: 'paymentOption',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inputAuthCode'
          }, {
            name: 'inputReferenceCode'
          }, {
            name: 'checkNumber'
          }, {
            name: 'paymentCardCsc'
          }, {
            name: 'paymentProcessingProfile',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingMode',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CashRefundHandlingMode'
          }, {
            name: 'outputAuthCode'
          }, {
            name: 'outputReferenceCode'
          }, {
            name: 'paymentOperation',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.CashRefundPaymentOperation'
          }, {
            name: 'dynamicDescriptor'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shippingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shippingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'shippingTax2Rate'
          }, {
            name: 'shippingCost',
            typeInfo: 'Double'
          }, {
            name: 'handlingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'handlingTax2Rate'
          }, {
            name: 'handlingCost',
            typeInfo: 'Double'
          }, {
            name: 'salesGroup',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'syncSalesTeams',
            typeInfo: 'Boolean'
          }, {
            name: 'paymentMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revenueStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RevenueStatus'
          }, {
            name: 'recognizedRevenue',
            typeInfo: 'Double'
          }, {
            name: 'deferredRevenue',
            typeInfo: 'Double'
          }, {
            name: 'revRecOnRevCommitment',
            typeInfo: 'Boolean'
          }, {
            name: 'creditCard',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'chargeIt',
            typeInfo: 'Boolean'
          }, {
            name: 'ccNumber'
          }, {
            name: 'ccExpireDate',
            typeInfo: 'DateTime'
          }, {
            name: 'ccName'
          }, {
            name: 'ccStreet'
          }, {
            name: 'ccZipCode'
          }, {
            name: 'ccApproved',
            typeInfo: 'Boolean'
          }, {
            name: 'creditCardProcessor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'debitCardIssueNo'
          }, {
            name: 'pnRefNum'
          }, {
            name: 'validFrom',
            typeInfo: 'DateTime'
          }, {
            name: 'payPalTranId'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'ccIsPurchaseCardBin',
            typeInfo: 'Boolean'
          }, {
            name: 'discountTotal',
            typeInfo: 'Double'
          }, {
            name: 'ccProcessAsPurchaseCard',
            typeInfo: 'Boolean'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'altShippingCost',
            typeInfo: 'Double'
          }, {
            name: 'payPalStatus'
          }, {
            name: 'altHandlingCost',
            typeInfo: 'Double'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'payPalAuthId'
          }, {
            name: 'status'
          }, {
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'giftCert',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'giftCertTotal',
            typeInfo: 'Double'
          }, {
            name: 'giftCertApplied',
            typeInfo: 'Double'
          }, {
            name: 'giftCertAvailable',
            typeInfo: 'Double'
          }, {
            name: 'tranIsVsoeBundle',
            typeInfo: 'Boolean'
          }, {
            name: 'payPalProcess',
            typeInfo: 'Boolean'
          }, {
            name: 'vsoeAutoCalc',
            typeInfo: 'Boolean'
          }, {
            name: 'syncPartnerTeams',
            typeInfo: 'Boolean'
          }, {
            name: 'itemList',
            typeInfo: '.CashRefundItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'salesTeamList',
            typeInfo: '.CashRefundSalesTeamList'
          }, {
            name: 'partnersList',
            typeInfo: '.CashRefundPartnersList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerDepositApply',
        propertyInfos: [{
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'job'
          }]
      }, {
        localName: 'ChargeSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ChargeSearchRowBasic'
          }, {
            name: 'billingAccountJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.BillingAccountSearchRowBasic'
          }, {
            name: 'billingScheduleJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.BillingScheduleSearchRowBasic'
          }, {
            name: 'chargeEmployeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'invoiceJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchRowBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'salesOrderJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'usageJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.UsageSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'CreditMemoSalesTeamList',
        propertyInfos: [{
            name: 'salesTeam',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CreditMemoSalesTeam'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerPaymentCreditList',
        propertyInfos: [{
            name: 'credit',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CustomerPaymentCredit'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ReturnAuthorizationSalesTeam',
        propertyInfos: [{
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesRole',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isPrimary',
            typeInfo: 'Boolean'
          }, {
            name: 'contribution',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CreditMemoPartnersList',
        propertyInfos: [{
            name: 'partners',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Partners'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CreditMemoItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CreditMemoItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CustomerRefundDeposit',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'depositDate',
            typeInfo: 'DateTime'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'remaining',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CustomerRefundDepositList',
        propertyInfos: [{
            name: 'customerRefundDeposit',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CustomerRefundDeposit'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Charge',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesOrder',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billTo',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billingAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'stage',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.ChargeStage'
          }, {
            name: 'chargeDate',
            typeInfo: 'DateTime'
          }, {
            name: 'use',
            typeInfo: 'com_netsuite_webservices_transactions_customers_2019_2_types.ChargeUse'
          }, {
            name: 'chargeType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'projectTask',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'timeRecord',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'billingItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transactionLine',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'salesOrderLine',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subscriptionLine',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'invoice',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'invoiceLine',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rule',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'runId'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'DepositApplicationApply',
        propertyInfos: [{
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'job'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }],
    elementInfos: [{
        typeInfo: '.CustomerRefund',
        elementName: 'CustomerRefund'
      }, {
        typeInfo: '.ReturnAuthorization',
        elementName: 'ReturnAuthorization'
      }, {
        typeInfo: '.Charge',
        elementName: 'charge'
      }, {
        typeInfo: '.ChargeSearch',
        elementName: 'chargeSearch'
      }, {
        typeInfo: '.CreditMemo',
        elementName: 'CreditMemo'
      }, {
        typeInfo: '.CashRefund',
        elementName: 'CashRefund'
      }, {
        typeInfo: '.DepositApplication',
        elementName: 'DepositApplication'
      }, {
        typeInfo: '.CustomerDeposit',
        elementName: 'CustomerDeposit'
      }, {
        typeInfo: '.CustomerPayment',
        elementName: 'CustomerPayment'
      }]
  };
  return {
    com_netsuite_webservices_transactions_customers_2019_2: com_netsuite_webservices_transactions_customers_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_transactions_customers_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_transactions_customers_2019_2_Module = com_netsuite_webservices_transactions_customers_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_transactions_customers_2019_2 = com_netsuite_webservices_transactions_customers_2019_2_Module.com_netsuite_webservices_transactions_customers_2019_2;
  }
  else {
    var com_netsuite_webservices_transactions_customers_2019_2 = com_netsuite_webservices_transactions_customers_2019_2_Module.com_netsuite_webservices_transactions_customers_2019_2;
  }
}