var com_netsuite_webservices_lists_marketing_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_lists_marketing_2019_2 = {
    name: 'com_netsuite_webservices_lists_marketing_2019_2',
    defaultElementNamespaceURI: 'urn:marketing_2019_2.lists.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_lists_marketing_2019_2_types'],
    typeInfos: [{
        localName: 'CampaignEmail',
        propertyInfos: [{
            name: 'internalId'
          }, {
            name: 'campaignGroup',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'template',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'subscription',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'channel',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'cost',
            typeInfo: 'Double'
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.CampaignCampaignEmailStatus'
          }, {
            name: 'dateScheduled',
            typeInfo: 'DateTime'
          }, {
            name: 'promoCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'CampaignEventResponse',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'type'
          }, {
            name: 'dateSent',
            typeInfo: 'DateTime'
          }, {
            name: 'sent',
            typeInfo: 'Double'
          }, {
            name: 'opened',
            typeInfo: 'Double'
          }, {
            name: 'openedRatio',
            typeInfo: 'Double'
          }, {
            name: 'clickedThru',
            typeInfo: 'Double'
          }, {
            name: 'clickedThruRatio',
            typeInfo: 'Double'
          }, {
            name: 'responded',
            typeInfo: 'Long'
          }, {
            name: 'respondedRatio',
            typeInfo: 'Double'
          }, {
            name: 'unsubscribed',
            typeInfo: 'Long'
          }, {
            name: 'unsubscribedRatio',
            typeInfo: 'Double'
          }, {
            name: 'bounced',
            typeInfo: 'Long'
          }, {
            name: 'bouncedRatio',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CouponCodeSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CouponCodeSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }]
      }, {
        localName: 'PromotionCodeItems',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'CampaignCategory',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'parent',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'leadSource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'isexternal',
            typeInfo: 'Boolean'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PromotionCodeSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.PromotionCodeSearch'
          }, {
            name: 'columns',
            typeInfo: '.PromotionCodeSearchRow'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignDirectMailList',
        propertyInfos: [{
            name: 'campaignDirectMail',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CampaignDirectMail'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignResponseResponses',
        propertyInfos: [{
            name: 'response'
          }, {
            name: 'responseDate'
          }, {
            name: 'author'
          }, {
            name: 'note'
          }]
      }, {
        localName: 'CampaignDirectMail',
        propertyInfos: [{
            name: 'internalId'
          }, {
            name: 'campaignGroup',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'template',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'subscription',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'channel',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'cost',
            typeInfo: 'Double'
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.CampaignCampaignDirectMailStatus'
          }, {
            name: 'dateScheduled',
            typeInfo: 'DateTime'
          }, {
            name: 'promoCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PromotionCodeSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PromotionCodeSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'PromotionCodeCurrencyList',
        propertyInfos: [{
            name: 'currency',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PromotionCodeCurrency'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignEmailList',
        propertyInfos: [{
            name: 'campaignEmail',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CampaignEmail'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignResponseResponsesList',
        propertyInfos: [{
            name: 'responses',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CampaignResponseResponses'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignEventResponseList',
        propertyInfos: [{
            name: 'eventResponse',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CampaignEventResponse'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchBasic'
          }, {
            name: 'campaignRecipientJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchBasic'
          }, {
            name: 'messagesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchBasic'
          }, {
            name: 'promotionCodeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PromotionCodeSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'CampaignAudience',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'description'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CouponCode',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'promotion',
            required: true,
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'code',
            required: true
          }, {
            name: 'recipient',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'dateSent',
            typeInfo: 'DateTime'
          }, {
            name: 'used',
            typeInfo: 'Boolean'
          }, {
            name: 'useCount',
            typeInfo: 'Long'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignChannel',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'eventType',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.CampaignChannelEventType'
          }, {
            name: 'description'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PromotionCodeCurrency',
        propertyInfos: [{
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'minimumOrderAmount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CampaignSearchEngine',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'description'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignOffer',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'description'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PromotionCodeItemsList',
        propertyInfos: [{
            name: 'items',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PromotionCodeItems'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PromotionCodePartnersList',
        propertyInfos: [{
            name: 'partners',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PromotionCodePartners'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CouponCodeSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CouponCodeSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }]
      }, {
        localName: 'CouponCodeSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.CouponCodeSearch'
          }, {
            name: 'columns',
            typeInfo: '.CouponCodeSearchRow'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignEvent',
        propertyInfos: [{
            name: 'internalId'
          }, {
            name: 'campaignGroup',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'subscription',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'channel',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'cost',
            typeInfo: 'Double'
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.CampaignCampaignEventStatus'
          }, {
            name: 'dateScheduled',
            typeInfo: 'DateTime'
          }, {
            name: 'promoCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PromotionCodePartners',
        propertyInfos: [{
            name: 'partner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'code'
          }]
      }, {
        localName: 'PromotionCode',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'implementation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'useType',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.PromotionCodeUseType'
          }, {
            name: 'displayLineDiscounts',
            typeInfo: 'Boolean'
          }, {
            name: 'code'
          }, {
            name: 'codePattern'
          }, {
            name: 'numberToGenerate',
            typeInfo: 'Long'
          }, {
            name: 'description'
          }, {
            name: 'locationList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'discount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'discountType',
            typeInfo: 'Boolean'
          }, {
            name: 'applyDiscountTo',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.PromotionCodeApplyDiscountTo'
          }, {
            name: 'freeShipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'minimumOrderAmount',
            typeInfo: 'Double'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'isPublic',
            typeInfo: 'Boolean'
          }, {
            name: 'currencyList',
            typeInfo: '.PromotionCodeCurrencyList'
          }, {
            name: 'excludeItems',
            typeInfo: 'Boolean'
          }, {
            name: 'name'
          }, {
            name: 'itemsList',
            typeInfo: '.PromotionCodeItemsList'
          }, {
            name: 'partnersList',
            typeInfo: '.PromotionCodePartnersList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignVertical',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'description'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignFamily',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'description'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchRowBasic'
          }, {
            name: 'campaignRecipientJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchRowBasic'
          }, {
            name: 'messagesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchRowBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchRowBasic'
          }, {
            name: 'promotionCodeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PromotionCodeSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'Campaign',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'campaignId'
          }, {
            name: 'title'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'owner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'url'
          }, {
            name: 'baseCost',
            typeInfo: 'Double'
          }, {
            name: 'cost',
            typeInfo: 'Double'
          }, {
            name: 'expectedRevenue',
            typeInfo: 'Double'
          }, {
            name: 'message'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'local',
            typeInfo: 'Boolean'
          }, {
            name: 'totalRevenue',
            typeInfo: 'Double'
          }, {
            name: 'roi',
            typeInfo: 'Double'
          }, {
            name: 'profit',
            typeInfo: 'Double'
          }, {
            name: 'costPerCustomer',
            typeInfo: 'Double'
          }, {
            name: 'convCostPerCustomer',
            typeInfo: 'Double'
          }, {
            name: 'conversions',
            typeInfo: 'Long'
          }, {
            name: 'leadsGenerated',
            typeInfo: 'Long'
          }, {
            name: 'uniqueVisitors',
            typeInfo: 'Long'
          }, {
            name: 'vertical',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'audience',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'offer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'promotionCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'itemList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'family',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'searchEngine',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'keyword'
          }, {
            name: 'campaignEmailList',
            typeInfo: '.CampaignEmailList'
          }, {
            name: 'campaignDirectMailList',
            typeInfo: '.CampaignDirectMailList'
          }, {
            name: 'campaignEventList',
            typeInfo: '.CampaignEventList'
          }, {
            name: 'eventResponseList',
            typeInfo: '.CampaignEventResponseList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignEventList',
        propertyInfos: [{
            name: 'campaignEvent',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CampaignEvent'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.CampaignSearch'
          }, {
            name: 'columns',
            typeInfo: '.CampaignSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PromotionCodeSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PromotionCodeSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'CampaignResponse',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'leadSource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'campaignEvent',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'campaignResponseDate',
            typeInfo: 'DateTime'
          }, {
            name: 'channel'
          }, {
            name: 'response',
            typeInfo: 'com_netsuite_webservices_lists_marketing_2019_2_types.CampaignResponseResponse'
          }, {
            name: 'note'
          }, {
            name: 'responsesList',
            typeInfo: '.CampaignResponseResponsesList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CampaignSubscription',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'description'
          }, {
            name: 'subscribedByDefault',
            typeInfo: 'Boolean'
          }, {
            name: 'unsubscribed',
            typeInfo: 'Boolean'
          }, {
            name: 'externalName'
          }, {
            name: 'externalDescription'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }],
    elementInfos: [{
        typeInfo: '.CampaignResponse',
        elementName: 'CampaignResponse'
      }, {
        typeInfo: '.CampaignCategory',
        elementName: 'CampaignCategory'
      }, {
        typeInfo: '.Campaign',
        elementName: 'Campaign'
      }, {
        typeInfo: '.CampaignSearch',
        elementName: 'campaignSearch'
      }, {
        typeInfo: '.CampaignFamily',
        elementName: 'CampaignFamily'
      }, {
        typeInfo: '.CouponCode',
        elementName: 'couponCode'
      }, {
        typeInfo: '.CampaignVertical',
        elementName: 'CampaignVertical'
      }, {
        typeInfo: '.PromotionCodeSearch',
        elementName: 'promotionCodeSearch'
      }, {
        typeInfo: '.CampaignOffer',
        elementName: 'CampaignOffer'
      }, {
        typeInfo: '.CampaignChannel',
        elementName: 'CampaignChannel'
      }, {
        typeInfo: '.CampaignSubscription',
        elementName: 'CampaignSubscription'
      }, {
        typeInfo: '.PromotionCode',
        elementName: 'promotionCode'
      }, {
        typeInfo: '.CouponCodeSearch',
        elementName: 'couponCodeSearch'
      }, {
        typeInfo: '.CampaignAudience',
        elementName: 'CampaignAudience'
      }, {
        typeInfo: '.CampaignSearchEngine',
        elementName: 'CampaignSearchEngine'
      }]
  };
  return {
    com_netsuite_webservices_lists_marketing_2019_2: com_netsuite_webservices_lists_marketing_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_lists_marketing_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_lists_marketing_2019_2_Module = com_netsuite_webservices_lists_marketing_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_lists_marketing_2019_2 = com_netsuite_webservices_lists_marketing_2019_2_Module.com_netsuite_webservices_lists_marketing_2019_2;
  }
  else {
    var com_netsuite_webservices_lists_marketing_2019_2 = com_netsuite_webservices_lists_marketing_2019_2_Module.com_netsuite_webservices_lists_marketing_2019_2;
  }
}