var com_netsuite_webservices_activities_scheduling_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_activities_scheduling_2019_2 = {
    name: 'com_netsuite_webservices_activities_scheduling_2019_2',
    defaultElementNamespaceURI: 'urn:scheduling_2019_2.activities.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_activities_scheduling_2019_2_types', 'com_netsuite_webservices_platform_common_2019_2_types', 'com_netsuite_webservices_platform_core_2019_2_types'],
    typeInfos: [{
        localName: 'TaskContactList',
        propertyInfos: [{
            name: 'contact',
            minOccurs: 0,
            collection: true,
            typeInfo: '.TaskContact'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTaskSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.ProjectTaskSearch'
          }, {
            name: 'columns',
            typeInfo: '.ProjectTaskSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CalendarEventAttendeeList',
        propertyInfos: [{
            name: 'attendee',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CalendarEventAttendee'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TaskSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchBasic'
          }, {
            name: 'assignedJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'companyCustomerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'PhoneCallTimeItemList',
        propertyInfos: [{
            name: 'timeItem',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CalendarEventSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.CalendarEventSearch'
          }, {
            name: 'columns',
            typeInfo: '.CalendarEventSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ResourceAllocationSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchRowBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'projectTaskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchRowBasic'
          }, {
            name: 'requestedByJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'resourceJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'ProjectTaskPredecessor',
        propertyInfos: [{
            name: 'task',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'type',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.ProjectTaskPredecessorPredecessorType'
          }, {
            name: 'lagDays',
            typeInfo: 'Double'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'ResourceAllocationSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'projectTaskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchBasic'
          }, {
            name: 'requestedByJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'resourceJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'CalendarEventResourceList',
        propertyInfos: [{
            name: 'resource',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CalendarEventResource'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ExclusionDateList',
        propertyInfos: [{
            name: 'exclusionDate',
            required: true,
            collection: true,
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'PhoneCallContactList',
        propertyInfos: [{
            name: 'contact',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PhoneCallContact'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CalendarEventTimeItemList',
        propertyInfos: [{
            name: 'timeItem',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CalendarEventResource',
        propertyInfos: [{
            name: 'resource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location'
          }]
      }, {
        localName: 'ResourceAllocationSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.ResourceAllocationSearch'
          }, {
            name: 'columns',
            typeInfo: '.ResourceAllocationSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTaskPredecessorList',
        propertyInfos: [{
            name: 'projectTaskPredecessor',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ProjectTaskPredecessor'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CalendarEventSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchBasic'
          }, {
            name: 'attendeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'attendeeContactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchBasic'
          }, {
            name: 'attendeeCustomerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'TaskTimeItemList',
        propertyInfos: [{
            name: 'timeItem',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CalendarEvent',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'company',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contact',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'supportCase',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'period',
            typeInfo: 'Long'
          }, {
            name: 'frequency',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RecurrenceFrequency'
          }, {
            name: 'recurrenceDowMaskList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.RecurrenceDowMaskList'
          }, {
            name: 'recurrenceDow',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RecurrenceDow'
          }, {
            name: 'recurrenceDowim',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.RecurrenceDowim'
          }, {
            name: 'seriesStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endByDate',
            typeInfo: 'DateTime'
          }, {
            name: 'noEndDate',
            typeInfo: 'Boolean'
          }, {
            name: 'sendEmail',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'title'
          }, {
            name: 'recurrence'
          }, {
            name: 'location'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'allDayEvent',
            typeInfo: 'Boolean'
          }, {
            name: 'timedEvent',
            typeInfo: 'Boolean'
          }, {
            name: 'reminderType',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.CalendarEventReminderType'
          }, {
            name: 'reminderMinutes',
            values: ['_none', '_0minutes', '_10minutes', '_12hours', '_15minutes', '_1day', '_1hour', '_1week', '_2days', '_2hours', '_30minutes', '_3days', '_3hours', '_4hours', '_5hours', '_5minutes', '_8hours']
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.CalendarEventStatus'
          }, {
            name: 'accessLevel',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.CalendarEventAccessLevel'
          }, {
            name: 'organizer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'message'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'exclusionDateList',
            typeInfo: '.ExclusionDateList'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'owner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'attendeeList',
            typeInfo: '.CalendarEventAttendeeList'
          }, {
            name: 'resourceList',
            typeInfo: '.CalendarEventResourceList'
          }, {
            name: 'timeItemList',
            typeInfo: '.CalendarEventTimeItemList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTaskSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchRowBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'predecessorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchRowBasic'
          }, {
            name: 'projectTaskAssignmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskAssignmentSearchRowBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchRowBasic'
          }, {
            name: 'successorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchRowBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'PhoneCall',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'message'
          }, {
            name: 'company',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contact',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'supportCase',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'milestone',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'title'
          }, {
            name: 'owner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'assigned',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'sendEmail',
            typeInfo: 'Boolean'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'timedEvent',
            typeInfo: 'Boolean'
          }, {
            name: 'completedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'phone'
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.PhoneCallStatus'
          }, {
            name: 'priority',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.PhoneCallPriority'
          }, {
            name: 'accessLevel',
            typeInfo: 'Boolean'
          }, {
            name: 'reminderType',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.PhoneCallReminderType'
          }, {
            name: 'reminderMinutes',
            values: ['_0minutes', '_10minutes', '_12hours', '_15minutes', '_1day', '_1hour', '_1week', '_2days', '_2hours', '_30minutes', '_3days', '_3hours', '_4hours', '_5hours', '_5minutes', '_8hours']
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'contactList',
            typeInfo: '.PhoneCallContactList'
          }, {
            name: 'timeItemList',
            typeInfo: '.PhoneCallTimeItemList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTask',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'eventId',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'percentTimeComplete',
            typeInfo: 'Double'
          }, {
            name: 'title'
          }, {
            name: 'company',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contact',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'order',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'owner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'parent',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'priority',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'estimatedWork',
            typeInfo: 'Double'
          }, {
            name: 'estimatedWorkBaseline',
            typeInfo: 'Double'
          }, {
            name: 'constraintType',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.ProjectTaskConstraintType'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'startDateBaseline',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'finishByDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDateBaseline',
            typeInfo: 'DateTime'
          }, {
            name: 'actualWork',
            typeInfo: 'Double'
          }, {
            name: 'remainingWork',
            typeInfo: 'Double'
          }, {
            name: 'message'
          }, {
            name: 'isMilestone',
            typeInfo: 'Boolean'
          }, {
            name: 'isOnCriticalPath'
          }, {
            name: 'slackMinutes',
            typeInfo: 'Double'
          }, {
            name: 'lateEnd',
            typeInfo: 'DateTime'
          }, {
            name: 'lateStart',
            typeInfo: 'DateTime'
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.ProjectTaskStatus'
          }, {
            name: 'nonBillableTask',
            typeInfo: 'Boolean'
          }, {
            name: 'assigneeList',
            typeInfo: '.ProjectTaskAssigneeList'
          }, {
            name: 'predecessorList',
            typeInfo: '.ProjectTaskPredecessorList'
          }, {
            name: 'timeItemList',
            typeInfo: '.ProjectTaskTimeItemList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TaskSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.TaskSearch'
          }, {
            name: 'columns',
            typeInfo: '.TaskSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PhoneCallSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.PhoneCallSearch'
          }, {
            name: 'columns',
            typeInfo: '.PhoneCallSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTaskAssignee',
        propertyInfos: [{
            name: 'resource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'units',
            typeInfo: 'Double'
          }, {
            name: 'serviceItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'estimatedWork',
            typeInfo: 'Double'
          }, {
            name: 'unitCost',
            typeInfo: 'Double'
          }, {
            name: 'unitPrice',
            typeInfo: 'Double'
          }, {
            name: 'cost',
            typeInfo: 'Double'
          }, {
            name: 'price',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'CalendarEventSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchRowBasic'
          }, {
            name: 'attendeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'attendeeContactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchRowBasic'
          }, {
            name: 'attendeeCustomerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchRowBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchRowBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchRowBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'PhoneCallContact',
        propertyInfos: [{
            name: 'company',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contact',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'phone'
          }, {
            name: 'email'
          }]
      }, {
        localName: 'CalendarEventAttendee',
        propertyInfos: [{
            name: 'sendEmail',
            typeInfo: 'Boolean'
          }, {
            name: 'attendee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'response',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2_types.CalendarEventAttendeeResponse'
          }, {
            name: 'attendance',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.CalendarEventAttendeeAttendance'
          }]
      }, {
        localName: 'TaskSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchRowBasic'
          }, {
            name: 'assignedJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'companyCustomerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchRowBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchRowBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchRowBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'ProjectTaskAssigneeList',
        propertyInfos: [{
            name: 'projectTaskAssignee',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ProjectTaskAssignee'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PhoneCallSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'companyCustomerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchRowBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchRowBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchRowBasic'
          }, {
            name: 'participantJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'Task',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'company',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contact',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'supportCase',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'milestone',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'title'
          }, {
            name: 'assigned',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'sendEmail',
            typeInfo: 'Boolean'
          }, {
            name: 'timedEvent',
            typeInfo: 'Boolean'
          }, {
            name: 'estimatedTime',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'estimatedTimeOverride',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'actualTime',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'timeRemaining',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'percentTimeComplete',
            typeInfo: 'Double'
          }, {
            name: 'percentComplete',
            typeInfo: 'Double'
          }, {
            name: 'parent',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'dueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'completedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'priority',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.TaskPriority'
          }, {
            name: 'status',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.TaskStatus'
          }, {
            name: 'message'
          }, {
            name: 'accessLevel',
            typeInfo: 'Boolean'
          }, {
            name: 'reminderType',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.TaskReminderType'
          }, {
            name: 'reminderMinutes',
            values: ['_0minutes', '_10minutes', '_12hours', '_15minutes', '_1day', '_1hour', '_1week', '_2days', '_2hours', '_30minutes', '_3days', '_3hours', '_4hours', '_5hours', '_5minutes', '_8hours']
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'owner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contactList',
            typeInfo: '.TaskContactList'
          }, {
            name: 'timeItemList',
            typeInfo: '.TaskTimeItemList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TaskContact',
        propertyInfos: [{
            name: 'company',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'contact',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'PhoneCallSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'companyCustomerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchBasic'
          }, {
            name: 'participantJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'ResourceAllocation',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'requestedby',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.ResourceAllocationApprovalStatus'
          }, {
            name: 'nextApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'allocationResource',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'project',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'notes'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'allocationAmount',
            typeInfo: 'Double'
          }, {
            name: 'allocationUnit',
            typeInfo: 'com_netsuite_webservices_activities_scheduling_2019_2_types.ResourceAllocationAllocationUnit'
          }, {
            name: 'numberHours',
            typeInfo: 'Double'
          }, {
            name: 'percentOfTime',
            typeInfo: 'Double'
          }, {
            name: 'allocationType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTaskTimeItemList',
        propertyInfos: [{
            name: 'timeItem',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ProjectTaskSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'predecessorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchBasic'
          }, {
            name: 'projectTaskAssignmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskAssignmentSearchBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchBasic'
          }, {
            name: 'successorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }],
    elementInfos: [{
        typeInfo: '.CalendarEventSearch',
        elementName: 'calendarEventSearch'
      }, {
        typeInfo: '.ResourceAllocation',
        elementName: 'resourceAllocation'
      }, {
        typeInfo: '.CalendarEvent',
        elementName: 'CalendarEvent'
      }, {
        typeInfo: '.ProjectTaskSearch',
        elementName: 'projectTaskSearch'
      }, {
        typeInfo: '.PhoneCall',
        elementName: 'PhoneCall'
      }, {
        typeInfo: '.PhoneCallSearch',
        elementName: 'phoneCallSearch'
      }, {
        typeInfo: '.Task',
        elementName: 'Task'
      }, {
        typeInfo: '.TaskSearch',
        elementName: 'taskSearch'
      }, {
        typeInfo: '.ResourceAllocationSearch',
        elementName: 'resourceAllocationSearch'
      }, {
        typeInfo: '.ProjectTask',
        elementName: 'projectTask'
      }]
  };
  return {
    com_netsuite_webservices_activities_scheduling_2019_2: com_netsuite_webservices_activities_scheduling_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_activities_scheduling_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_activities_scheduling_2019_2_Module = com_netsuite_webservices_activities_scheduling_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_activities_scheduling_2019_2 = com_netsuite_webservices_activities_scheduling_2019_2_Module.com_netsuite_webservices_activities_scheduling_2019_2;
  }
  else {
    var com_netsuite_webservices_activities_scheduling_2019_2 = com_netsuite_webservices_activities_scheduling_2019_2_Module.com_netsuite_webservices_activities_scheduling_2019_2;
  }
}