var com_netsuite_webservices_transactions_inventory_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_transactions_inventory_2019_2 = {
    name: 'com_netsuite_webservices_transactions_inventory_2019_2',
    defaultElementNamespaceURI: 'urn:inventory_2019_2.transactions.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_transactions_inventory_2019_2_types', 'com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_platform_common_2019_2_types'],
    typeInfos: [{
        localName: 'WorkOrderItem',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'operationSequenceNumber',
            typeInfo: 'Long'
          }, {
            name: 'componentYield',
            typeInfo: 'Double'
          }, {
            name: 'bomQuantity',
            typeInfo: 'Double'
          }, {
            name: 'quantityCommitted',
            typeInfo: 'Double'
          }, {
            name: 'quantityBackOrdered',
            typeInfo: 'Double'
          }, {
            name: 'quantityAvailable',
            typeInfo: 'Double'
          }, {
            name: 'averageCost',
            typeInfo: 'Double'
          }, {
            name: 'lastPurchasePrice',
            typeInfo: 'Double'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'orderPriority',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'itemSource',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.ItemSource'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'poVendor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'poRate',
            typeInfo: 'Double'
          }, {
            name: 'percentComplete',
            typeInfo: 'Double'
          }, {
            name: 'contribution',
            typeInfo: 'Double'
          }, {
            name: 'description'
          }, {
            name: 'commitInventory',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.WorkOrderItemItemCommitInventory'
          }, {
            name: 'plannedIssueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'TransferOrderItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.TransferOrderItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InventoryAdjustmentInventory',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'description'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'currentValue',
            typeInfo: 'Double'
          }, {
            name: 'adjustQtyBy',
            typeInfo: 'Double'
          }, {
            name: 'binNumbers'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'newQuantity',
            typeInfo: 'Double'
          }, {
            name: 'unitCost',
            typeInfo: 'Double'
          }, {
            name: 'foreignCurrencyUnitCost',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'currency'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'BinTransfer',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'memo'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryList',
            typeInfo: '.BinTransferInventoryList'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrderIssueComponentList',
        propertyInfos: [{
            name: 'workOrderIssueComponent',
            minOccurs: 0,
            collection: true,
            typeInfo: '.WorkOrderIssueComponent'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrderIssue',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'manufacturingRouting',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startOperation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'endOperation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'componentList',
            typeInfo: '.WorkOrderIssueComponentList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BinWorksheetItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.BinWorksheetItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrderCompletionOperationList',
        propertyInfos: [{
            name: 'workOrderCompletionOperation',
            minOccurs: 0,
            collection: true,
            typeInfo: '.WorkOrderCompletionOperation'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InterCompanyTransferOrderItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InterCompanyTransferOrderItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PartnersList',
        propertyInfos: [{
            name: 'partners',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Partners'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrderItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.WorkOrderItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BinWorksheetItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'itemName'
          }, {
            name: 'description'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'itemOnHand'
          }, {
            name: 'itemUnitsLabel'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'itemBins'
          }, {
            name: 'itemBinNumbers'
          }, {
            name: 'itemBinList'
          }, {
            name: 'itemPreferBin'
          }, {
            name: 'itemBlank'
          }]
      }, {
        localName: 'WorkOrderCompletionComponent',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'operationSequenceNumber',
            typeInfo: 'Long'
          }, {
            name: 'quantityPer',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'componentInventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'lineNumber',
            typeInfo: 'Long'
          }]
      }, {
        localName: 'AssemblyBuild',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'buildable',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'billOfMaterials',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'binNumbers'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billOfMaterialsRevision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'componentList',
            typeInfo: '.AssemblyComponentList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TransferOrder',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shippingCost',
            typeInfo: 'Double'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'status'
          }, {
            name: 'shippingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'shipIsResidential',
            typeInfo: 'Boolean'
          }, {
            name: 'shipAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'fob'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'source'
          }, {
            name: 'orderStatus',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.TransferOrderOrderStatus'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'useItemCostAsTransferCost',
            typeInfo: 'Boolean'
          }, {
            name: 'incoterm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'firmed',
            typeInfo: 'Boolean'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transferLocation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'shipDate',
            typeInfo: 'DateTime'
          }, {
            name: 'shipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'trackingNumbers'
          }, {
            name: 'linkedTrackingNumbers'
          }, {
            name: 'shipComplete',
            typeInfo: 'Boolean'
          }, {
            name: 'altShippingCost',
            typeInfo: 'Double'
          }, {
            name: 'shippingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'shippingTax2Rate',
            typeInfo: 'Double'
          }, {
            name: 'handlingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'handlingTax2Rate',
            typeInfo: 'Double'
          }, {
            name: 'shippingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'itemList',
            typeInfo: '.TransferOrderItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InventoryCostRevaluationCostComponent',
        propertyInfos: [{
            name: 'cost',
            typeInfo: 'Double'
          }, {
            name: 'componentItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'costCategory',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'InventoryAdjustment',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'estimatedTotalValue',
            typeInfo: 'Double'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'adjLocation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'inventoryList',
            typeInfo: '.InventoryAdjustmentInventoryList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BinTransferInventoryList',
        propertyInfos: [{
            name: 'inventory',
            minOccurs: 0,
            collection: true,
            typeInfo: '.BinTransferInventory'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InterCompanyTransferOrderItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'quantityAvailable',
            typeInfo: 'Double'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'quantityBackOrdered',
            typeInfo: 'Double'
          }, {
            name: 'quantityCommitted',
            typeInfo: 'Double'
          }, {
            name: 'quantityFulfilled',
            typeInfo: 'Double'
          }, {
            name: 'quantityReceived',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'description'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'commitInventory',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.TransferOrderItemCommitInventory'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lastPurchasePrice',
            typeInfo: 'Double'
          }, {
            name: 'averageCost',
            typeInfo: 'Double'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'WorkOrderIssueComponent',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'operationSequenceNumber',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'componentInventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'lineNumber',
            typeInfo: 'Long'
          }]
      }, {
        localName: 'SalesTeamList',
        propertyInfos: [{
            name: 'salesTeam',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSalesTeam'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AssemblyComponentList',
        propertyInfos: [{
            name: 'component',
            minOccurs: 0,
            collection: true,
            typeInfo: '.AssemblyComponent'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InventoryCostRevaluation',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'inventoryValue',
            typeInfo: 'Double'
          }, {
            name: 'unitCost',
            typeInfo: 'Double'
          }, {
            name: 'costComponentList',
            typeInfo: '.InventoryCostRevaluationCostComponentList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AssemblyUnbuild',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'built',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'billOfMaterials',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billOfMaterialsRevision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'binNumbers'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'componentList',
            typeInfo: '.AssemblyComponentList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AssemblyComponent',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'componentInventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'componentNumbers'
          }, {
            name: 'binNumbers'
          }, {
            name: 'lineNumber',
            typeInfo: 'Long'
          }]
      }, {
        localName: 'InventoryAdjustmentInventoryList',
        propertyInfos: [{
            name: 'inventory',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InventoryAdjustmentInventory'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TransferOrderItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'quantityAvailable',
            typeInfo: 'Double'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'quantityBackOrdered',
            typeInfo: 'Double'
          }, {
            name: 'quantityCommitted',
            typeInfo: 'Double'
          }, {
            name: 'quantityFulfilled',
            typeInfo: 'Double'
          }, {
            name: 'quantityPacked',
            typeInfo: 'Double'
          }, {
            name: 'quantityPicked',
            typeInfo: 'Double'
          }, {
            name: 'quantityReceived',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'description'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'commitInventory',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.TransferOrderItemCommitInventory'
          }, {
            name: 'orderPriority',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lastPurchasePrice',
            typeInfo: 'Double'
          }, {
            name: 'averageCost',
            typeInfo: 'Double'
          }, {
            name: 'expectedShipDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expectedReceiptDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'InventoryCostRevaluationCostComponentList',
        propertyInfos: [{
            name: 'costComponent',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InventoryCostRevaluationCostComponent'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrder',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'manufacturingRouting',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'autoCalculateLag',
            typeInfo: 'Boolean'
          }, {
            name: 'status'
          }, {
            name: 'tranId'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'assemblyItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'expandAssembly',
            typeInfo: 'Boolean'
          }, {
            name: 'isWip',
            typeInfo: 'Boolean'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'billOfMaterials',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'orderStatus',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.WorkOrderOrderStatus'
          }, {
            name: 'firmed',
            typeInfo: 'Boolean'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'itemList',
            typeInfo: '.WorkOrderItemList'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'schedulingMethod',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.WorkOrderSchedulingMethod'
          }, {
            name: 'salesTeamList',
            typeInfo: '.SalesTeamList'
          }, {
            name: 'partnersList',
            typeInfo: '.PartnersList'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'sourceTransactionId'
          }, {
            name: 'sourceTransactionLine',
            typeInfo: 'Long'
          }, {
            name: 'specialOrder',
            typeInfo: 'Boolean'
          }, {
            name: 'buildable',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'built',
            typeInfo: 'Double'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'revision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billOfMaterialsRevision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InventoryTransferInventoryList',
        propertyInfos: [{
            name: 'inventory',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InventoryTransferInventory'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrderCompletion',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'scrapQuantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBackflush',
            typeInfo: 'Boolean'
          }, {
            name: 'orderQuantity',
            typeInfo: 'Double'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startOperation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'endOperation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'completedQuantity',
            typeInfo: 'Double'
          }, {
            name: 'manufacturingRouting',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'componentList',
            typeInfo: '.WorkOrderCompletionComponentList'
          }, {
            name: 'operationList',
            typeInfo: '.WorkOrderCompletionOperationList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InventoryTransfer',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'memo'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transferLocation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryList',
            typeInfo: '.InventoryTransferInventoryList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BinTransferInventory',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'preferredBin'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'itemUnitsLabel'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'fromBins'
          }, {
            name: 'toBins'
          }]
      }, {
        localName: 'WorkOrderCompletionOperation',
        propertyInfos: [{
            name: 'operationSequence',
            typeInfo: 'Long'
          }, {
            name: 'operationName'
          }, {
            name: 'workCenter'
          }, {
            name: 'machineResources',
            typeInfo: 'Double'
          }, {
            name: 'laborResources',
            typeInfo: 'Double'
          }, {
            name: 'inputQuantity',
            typeInfo: 'Double'
          }, {
            name: 'quantityRemaining',
            typeInfo: 'Double'
          }, {
            name: 'predecessorCompletedQuantity',
            typeInfo: 'Double'
          }, {
            name: 'completedQuantity',
            typeInfo: 'Double'
          }, {
            name: 'recordSetup',
            typeInfo: 'Boolean'
          }, {
            name: 'machineSetupTime',
            typeInfo: 'Double'
          }, {
            name: 'laborSetupTime',
            typeInfo: 'Double'
          }, {
            name: 'machineRunTime',
            typeInfo: 'Double'
          }, {
            name: 'laborRunTime',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'WorkOrderCompletionComponentList',
        propertyInfos: [{
            name: 'workOrderCompletionComponent',
            minOccurs: 0,
            collection: true,
            typeInfo: '.WorkOrderCompletionComponent'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BinWorksheet',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'memo'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'itemList',
            typeInfo: '.BinWorksheetItemList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'WorkOrderClose',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'orderQuantity',
            typeInfo: 'Double'
          }, {
            name: 'scrapQuantity',
            typeInfo: 'Double'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'revision',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InterCompanyTransferOrder',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shippingCost',
            typeInfo: 'Double'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'status'
          }, {
            name: 'shippingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'shipIsResidential',
            typeInfo: 'Boolean'
          }, {
            name: 'shipAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'fob'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'source'
          }, {
            name: 'orderStatus',
            typeInfo: 'com_netsuite_webservices_transactions_inventory_2019_2_types.TransferOrderOrderStatus'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'toSubsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'useItemCostAsTransferCost',
            typeInfo: 'Boolean'
          }, {
            name: 'incoterm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transferLocation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'shipDate',
            typeInfo: 'DateTime'
          }, {
            name: 'shipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'trackingNumbers'
          }, {
            name: 'linkedTrackingNumbers'
          }, {
            name: 'shipComplete',
            typeInfo: 'Boolean'
          }, {
            name: 'altShippingCost',
            typeInfo: 'Double'
          }, {
            name: 'shippingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'handlingTax1Rate',
            typeInfo: 'Double'
          }, {
            name: 'shippingTax2Rate',
            typeInfo: 'Double'
          }, {
            name: 'handlingTax2Rate',
            typeInfo: 'Double'
          }, {
            name: 'shippingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'handlingTaxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'itemList',
            typeInfo: '.InterCompanyTransferOrderItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InventoryTransferInventory',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'description'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'adjustQtyBy',
            typeInfo: 'Double'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'fromBinNumbers'
          }, {
            name: 'toBinNumbers'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }],
    elementInfos: [{
        typeInfo: '.WorkOrder',
        elementName: 'workOrder'
      }, {
        typeInfo: '.InventoryCostRevaluation',
        elementName: 'inventoryCostRevaluation'
      }, {
        typeInfo: '.WorkOrderCompletion',
        elementName: 'workOrderCompletion'
      }, {
        typeInfo: '.InventoryAdjustment',
        elementName: 'InventoryAdjustment'
      }, {
        typeInfo: '.WorkOrderClose',
        elementName: 'workOrderClose'
      }, {
        typeInfo: '.AssemblyBuild',
        elementName: 'assemblyBuild'
      }, {
        typeInfo: '.BinTransfer',
        elementName: 'binTransfer'
      }, {
        typeInfo: '.TransferOrder',
        elementName: 'transferOrder'
      }, {
        typeInfo: '.AssemblyUnbuild',
        elementName: 'assemblyUnbuild'
      }, {
        typeInfo: '.WorkOrderIssue',
        elementName: 'workOrderIssue'
      }, {
        typeInfo: '.BinWorksheet',
        elementName: 'binWorksheet'
      }, {
        typeInfo: '.InterCompanyTransferOrder',
        elementName: 'interCompanyTransferOrder'
      }, {
        typeInfo: '.InventoryTransfer',
        elementName: 'inventoryTransfer'
      }]
  };
  return {
    com_netsuite_webservices_transactions_inventory_2019_2: com_netsuite_webservices_transactions_inventory_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_transactions_inventory_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_transactions_inventory_2019_2_Module = com_netsuite_webservices_transactions_inventory_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_transactions_inventory_2019_2 = com_netsuite_webservices_transactions_inventory_2019_2_Module.com_netsuite_webservices_transactions_inventory_2019_2;
  }
  else {
    var com_netsuite_webservices_transactions_inventory_2019_2 = com_netsuite_webservices_transactions_inventory_2019_2_Module.com_netsuite_webservices_transactions_inventory_2019_2;
  }
}