var com_netsuite_webservices_transactions_purchases_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_transactions_purchases_2019_2 = {
    name: 'com_netsuite_webservices_transactions_purchases_2019_2',
    defaultElementNamespaceURI: 'urn:purchases_2019_2.transactions.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_transactions_purchases_2019_2_types', 'com_netsuite_webservices_platform_common_2019_2_types'],
    typeInfos: [{
        localName: 'VendorBillItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vendorName'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'orderDoc',
            typeInfo: 'Long'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'description'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'binNumbers'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'landedCostCategory',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'billVarianceStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.TransactionBillVarianceStatus'
          }, {
            name: 'billreceiptsList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'landedCost',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LandedCost'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'InboundShipmentSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InboundShipmentSearchRowBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchRowBasic'
          }, {
            name: 'itemReceiptJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'purchaseOrderJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'VendorBillInstallment',
        propertyInfos: [{
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'dueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amountDue',
            typeInfo: 'Double'
          }, {
            name: 'seqNum',
            typeInfo: 'Long'
          }, {
            name: 'status'
          }]
      }, {
        localName: 'VendorPaymentCredit',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'creditDate',
            typeInfo: 'DateTime'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'appliedTo'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'PurchaseRequisitionItemList',
        propertyInfos: [{
            name: 'purchaseRequisitionItem',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PurchaseRequisitionItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ItemReceiptExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ItemReceiptExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorCreditApply',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'PurchaseOrderItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PurchaseOrderItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ItemReceiptItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ItemReceiptItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorBillInstallmentList',
        propertyInfos: [{
            name: 'vendorBillInstallment',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorBillInstallment'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorPaymentApply',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'doc',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'job'
          }, {
            name: 'applyDate',
            typeInfo: 'DateTime'
          }, {
            name: 'type'
          }, {
            name: 'refNum'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'due',
            typeInfo: 'Double'
          }, {
            name: 'currency'
          }, {
            name: 'discDate',
            typeInfo: 'DateTime'
          }, {
            name: 'discAmt',
            typeInfo: 'Double'
          }, {
            name: 'disc',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'VendorPayment',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'balance',
            typeInfo: 'Double'
          }, {
            name: 'apAcct',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'address'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'voidJournal',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currencyName'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'toAch',
            typeInfo: 'Boolean'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'printVoucher',
            typeInfo: 'Boolean'
          }, {
            name: 'tranId'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'status'
          }, {
            name: 'transactionNumber'
          }, {
            name: 'applyList',
            typeInfo: '.VendorPaymentApplyList'
          }, {
            name: 'creditList',
            typeInfo: '.VendorPaymentCreditList'
          }, {
            name: 'billPay',
            typeInfo: 'Boolean'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'availableBalance',
            typeInfo: 'Double'
          }, {
            name: 'isInTransitPayment',
            typeInfo: 'Boolean'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'nextApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorCreditExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorCreditExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorReturnAuthorizationExpense',
        propertyInfos: [{
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'VendorReturnAuthorizationItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vendorName'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbersList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'description'
          }, {
            name: 'binNumbers'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isDropShipment',
            typeInfo: 'Boolean'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'InboundShipmentLandedCost',
        propertyInfos: [{
            name: 'landedCostCostCategory',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'landedCostAmount',
            typeInfo: 'Double'
          }, {
            name: 'landedCostCurrency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'landedCostExchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'landedCostEffectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'landedCostAllocationMethod',
            typeInfo: 'com_netsuite_webservices_transactions_purchases_2019_2_types.InboundShipmentLandedCostAllocationMethod'
          }, {
            name: 'landedCostShipmentItemsList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }]
      }, {
        localName: 'ItemReceiptItem',
        propertyInfos: [{
            name: 'itemReceive',
            typeInfo: 'Boolean'
          }, {
            name: 'jobName'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'itemName'
          }, {
            name: 'description'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'onHand',
            typeInfo: 'Double'
          }, {
            name: 'quantityRemaining',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'unitsDisplay'
          }, {
            name: 'unitCostOverride',
            typeInfo: 'Double'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'binNumbers'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }, {
            name: 'rate'
          }, {
            name: 'currency'
          }, {
            name: 'restock',
            typeInfo: 'Boolean'
          }, {
            name: 'billVarianceStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.TransactionBillVarianceStatus'
          }, {
            name: 'isDropShipment',
            typeInfo: 'Boolean'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'landedCost',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LandedCost'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'InboundShipmentLandedCostList',
        propertyInfos: [{
            name: 'inboundShipmentLandedCost',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InboundShipmentLandedCost'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchaseOrderExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PurchaseOrderExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InboundShipmentSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.InboundShipmentSearch'
          }, {
            name: 'columns',
            typeInfo: '.InboundShipmentSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InboundShipmentSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InboundShipmentSearchBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchBasic'
          }, {
            name: 'itemReceiptJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'purchaseOrderJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'InboundShipmentItems',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'purchaseOrder',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipmentItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipmentItemDescription'
          }, {
            name: 'poVendor'
          }, {
            name: 'receivingLocation',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantityReceived',
            typeInfo: 'Double'
          }, {
            name: 'quantityExpected',
            typeInfo: 'Double'
          }, {
            name: 'quantityRemaining',
            typeInfo: 'Double'
          }, {
            name: 'unit',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'poRate',
            typeInfo: 'Double'
          }, {
            name: 'expectedRate',
            typeInfo: 'Double'
          }, {
            name: 'shipmentItemExchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'shipmentItemEffectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'unitLandedCost',
            typeInfo: 'Double'
          }, {
            name: 'totalUnitCost',
            typeInfo: 'Double'
          }, {
            name: 'shipmentItemAmount',
            typeInfo: 'Double'
          }, {
            name: 'poCurrency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'incoterm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'ItemReceipt',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currencyName'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'partner',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'inboundShipment',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'itemFulfillment',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'landedCostMethod',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.LandedCostMethod'
          }, {
            name: 'landedCostPerLine',
            typeInfo: 'Boolean'
          }, {
            name: 'itemList',
            typeInfo: '.ItemReceiptItemList'
          }, {
            name: 'expenseList',
            typeInfo: '.ItemReceiptExpenseList'
          }, {
            name: 'landedCostsList',
            typeInfo: '.PurchLandedCostList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorPaymentCreditList',
        propertyInfos: [{
            name: 'credit',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorPaymentCredit'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchaseOrderItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'quantityOnShipments',
            typeInfo: 'Double'
          }, {
            name: 'vendorName'
          }, {
            name: 'quantityReceived',
            typeInfo: 'Double'
          }, {
            name: 'quantityBilled',
            typeInfo: 'Double'
          }, {
            name: 'quantityAvailable',
            typeInfo: 'Double'
          }, {
            name: 'quantityOnHand',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'description'
          }, {
            name: 'purchaseContract',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'landedCostCategory',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'billVarianceStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.TransactionBillVarianceStatus'
          }, {
            name: 'matchBillToReceipt',
            typeInfo: 'Boolean'
          }, {
            name: 'expectedReceiptDate',
            typeInfo: 'DateTime'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'linkedOrderList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'InboundShipmentItemsList',
        propertyInfos: [{
            name: 'inboundShipmentItems',
            minOccurs: 0,
            collection: true,
            typeInfo: '.InboundShipmentItems'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorReturnAuthorizationExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorReturnAuthorizationExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchaseRequisitionExpense',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'poVendor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'estimatedAmount',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'linkedOrderList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'linkedOrderStatus'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'VendorCreditApplyList',
        propertyInfos: [{
            name: 'apply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorCreditApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorBillExpense',
        propertyInfos: [{
            name: 'orderDoc',
            typeInfo: 'Long'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'projectTask',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'VendorBillExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorBillExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchaseRequisition',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'source'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'currencyName'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'vatRegNum'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'estimatedTotal',
            typeInfo: 'Double'
          }, {
            name: 'status'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'dueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'memo'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'nextApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'itemList',
            typeInfo: '.PurchaseRequisitionItemList'
          }, {
            name: 'expenseList',
            typeInfo: '.PurchaseRequisitionExpenseList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'InboundShipment',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipmentNumber'
          }, {
            name: 'externalDocumentNumber'
          }, {
            name: 'shipmentStatus',
            typeInfo: 'com_netsuite_webservices_transactions_purchases_2019_2_types.InboundShipmentShipmentStatus'
          }, {
            name: 'expectedShippingDate',
            typeInfo: 'DateTime'
          }, {
            name: 'actualShippingDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expectedDeliveryDate',
            typeInfo: 'DateTime'
          }, {
            name: 'actualDeliveryDate',
            typeInfo: 'DateTime'
          }, {
            name: 'shipmentMemo'
          }, {
            name: 'vesselNumber'
          }, {
            name: 'billOfLading'
          }, {
            name: 'landedCostList',
            typeInfo: '.InboundShipmentLandedCostList'
          }, {
            name: 'itemsList',
            typeInfo: '.InboundShipmentItemsList'
          }, {
            name: 'shipmentBaseCurrency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorBill',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'nextApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vatRegNum'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currencyName'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'terms',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'dueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'discountDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'userTotal',
            typeInfo: 'Double'
          }, {
            name: 'discountAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'paymentHold',
            typeInfo: 'Boolean'
          }, {
            name: 'memo'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'creditLimit',
            typeInfo: 'Double'
          }, {
            name: 'availableVendorCredit',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'status'
          }, {
            name: 'landedCostMethod',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.LandedCostMethod'
          }, {
            name: 'landedCostPerLine',
            typeInfo: 'Boolean'
          }, {
            name: 'transactionNumber'
          }, {
            name: 'expenseList',
            typeInfo: '.VendorBillExpenseList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'itemList',
            typeInfo: '.VendorBillItemList'
          }, {
            name: 'installmentList',
            typeInfo: '.VendorBillInstallmentList'
          }, {
            name: 'landedCostsList',
            typeInfo: '.PurchLandedCostList'
          }, {
            name: 'purchaseOrderList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'overrideInstallments',
            typeInfo: 'Boolean'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ItemReceiptExpense',
        propertyInfos: [{
            name: 'markReceived',
            typeInfo: 'Boolean'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'account'
          }, {
            name: 'memo'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'VendorBillItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorBillItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorCreditExpense',
        propertyInfos: [{
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PurchaseOrder',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'purchaseContract',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vatRegNum'
          }, {
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'supervisorApproval',
            typeInfo: 'Boolean'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'terms',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'dueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'otherRefNum'
          }, {
            name: 'availableVendorCredit',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'nextApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'source'
          }, {
            name: 'currencyName'
          }, {
            name: 'toBePrinted',
            typeInfo: 'Boolean'
          }, {
            name: 'toBeEmailed',
            typeInfo: 'Boolean'
          }, {
            name: 'email'
          }, {
            name: 'toBeFaxed',
            typeInfo: 'Boolean'
          }, {
            name: 'fax'
          }, {
            name: 'message'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'shipTo',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subTotal',
            typeInfo: 'Double'
          }, {
            name: 'taxTotal',
            typeInfo: 'Double'
          }, {
            name: 'tax2Total',
            typeInfo: 'Double'
          }, {
            name: 'shippingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'shipIsResidential',
            typeInfo: 'Boolean'
          }, {
            name: 'shipAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'fob'
          }, {
            name: 'shipDate',
            typeInfo: 'DateTime'
          }, {
            name: 'shipMethod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'incoterm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'trackingNumbers'
          }, {
            name: 'linkedTrackingNumbers'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'intercoTransaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'intercoStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.IntercoStatus'
          }, {
            name: 'status'
          }, {
            name: 'orderStatus',
            typeInfo: 'com_netsuite_webservices_transactions_purchases_2019_2_types.PurchaseOrderOrderStatus'
          }, {
            name: 'itemList',
            typeInfo: '.PurchaseOrderItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'expenseList',
            typeInfo: '.PurchaseOrderExpenseList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchaseRequisitionItem',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vendorName'
          }, {
            name: 'poVendor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'serialNumbers'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'description'
          }, {
            name: 'estimatedRate',
            typeInfo: 'Double'
          }, {
            name: 'estimatedAmount',
            typeInfo: 'Double'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'linkedOrderList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'linkedOrderStatus'
          }, {
            name: 'expectedReceiptDate',
            typeInfo: 'DateTime'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'expandItemGroup',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'PurchaseOrderExpense',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'linkedOrderList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isClosed',
            typeInfo: 'Boolean'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'VendorCredit',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'unApplied',
            typeInfo: 'Double'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'autoApply',
            typeInfo: 'Boolean'
          }, {
            name: 'applied',
            typeInfo: 'Double'
          }, {
            name: 'transactionNumber'
          }, {
            name: 'tranId'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'userTotal',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currencyName'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'userTaxTotal',
            typeInfo: 'Double'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'expenseList',
            typeInfo: '.VendorCreditExpenseList'
          }, {
            name: 'itemList',
            typeInfo: '.VendorCreditItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'applyList',
            typeInfo: '.VendorCreditApplyList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorCreditItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorCreditItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorPaymentApplyList',
        propertyInfos: [{
            name: 'apply',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorPaymentApply'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorReturnAuthorizationItemList',
        propertyInfos: [{
            name: 'item',
            minOccurs: 0,
            collection: true,
            typeInfo: '.VendorReturnAuthorizationItem'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorReturnAuthorization',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRegOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'taxDetailsOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'createdFrom',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'orderStatus',
            typeInfo: 'com_netsuite_webservices_transactions_purchases_2019_2_types.VendorReturnAuthorizationOrderStatus'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'userTotal',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currencyName'
          }, {
            name: 'billingAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'billAddressList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'entityTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'userTaxTotal',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'intercoTransaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'intercoStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.IntercoStatus'
          }, {
            name: 'expenseList',
            typeInfo: '.VendorReturnAuthorizationExpenseList'
          }, {
            name: 'itemList',
            typeInfo: '.VendorReturnAuthorizationItemList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchaseRequisitionExpenseList',
        propertyInfos: [{
            name: 'purchaseRequisitionExpense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PurchaseRequisitionExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PurchLandedCostList',
        propertyInfos: [{
            name: 'landedCost',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LandedCostSummary'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'VendorCreditItem',
        propertyInfos: [{
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'vendorName'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'orderLine',
            typeInfo: 'Long'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'units',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'inventoryDetail',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.InventoryDetail'
          }, {
            name: 'serialNumbersList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRefList'
          }, {
            name: 'description'
          }, {
            name: 'rate'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'binNumbers'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'options',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'amortizationSched',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amortizStartDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationEndDate',
            typeInfo: 'DateTime'
          }, {
            name: 'amortizationResidual'
          }, {
            name: 'taxAmount',
            typeInfo: 'Double'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }],
    elementInfos: [{
        typeInfo: '.VendorBill',
        elementName: 'VendorBill'
      }, {
        typeInfo: '.InboundShipment',
        elementName: 'inboundShipment'
      }, {
        typeInfo: '.PurchaseRequisition',
        elementName: 'purchaseRequisition'
      }, {
        typeInfo: '.PurchaseOrder',
        elementName: 'PurchaseOrder'
      }, {
        typeInfo: '.InboundShipmentSearch',
        elementName: 'inboundShipmentSearch'
      }, {
        typeInfo: '.VendorPayment',
        elementName: 'vendorPayment'
      }, {
        typeInfo: '.VendorReturnAuthorization',
        elementName: 'vendorReturnAuthorization'
      }, {
        typeInfo: '.VendorCredit',
        elementName: 'vendorCredit'
      }, {
        typeInfo: '.ItemReceipt',
        elementName: 'ItemReceipt'
      }]
  };
  return {
    com_netsuite_webservices_transactions_purchases_2019_2: com_netsuite_webservices_transactions_purchases_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_transactions_purchases_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_transactions_purchases_2019_2_Module = com_netsuite_webservices_transactions_purchases_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_transactions_purchases_2019_2 = com_netsuite_webservices_transactions_purchases_2019_2_Module.com_netsuite_webservices_transactions_purchases_2019_2;
  }
  else {
    var com_netsuite_webservices_transactions_purchases_2019_2 = com_netsuite_webservices_transactions_purchases_2019_2_Module.com_netsuite_webservices_transactions_purchases_2019_2;
  }
}