var com_netsuite_webservices_lists_employees_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_lists_employees_2019_2 = {
    name: 'com_netsuite_webservices_lists_employees_2019_2',
    defaultElementNamespaceURI: 'urn:employees_2019_2.lists.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_platform_common_2019_2_types', 'com_netsuite_webservices_lists_employees_2019_2_types'],
    typeInfos: [{
        localName: 'EmployeeRolesList',
        propertyInfos: [{
            name: 'roles',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeRoles'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Employee',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'template',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entityId'
          }, {
            name: 'salutation'
          }, {
            name: 'firstName'
          }, {
            name: 'middleName'
          }, {
            name: 'lastName'
          }, {
            name: 'altName'
          }, {
            name: 'phone'
          }, {
            name: 'fax'
          }, {
            name: 'email'
          }, {
            name: 'defaultAddress'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'phoneticName'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'dateCreated',
            typeInfo: 'DateTime'
          }, {
            name: 'initials'
          }, {
            name: 'officePhone'
          }, {
            name: 'homePhone'
          }, {
            name: 'mobilePhone'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billingClass',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'accountNumber'
          }, {
            name: 'compensationCurrency',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeCompensationCurrency'
          }, {
            name: 'baseWageType',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeBaseWageType'
          }, {
            name: 'baseWage',
            typeInfo: 'Double'
          }, {
            name: 'comments'
          }, {
            name: 'globalSubscriptionStatus',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2_types.GlobalSubscriptionStatus'
          }, {
            name: 'image',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'payFrequency',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeePayFrequency'
          }, {
            name: 'lastPaidDate',
            typeInfo: 'DateTime'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'useTimeData',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeUseTimeData'
          }, {
            name: 'usePerquest',
            typeInfo: 'Boolean'
          }, {
            name: 'workplace',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'adpId'
          }, {
            name: 'directDeposit',
            typeInfo: 'Boolean'
          }, {
            name: 'expenseLimit',
            typeInfo: 'Double'
          }, {
            name: 'purchaseOrderLimit',
            typeInfo: 'Double'
          }, {
            name: 'purchaseOrderApprovalLimit',
            typeInfo: 'Double'
          }, {
            name: 'socialSecurityNumber'
          }, {
            name: 'supervisor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approver',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approvalLimit',
            typeInfo: 'Double'
          }, {
            name: 'timeApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'employeeType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isSalesRep',
            typeInfo: 'Boolean'
          }, {
            name: 'salesRole',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isSupportRep',
            typeInfo: 'Boolean'
          }, {
            name: 'isJobResource',
            typeInfo: 'Boolean'
          }, {
            name: 'laborCost',
            typeInfo: 'Double'
          }, {
            name: 'birthDate',
            typeInfo: 'DateTime'
          }, {
            name: 'hireDate',
            typeInfo: 'DateTime'
          }, {
            name: 'releaseDate',
            typeInfo: 'DateTime'
          }, {
            name: 'terminationDetails'
          }, {
            name: 'terminationReason',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'terminationRegretted',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeTerminationRegretted'
          }, {
            name: 'terminationCategory',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeTerminationCategory'
          }, {
            name: 'timeOffPlan',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'lastReviewDate',
            typeInfo: 'DateTime'
          }, {
            name: 'nextReviewDate',
            typeInfo: 'DateTime'
          }, {
            name: 'title'
          }, {
            name: 'employeeStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'jobDescription'
          }, {
            name: 'workAssignment',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeWorkAssignment'
          }, {
            name: 'job',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'maritalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'ethnicity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'gender',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.Gender'
          }, {
            name: 'purchaseOrderApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'workCalendar',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'giveAccess',
            typeInfo: 'Boolean'
          }, {
            name: 'defaultExpenseReportCurrency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'concurrentWebServicesUser',
            typeInfo: 'Boolean'
          }, {
            name: 'sendEmail',
            typeInfo: 'Boolean'
          }, {
            name: 'hasOfflineAccess',
            typeInfo: 'Boolean'
          }, {
            name: 'password'
          }, {
            name: 'password2'
          }, {
            name: 'requirePwdChange',
            typeInfo: 'Boolean'
          }, {
            name: 'inheritIPRules',
            typeInfo: 'Boolean'
          }, {
            name: 'ipAddressRule',
            elementName: 'IPAddressRule'
          }, {
            name: 'startDateTimeOffCalc',
            typeInfo: 'DateTime'
          }, {
            name: 'commissionPaymentPreference',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeCommissionPaymentPreference'
          }, {
            name: 'billPay',
            typeInfo: 'Boolean'
          }, {
            name: 'defaultAcctCorpCardExp',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'eligibleForCommission',
            typeInfo: 'Boolean'
          }, {
            name: 'subscriptionsList',
            typeInfo: '.EmployeeSubscriptionsList'
          }, {
            name: 'ratesList',
            typeInfo: '.EmployeeRatesList'
          }, {
            name: 'addressbookList',
            typeInfo: '.EmployeeAddressbookList'
          }, {
            name: 'rolesList',
            typeInfo: '.EmployeeRolesList'
          }, {
            name: 'hrEducationList',
            typeInfo: '.EmployeeHrEducationList'
          }, {
            name: 'accruedTimeList',
            typeInfo: '.EmployeeAccruedTimeList'
          }, {
            name: 'directDepositList',
            typeInfo: '.EmployeeDirectDepositList'
          }, {
            name: 'currencyList',
            typeInfo: '.EmployeeCurrencyList'
          }, {
            name: 'companyContributionList',
            typeInfo: '.EmployeeCompanyContributionList'
          }, {
            name: 'earningList',
            typeInfo: '.EmployeeEarningList'
          }, {
            name: 'emergencyContactList',
            typeInfo: '.EmployeeEmergencyContactList'
          }, {
            name: 'hcmPositionList',
            typeInfo: '.EmployeeHcmPositionList'
          }, {
            name: 'deductionList',
            typeInfo: '.EmployeeDeductionList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeDirectDeposit',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'netAccount',
            typeInfo: 'Boolean'
          }, {
            name: 'savingsAccount',
            typeInfo: 'Boolean'
          }, {
            name: 'accountPrenoted',
            typeInfo: 'Boolean'
          }, {
            name: 'accountStatus',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeDirectDepositAccountStatus'
          }, {
            name: 'bankName'
          }, {
            name: 'bankId'
          }, {
            name: 'bankNumber'
          }, {
            name: 'bankRoutingNumber'
          }, {
            name: 'bankAccountNumber'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'inactive',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'EmployeeSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'campaignResponseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchRowBasic'
          }, {
            name: 'chargeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ChargeSearchRowBasic'
          }, {
            name: 'departmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.DepartmentSearchRowBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchRowBasic'
          }, {
            name: 'hcmJobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.HcmJobSearchRowBasic'
          }, {
            name: 'locationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LocationSearchRowBasic'
          }, {
            name: 'managedJobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'messagesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchRowBasic'
          }, {
            name: 'messagesFromJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchRowBasic'
          }, {
            name: 'messagesToJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchRowBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchRowBasic'
          }, {
            name: 'subsidiaryJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SubsidiarySearchRowBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'EmployeeRates',
        propertyInfos: [{
            name: 'entityCurrency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'EmployeeEarning',
        propertyInfos: [{
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'payRate'
          }, {
            name: 'primaryEarning',
            typeInfo: 'Boolean'
          }, {
            name: 'defaultHours',
            typeInfo: 'Double'
          }, {
            name: 'inactive',
            typeInfo: 'Boolean'
          }, {
            name: 'defaultEarning',
            typeInfo: 'Boolean'
          }, {
            name: 'effectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'PayrollItemSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.PayrollItemSearch'
          }, {
            name: 'columns',
            typeInfo: '.PayrollItemSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeCompanyContribution',
        propertyInfos: [{
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'limit',
            typeInfo: 'Double'
          }, {
            name: 'inactive',
            typeInfo: 'Boolean'
          }, {
            name: 'effectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'EmployeeSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.EmployeeSearch'
          }, {
            name: 'columns',
            typeInfo: '.EmployeeSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeRoles',
        propertyInfos: [{
            name: 'selectedRole',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'EmployeeHrEducationList',
        propertyInfos: [{
            name: 'employeeHrEducation',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeHrEducation'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'campaignResponseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchBasic'
          }, {
            name: 'chargeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ChargeSearchBasic'
          }, {
            name: 'departmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.DepartmentSearchBasic'
          }, {
            name: 'fileJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchBasic'
          }, {
            name: 'hcmJobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.HcmJobSearchBasic'
          }, {
            name: 'locationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LocationSearchBasic'
          }, {
            name: 'managedJobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'messagesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchBasic'
          }, {
            name: 'messagesFromJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchBasic'
          }, {
            name: 'messagesToJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchBasic'
          }, {
            name: 'subsidiaryJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SubsidiarySearchBasic'
          }, {
            name: 'timeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'userNotesJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'EmployeeAddressbookList',
        propertyInfos: [{
            name: 'addressbook',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeAddressbook'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PayrollItemSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PayrollItemSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'EmployeeAccruedTime',
        propertyInfos: [{
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'accruedHours',
            typeInfo: 'Double'
          }, {
            name: 'accrualRate',
            typeInfo: 'Double'
          }, {
            name: 'monetaryRate',
            typeInfo: 'Double'
          }, {
            name: 'resetAccruedHoursAtYearEnd',
            typeInfo: 'Boolean'
          }, {
            name: 'accrualMethod',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.EmployeeAccruedTimeAccrualMethod'
          }, {
            name: 'maximumAccruedHours',
            typeInfo: 'Double'
          }, {
            name: 'inactive',
            typeInfo: 'Boolean'
          }, {
            name: 'effectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'EmployeeEmergencyContact',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'contact'
          }, {
            name: 'relationship'
          }, {
            name: 'address'
          }, {
            name: 'phone'
          }]
      }, {
        localName: 'HcmJob',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'title'
          }, {
            name: 'isInactive',
            typeInfo: 'Boolean'
          }, {
            name: 'employmentCategory',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'jobId'
          }, {
            name: 'description'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeCompanyContributionList',
        propertyInfos: [{
            name: 'employeeCompanyContribution',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeCompanyContribution'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeDirectDepositList',
        propertyInfos: [{
            name: 'employeeDirectDeposit',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeDirectDeposit'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeHcmPosition',
        propertyInfos: [{
            name: 'position',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'primaryPosition',
            typeInfo: 'Boolean'
          }, {
            name: 'positionId'
          }, {
            name: 'positionAllocation',
            typeInfo: 'Double'
          }, {
            name: 'fullTimeEquivalent',
            typeInfo: 'Double'
          }, {
            name: 'employmentCategory',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'reportsTo',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'EmployeeDeduction',
        propertyInfos: [{
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate'
          }, {
            name: 'limit',
            typeInfo: 'Double'
          }, {
            name: 'inactive',
            typeInfo: 'Boolean'
          }, {
            name: 'effectiveDate',
            typeInfo: 'DateTime'
          }, {
            name: 'expirationDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'EmployeeSubscriptions',
        propertyInfos: [{
            name: 'subscribed'
          }, {
            name: 'subscription'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'EmployeeSubscriptionsList',
        propertyInfos: [{
            name: 'subscriptions',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeSubscriptions'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeHrEducation',
        propertyInfos: [{
            name: 'education',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'degree'
          }, {
            name: 'degreeDate',
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'HcmJobSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.HcmJobSearch'
          }, {
            name: 'columns',
            typeInfo: '.HcmJobSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeCurrency',
        propertyInfos: [{
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }]
      }, {
        localName: 'EmployeeRatesList',
        propertyInfos: [{
            name: 'employeeRates',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeRates'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PayrollItem',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'itemType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'name'
          }, {
            name: 'vendor',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'expenseAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'liabilityAccount',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'employeePaid',
            typeInfo: 'Boolean'
          }, {
            name: 'accountCategory',
            typeInfo: 'com_netsuite_webservices_lists_employees_2019_2_types.PayrollItemAccountCategory'
          }, {
            name: 'inactive',
            typeInfo: 'Boolean'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'HcmJobSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.HcmJobSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'EmployeeAccruedTimeList',
        propertyInfos: [{
            name: 'employeeAccruedTime',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeAccruedTime'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeDeductionList',
        propertyInfos: [{
            name: 'employeeDeduction',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeDeduction'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PayrollItemSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PayrollItemSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'EmployeeAddressbook',
        propertyInfos: [{
            name: 'defaultShipping',
            typeInfo: 'Boolean'
          }, {
            name: 'defaultBilling',
            typeInfo: 'Boolean'
          }, {
            name: 'label'
          }, {
            name: 'addressbookAddress',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.Address'
          }, {
            name: 'internalId'
          }]
      }, {
        localName: 'EmployeeCurrencyList',
        propertyInfos: [{
            name: 'employeeCurrency',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeCurrency'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeEarningList',
        propertyInfos: [{
            name: 'employeeEarning',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeEarning'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'HcmJobSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.HcmJobSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'EmployeeEmergencyContactList',
        propertyInfos: [{
            name: 'employeeEmergencyContact',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeEmergencyContact'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EmployeeHcmPositionList',
        propertyInfos: [{
            name: 'employeeHcmPosition',
            minOccurs: 0,
            collection: true,
            typeInfo: '.EmployeeHcmPosition'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }],
    elementInfos: [{
        typeInfo: '.Employee',
        elementName: 'Employee'
      }, {
        typeInfo: '.HcmJob',
        elementName: 'hcmJob'
      }, {
        typeInfo: '.PayrollItemSearch',
        elementName: 'payrollItemSearch'
      }, {
        typeInfo: '.EmployeeSearch',
        elementName: 'employeeSearch'
      }, {
        typeInfo: '.PayrollItem',
        elementName: 'payrollItem'
      }, {
        typeInfo: '.HcmJobSearch',
        elementName: 'hcmJobSearch'
      }]
  };
  return {
    com_netsuite_webservices_lists_employees_2019_2: com_netsuite_webservices_lists_employees_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_lists_employees_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_lists_employees_2019_2_Module = com_netsuite_webservices_lists_employees_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_lists_employees_2019_2 = com_netsuite_webservices_lists_employees_2019_2_Module.com_netsuite_webservices_lists_employees_2019_2;
  }
  else {
    var com_netsuite_webservices_lists_employees_2019_2 = com_netsuite_webservices_lists_employees_2019_2_Module.com_netsuite_webservices_lists_employees_2019_2;
  }
}