var com_netsuite_webservices_general_communication_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_general_communication_2019_2 = {
    name: 'com_netsuite_webservices_general_communication_2019_2',
    defaultElementNamespaceURI: 'urn:communication_2019_2.general.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_general_communication_2019_2_types', 'com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_documents_filecabinet_2019_2', 'com_netsuite_webservices_platform_common_2019_2'],
    typeInfos: [{
        localName: 'NoteSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.NoteSearch'
          }, {
            name: 'columns',
            typeInfo: '.NoteSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'MessageMediaItemList',
        propertyInfos: [{
            name: 'mediaItem',
            required: true,
            collection: true,
            typeInfo: 'com_netsuite_webservices_documents_filecabinet_2019_2.File'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'NoteSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchBasic'
          }, {
            name: 'authorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'callJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchBasic'
          }, {
            name: 'campaignJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'entityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'eventJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchBasic'
          }, {
            name: 'issueJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.IssueSearchBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchBasic'
          }, {
            name: 'partnerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PartnerSearchBasic'
          }, {
            name: 'solutionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SolutionSearchBasic'
          }, {
            name: 'taskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'MessageSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchRowBasic'
          }, {
            name: 'attachmentsJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchRowBasic'
          }, {
            name: 'authorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'campaignJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchRowBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'entityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchRowBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchRowBasic'
          }, {
            name: 'partnerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PartnerSearchRowBasic'
          }, {
            name: 'recipientJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchRowBasic'
          }]
      }, {
        localName: 'Note',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'title'
          }, {
            name: 'noteType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'direction',
            typeInfo: 'com_netsuite_webservices_general_communication_2019_2_types.NoteDirection'
          }, {
            name: 'noteDate',
            typeInfo: 'DateTime'
          }, {
            name: 'note'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'activity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'author',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'folder',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'media',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'record',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'recordType',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'topic',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'transaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'MessageSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.MessageSearchBasic'
          }, {
            name: 'attachmentsJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.FileSearchBasic'
          }, {
            name: 'authorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'campaignJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'entityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchBasic'
          }, {
            name: 'partnerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PartnerSearchBasic'
          }, {
            name: 'recipientJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchBasic'
          }]
      }, {
        localName: 'Message',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'author',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'authorEmail'
          }, {
            name: 'recipient',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'recipientEmail'
          }, {
            name: 'cc'
          }, {
            name: 'bcc'
          }, {
            name: 'messageDate',
            typeInfo: 'DateTime'
          }, {
            name: 'recordName'
          }, {
            name: 'recordTypeName'
          }, {
            name: 'subject'
          }, {
            name: 'message'
          }, {
            name: 'emailed',
            typeInfo: 'Boolean'
          }, {
            name: 'activity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'compressAttachments',
            typeInfo: 'Boolean'
          }, {
            name: 'incoming',
            typeInfo: 'Boolean'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'transaction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'mediaItemList',
            typeInfo: '.MessageMediaItemList'
          }, {
            name: 'dateTime'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'MessageSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.MessageSearch'
          }, {
            name: 'columns',
            typeInfo: '.MessageSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'NoteSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.NoteSearchRowBasic'
          }, {
            name: 'authorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'callJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchRowBasic'
          }, {
            name: 'campaignJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CampaignSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'contactJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ContactSearchRowBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'entityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EntitySearchRowBasic'
          }, {
            name: 'eventJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchRowBasic'
          }, {
            name: 'issueJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.IssueSearchRowBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchRowBasic'
          }, {
            name: 'opportunityJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OpportunitySearchRowBasic'
          }, {
            name: 'originatingLeadJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.OriginatingLeadSearchRowBasic'
          }, {
            name: 'partnerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PartnerSearchRowBasic'
          }, {
            name: 'solutionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SolutionSearchRowBasic'
          }, {
            name: 'taskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchRowBasic'
          }, {
            name: 'transactionJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TransactionSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }],
    elementInfos: [{
        typeInfo: '.Message',
        elementName: 'Message'
      }, {
        typeInfo: '.Note',
        elementName: 'Note'
      }, {
        typeInfo: '.MessageSearch',
        elementName: 'messageSearch'
      }, {
        typeInfo: '.NoteSearch',
        elementName: 'noteSearch'
      }]
  };
  return {
    com_netsuite_webservices_general_communication_2019_2: com_netsuite_webservices_general_communication_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_general_communication_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_general_communication_2019_2_Module = com_netsuite_webservices_general_communication_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_general_communication_2019_2 = com_netsuite_webservices_general_communication_2019_2_Module.com_netsuite_webservices_general_communication_2019_2;
  }
  else {
    var com_netsuite_webservices_general_communication_2019_2 = com_netsuite_webservices_general_communication_2019_2_Module.com_netsuite_webservices_general_communication_2019_2;
  }
}