var com_netsuite_webservices_transactions_employees_2019_2_Module_Factory = function () {
  var com_netsuite_webservices_transactions_employees_2019_2 = {
    name: 'com_netsuite_webservices_transactions_employees_2019_2',
    defaultElementNamespaceURI: 'urn:employees_2019_2.transactions.webservices.netsuite.com',
    dependencies: ['com_netsuite_webservices_platform_core_2019_2', 'com_netsuite_webservices_platform_common_2019_2', 'com_netsuite_webservices_transactions_employees_2019_2_types'],
    typeInfos: [{
        localName: 'PaycheckJournalCompanyContribution',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PaycheckSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PaycheckSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'payrollItemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PayrollItemSearchRowBasic'
          }]
      }, {
        localName: 'TimeBill',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'caseTaskEvent',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paidExternally',
            typeInfo: 'Boolean'
          }, {
            name: 'workplace',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'hours',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'price',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'timeType',
            typeInfo: 'com_netsuite_webservices_transactions_employees_2019_2_types.TimeBillTimeType'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }, {
            name: 'overrideRate',
            typeInfo: 'Boolean'
          }, {
            name: 'temporaryLocalJurisdiction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'temporaryStateJurisdiction',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'rejectionNote'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'supervisorApproval',
            typeInfo: 'Boolean'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'timeSheet',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'status'
          }, {
            name: 'timeModified',
            typeInfo: 'Boolean'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckJournalDeductionList',
        propertyInfos: [{
            name: 'paycheckJournalDeduction',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckJournalDeduction'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeEntrySearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeEntrySearchBasic'
          }, {
            name: 'callJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'classJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ClassificationSearchBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'departmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.DepartmentSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'eventJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'locationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LocationSearchBasic'
          }, {
            name: 'projectTaskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchBasic'
          }, {
            name: 'projectTaskAssignmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskAssignmentSearchBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchBasic'
          }, {
            name: 'taskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchBasic'
          }, {
            name: 'timeSheetJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeSheetSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'PaycheckJournalEarning',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'hours',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'ExpenseReport',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'status'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'expenseReportCurrency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'expenseReportExchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'taxPointDate',
            typeInfo: 'DateTime'
          }, {
            name: 'tranId'
          }, {
            name: 'acctCorpCardExp',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'dueDate',
            typeInfo: 'DateTime'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'total',
            typeInfo: 'Double'
          }, {
            name: 'nextApprover',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'advance',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'complete',
            typeInfo: 'Boolean'
          }, {
            name: 'supervisorApproval',
            typeInfo: 'Boolean'
          }, {
            name: 'accountingApproval',
            typeInfo: 'Boolean'
          }, {
            name: 'useMultiCurrency',
            typeInfo: 'Boolean'
          }, {
            name: 'tax2Amt',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'expenseList',
            typeInfo: '.ExpenseReportExpenseList'
          }, {
            name: 'accountingBookDetailList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.AccountingBookDetailList'
          }, {
            name: 'taxDetailsList',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaxDetailsList'
          }, {
            name: 'nexus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiaryTaxRegNum',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayContribList',
        propertyInfos: [{
            name: 'paycheckPayContrib',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayContrib'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayExpList',
        propertyInfos: [{
            name: 'paycheckPayExp',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayExp'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayDisburse',
        propertyInfos: [{
            name: 'method'
          }, {
            name: 'bankName'
          }, {
            name: 'bankAccountDecrypt'
          }, {
            name: 'statusName'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'TimeSheet',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'startDate',
            typeInfo: 'DateTime'
          }, {
            name: 'endDate',
            typeInfo: 'DateTime'
          }, {
            name: 'totalHours',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'timeGridList',
            typeInfo: '.TimeSheetTimeGridList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckJournalEmployeeTaxList',
        propertyInfos: [{
            name: 'paycheckJournalEmployeeTax',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckJournalEmployeeTax'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayTime',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'payItem',
            typeInfo: 'Long'
          }, {
            name: 'payItemName'
          }, {
            name: 'ddate',
            typeInfo: 'DateTime'
          }, {
            name: 'custJob'
          }, {
            name: 'serviceItem'
          }, {
            name: 'count',
            typeInfo: 'Double'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'PaycheckPayDeductList',
        propertyInfos: [{
            name: 'paycheckPayDeduct',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayDeduct'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PaycheckSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'payrollItemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PayrollItemSearchBasic'
          }]
      }, {
        localName: 'TimeBillSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'callJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchBasic'
          }, {
            name: 'chargeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ChargeSearchBasic'
          }, {
            name: 'classJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ClassificationSearchBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchBasic'
          }, {
            name: 'departmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.DepartmentSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'eventJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchBasic'
          }, {
            name: 'locationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LocationSearchBasic'
          }, {
            name: 'projectTaskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchBasic'
          }, {
            name: 'projectTaskAssignmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskAssignmentSearchBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchBasic'
          }, {
            name: 'taskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchBasic'
          }, {
            name: 'timeSheetJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeSheetSearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'PaycheckJournal',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customForm',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'employee',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'companyContributionList',
            typeInfo: '.PaycheckJournalCompanyContributionList'
          }, {
            name: 'deductionList',
            typeInfo: '.PaycheckJournalDeductionList'
          }, {
            name: 'employeeTaxList',
            typeInfo: '.PaycheckJournalEmployeeTaxList'
          }, {
            name: 'companyTaxList',
            typeInfo: '.PaycheckJournalCompanyTaxList'
          }, {
            name: 'earningList',
            typeInfo: '.PaycheckJournalEarningList'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckJournalEmployeeTax',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PaycheckPayEarn',
        propertyInfos: [{
            name: 'payItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'count',
            typeInfo: 'Double'
          }, {
            name: 'rate'
          }, {
            name: 'serviceItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'grossAmount',
            typeInfo: 'Double'
          }, {
            name: 'manualEntry',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'PaycheckPayPto',
        propertyInfos: [{
            name: 'payItem',
            typeInfo: 'Long'
          }, {
            name: 'payItemName'
          }, {
            name: 'hoursAccrued',
            typeInfo: 'Double'
          }, {
            name: 'hoursUsed',
            typeInfo: 'Double'
          }, {
            name: 'hoursBalance',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'PaycheckJournalDeduction',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PaycheckJournalEarningList',
        propertyInfos: [{
            name: 'paycheckJournalEarning',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckJournalEarning'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckJournalCompanyTax',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Long'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PaycheckJournalCompanyContributionList',
        propertyInfos: [{
            name: 'paycheckJournalCompanyContribution',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckJournalCompanyContribution'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeBillSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.TimeBillSearch'
          }, {
            name: 'columns',
            typeInfo: '.TimeBillSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayDisburseList',
        propertyInfos: [{
            name: 'paycheckPayDisburse',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayDisburse'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeBillSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'callJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'chargeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ChargeSearchRowBasic'
          }, {
            name: 'classJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ClassificationSearchRowBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'departmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.DepartmentSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'eventJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchRowBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchRowBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'locationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LocationSearchRowBasic'
          }, {
            name: 'projectTaskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchRowBasic'
          }, {
            name: 'projectTaskAssignmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskAssignmentSearchRowBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchRowBasic'
          }, {
            name: 'taskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchRowBasic'
          }, {
            name: 'timeSheetJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeSheetSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'ExpenseReportExpenseList',
        propertyInfos: [{
            name: 'expense',
            minOccurs: 0,
            collection: true,
            typeInfo: '.ExpenseReportExpense'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPaySummaryList',
        propertyInfos: [{
            name: 'paycheckPaySummary',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPaySummary'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayDeduct',
        propertyInfos: [{
            name: 'payItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'wageBase',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'manualEntry',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'TimeEntrySearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeEntrySearchRowBasic'
          }, {
            name: 'callJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.PhoneCallSearchRowBasic'
          }, {
            name: 'caseJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.SupportCaseSearchRowBasic'
          }, {
            name: 'classJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ClassificationSearchRowBasic'
          }, {
            name: 'customerJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomerSearchRowBasic'
          }, {
            name: 'departmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.DepartmentSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'eventJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CalendarEventSearchRowBasic'
          }, {
            name: 'itemJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ItemSearchRowBasic'
          }, {
            name: 'jobJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.JobSearchRowBasic'
          }, {
            name: 'locationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.LocationSearchRowBasic'
          }, {
            name: 'projectTaskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskSearchRowBasic'
          }, {
            name: 'projectTaskAssignmentJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ProjectTaskAssignmentSearchRowBasic'
          }, {
            name: 'resourceAllocationJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.ResourceAllocationSearchRowBasic'
          }, {
            name: 'taskJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TaskSearchRowBasic'
          }, {
            name: 'timeSheetJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeSheetSearchRowBasic'
          }, {
            name: 'userJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'vendorJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.VendorSearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'PaycheckPayPtoList',
        propertyInfos: [{
            name: 'paycheckPayPto',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayPto'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeSheetTimeGrid',
        propertyInfos: [{
            name: 'sunday',
            typeInfo: '.TimeEntry'
          }, {
            name: 'monday',
            typeInfo: '.TimeEntry'
          }, {
            name: 'tuesday',
            typeInfo: '.TimeEntry'
          }, {
            name: 'wednesday',
            typeInfo: '.TimeEntry'
          }, {
            name: 'thursday',
            typeInfo: '.TimeEntry'
          }, {
            name: 'friday',
            typeInfo: '.TimeEntry'
          }, {
            name: 'saturday',
            typeInfo: '.TimeEntry'
          }]
      }, {
        localName: 'TimeSheetSearchRow',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRow',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeSheetSearchRowBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchRowBasic'
          }, {
            name: 'timeBillJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchRowBasic'
          }, {
            name: 'timeEntryJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeEntrySearchRowBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchRowBasic'
          }]
      }, {
        localName: 'PaycheckPayTax',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'payTax'
          }, {
            name: 'payItem',
            typeInfo: 'Long'
          }, {
            name: 'taxableWageBase',
            typeInfo: 'Double'
          }, {
            name: 'taxedWageBase',
            typeInfo: 'Double'
          }, {
            name: 'reportableWageBase',
            typeInfo: 'Double'
          }, {
            name: 'isExempt',
            typeInfo: 'Boolean'
          }, {
            name: 'isResidentTax',
            typeInfo: 'Boolean'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'PaycheckJournalCompanyTaxList',
        propertyInfos: [{
            name: 'paycheckJournalCompanyTax',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckJournalCompanyTax'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeSheetSearch',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'basic',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeSheetSearchBasic'
          }, {
            name: 'employeeJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.EmployeeSearchBasic'
          }, {
            name: 'timeBillJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeBillSearchBasic'
          }, {
            name: 'timeEntryJoin',
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.TimeEntrySearchBasic'
          }, {
            name: 'customSearchJoin',
            minOccurs: 0,
            collection: true,
            typeInfo: 'com_netsuite_webservices_platform_common_2019_2.CustomSearchJoin'
          }]
      }, {
        localName: 'ExpenseReportExpense',
        propertyInfos: [{
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'expenseDate',
            typeInfo: 'DateTime'
          }, {
            name: 'category',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'quantity',
            typeInfo: 'Double'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }, {
            name: 'foreignAmount',
            typeInfo: 'Double'
          }, {
            name: 'currency',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'exchangeRate',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'taxCode',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'memo'
          }, {
            name: 'taxRate1',
            typeInfo: 'Double'
          }, {
            name: 'tax1Amt',
            typeInfo: 'Double'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'grossAmt',
            typeInfo: 'Double'
          }, {
            name: 'taxRate2',
            typeInfo: 'Double'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'expMediaItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isNonReimbursable',
            typeInfo: 'Boolean'
          }, {
            name: 'corporateCreditCard',
            typeInfo: 'Boolean'
          }, {
            name: 'receipt',
            typeInfo: 'Boolean'
          }, {
            name: 'refNumber',
            typeInfo: 'Long'
          }, {
            name: 'taxDetailsReference'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }]
      }, {
        localName: 'PaycheckPayTaxList',
        propertyInfos: [{
            name: 'paycheckPayTax',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayTax'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayExp',
        propertyInfos: [{
            name: 'apply',
            typeInfo: 'Boolean'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'origDoc',
            typeInfo: 'Long'
          }, {
            name: 'transaction'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'PaycheckSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.PaycheckSearch'
          }, {
            name: 'columns',
            typeInfo: '.PaycheckSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeSheetTimeGridList',
        propertyInfos: [{
            name: 'timeSheetTimeGrid',
            minOccurs: 0,
            collection: true,
            typeInfo: '.TimeSheetTimeGrid'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Paycheck',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'batchNumber'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'status'
          }, {
            name: 'entity',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'address'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'workplace',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'tranId'
          }, {
            name: 'userAmount',
            typeInfo: 'Double'
          }, {
            name: 'memo'
          }, {
            name: 'account',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'payFrequency'
          }, {
            name: 'balance',
            typeInfo: 'Double'
          }, {
            name: 'tranDate',
            typeInfo: 'DateTime'
          }, {
            name: 'postingPeriod',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'periodEnding',
            typeInfo: 'DateTime'
          }, {
            name: 'payEarnList',
            typeInfo: '.PaycheckPayEarnList'
          }, {
            name: 'payTimeList',
            typeInfo: '.PaycheckPayTimeList'
          }, {
            name: 'payExpList',
            typeInfo: '.PaycheckPayExpList'
          }, {
            name: 'payPtoList',
            typeInfo: '.PaycheckPayPtoList'
          }, {
            name: 'payDeductList',
            typeInfo: '.PaycheckPayDeductList'
          }, {
            name: 'payContribList',
            typeInfo: '.PaycheckPayContribList'
          }, {
            name: 'payTaxList',
            typeInfo: '.PaycheckPayTaxList'
          }, {
            name: 'paySummaryList',
            typeInfo: '.PaycheckPaySummaryList'
          }, {
            name: 'payDisburseList',
            typeInfo: '.PaycheckPayDisburseList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayContrib',
        propertyInfos: [{
            name: 'payItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'line',
            typeInfo: 'Long'
          }, {
            name: 'wageBase',
            typeInfo: 'Double'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'manualEntry',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'PaycheckPaySummary',
        propertyInfos: [{
            name: 'payItem'
          }, {
            name: 'payItemType'
          }, {
            name: 'amount',
            typeInfo: 'Double'
          }, {
            name: 'ytdAmount',
            typeInfo: 'Double'
          }]
      }, {
        localName: 'TimeEntrySearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.TimeEntrySearch'
          }, {
            name: 'columns',
            typeInfo: '.TimeEntrySearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeEntry',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.Record',
        propertyInfos: [{
            name: 'hours',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.Duration'
          }, {
            name: 'createdDate',
            typeInfo: 'DateTime'
          }, {
            name: 'lastModifiedDate',
            typeInfo: 'DateTime'
          }, {
            name: 'customer',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'caseTaskEvent',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'item',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'isBillable',
            typeInfo: 'Boolean'
          }, {
            name: 'payrollItem',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'paidExternally',
            typeInfo: 'Boolean'
          }, {
            name: 'price',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'rate',
            typeInfo: 'Double'
          }, {
            name: 'overrideRate',
            typeInfo: 'Boolean'
          }, {
            name: 'memo'
          }, {
            name: 'department',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'clazz',
            elementName: 'class',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'location',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'billingClass'
          }, {
            name: 'subsidiary',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'approvalStatus',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.RecordRef'
          }, {
            name: 'timeType',
            typeInfo: 'com_netsuite_webservices_transactions_employees_2019_2_types.TimeBillTimeType'
          }, {
            name: 'customFieldList',
            typeInfo: 'com_netsuite_webservices_platform_core_2019_2.CustomFieldList'
          }, {
            name: 'internalId',
            attributeName: {
              localPart: 'internalId'
            },
            type: 'attribute'
          }, {
            name: 'externalId',
            attributeName: {
              localPart: 'externalId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayTimeList',
        propertyInfos: [{
            name: 'paycheckPayTime',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayTime'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'PaycheckPayEarnList',
        propertyInfos: [{
            name: 'paycheckPayEarn',
            minOccurs: 0,
            collection: true,
            typeInfo: '.PaycheckPayEarn'
          }, {
            name: 'replaceAll',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'replaceAll'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TimeSheetSearchAdvanced',
        baseTypeInfo: 'com_netsuite_webservices_platform_core_2019_2.SearchRecord',
        propertyInfos: [{
            name: 'criteria',
            typeInfo: '.TimeSheetSearch'
          }, {
            name: 'columns',
            typeInfo: '.TimeSheetSearchRow'
          }, {
            name: 'savedSearchId',
            attributeName: {
              localPart: 'savedSearchId'
            },
            type: 'attribute'
          }, {
            name: 'savedSearchScriptId',
            attributeName: {
              localPart: 'savedSearchScriptId'
            },
            type: 'attribute'
          }]
      }],
    elementInfos: [{
        typeInfo: '.TimeEntry',
        elementName: 'timeEntry'
      }, {
        typeInfo: '.TimeSheet',
        elementName: 'timeSheet'
      }, {
        typeInfo: '.ExpenseReport',
        elementName: 'expenseReport'
      }, {
        typeInfo: '.TimeBillSearch',
        elementName: 'timeBillSearch'
      }, {
        typeInfo: '.TimeBill',
        elementName: 'TimeBill'
      }, {
        typeInfo: '.PaycheckJournal',
        elementName: 'paycheckJournal'
      }, {
        typeInfo: '.TimeSheetSearch',
        elementName: 'timeSheetSearch'
      }, {
        typeInfo: '.Paycheck',
        elementName: 'paycheck'
      }, {
        typeInfo: '.TimeEntrySearch',
        elementName: 'timeEntrySearch'
      }, {
        typeInfo: '.PaycheckSearch',
        elementName: 'paycheckSearch'
      }]
  };
  return {
    com_netsuite_webservices_transactions_employees_2019_2: com_netsuite_webservices_transactions_employees_2019_2
  };
};
if (typeof define === 'function' && define.amd) {
  define([], com_netsuite_webservices_transactions_employees_2019_2_Module_Factory);
}
else {
  var com_netsuite_webservices_transactions_employees_2019_2_Module = com_netsuite_webservices_transactions_employees_2019_2_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.com_netsuite_webservices_transactions_employees_2019_2 = com_netsuite_webservices_transactions_employees_2019_2_Module.com_netsuite_webservices_transactions_employees_2019_2;
  }
  else {
    var com_netsuite_webservices_transactions_employees_2019_2 = com_netsuite_webservices_transactions_employees_2019_2_Module.com_netsuite_webservices_transactions_employees_2019_2;
  }
}