import { AddListRequest, AddListResponse, AddRequest, AddResponse, AsyncAddListRequest, AsyncDeleteListRequest, AsyncGetListRequest, AsyncInitializeListRequest, AsyncSearchRequest, AsyncStatusResponse, AsyncUpdateListRequest, AsyncUpsertListRequest, AttachRequest, AttachResponse, ChangeEmailRequest, ChangeEmailResponse, ChangePasswordRequest, ChangePasswordResponse, CheckAsyncStatusRequest, DeleteListRequest, DeleteListResponse, DeleteRequest, DeleteResponse, DetachRequest, DetachResponse, GetAllRequest, GetAllResponse, GetAsyncResultRequest, GetAsyncResultResponse, GetBudgetExchangeRateRequest, GetBudgetExchangeRateResponse, GetCurrencyRateRequest, GetCurrencyRateResponse, GetCustomizationIdRequest, GetCustomizationIdResponse, GetDataCenterUrlsRequest, GetDataCenterUrlsResponse, GetDeletedRequest, GetDeletedResponse, GetItemAvailabilityRequest, GetItemAvailabilityResponse, GetListRequest, GetListResponse, GetPostingTransactionSummaryRequest, GetPostingTransactionSummaryResponse, GetRequest, GetResponse, GetSavedSearchRequest, GetSavedSearchResponse, GetSelectValueRequest, GetSelectValueResponse, GetServerTimeRequest, GetServerTimeResponse, InitializeListRequest, InitializeListResponse, InitializeRequest, InitializeResponse, LoginRequest, LoginResponse, LogoutRequest, LogoutResponse, MapSsoRequest, MapSsoResponse, SearchMoreRequest, SearchMoreResponse, SearchMoreWithIdRequest, SearchMoreWithIdResponse, SearchNextRequest, SearchNextResponse, SearchRequest, SearchResponse, SsoLoginRequest, SsoLoginResponse, UpdateInviteeStatusListRequest, UpdateInviteeStatusListResponse, UpdateInviteeStatusRequest, UpdateInviteeStatusResponse, UpdateListRequest, UpdateListResponse, UpdateRequest, UpdateResponse, UpsertListRequest, UpsertListResponse, UpsertRequest, UpsertResponse } from "./netsuite_webservices/2019_2/platform_messages";
import { Configuration } from "./types";
export declare class TypeSuiteClient {
    readonly config: Configuration;
    constructor(config: Configuration);
    add(request: AddRequest): Promise<AddResponse>;
    addList(request: AddListRequest): Promise<AddListResponse>;
    asyncAddList(request: AsyncAddListRequest): Promise<AsyncStatusResponse>;
    asyncDeleteList(request: AsyncDeleteListRequest): Promise<AsyncStatusResponse>;
    asyncGetList(request: AsyncGetListRequest): Promise<AsyncStatusResponse>;
    asyncInitializeList(request: AsyncInitializeListRequest): Promise<AsyncStatusResponse>;
    asyncSearch(request: AsyncSearchRequest): Promise<AsyncStatusResponse>;
    asyncUpdateList(request: AsyncUpdateListRequest): Promise<AsyncStatusResponse>;
    asyncUpsertList(request: AsyncUpsertListRequest): Promise<AsyncStatusResponse>;
    attach(request: AttachRequest): Promise<AttachResponse>;
    changeEmail(request: ChangeEmailRequest): Promise<ChangeEmailResponse>;
    changePassword(request: ChangePasswordRequest): Promise<ChangePasswordResponse>;
    checkAsyncStatus(request: CheckAsyncStatusRequest): Promise<AsyncStatusResponse>;
    delete(request: DeleteRequest): Promise<DeleteResponse>;
    deleteList(request: DeleteListRequest): Promise<DeleteListResponse>;
    detach(request: DetachRequest): Promise<DetachResponse>;
    get(request: GetRequest): Promise<GetResponse>;
    getAll(request: GetAllRequest): Promise<GetAllResponse>;
    getAsyncResult(request: GetAsyncResultRequest): Promise<GetAsyncResultResponse>;
    getBudgetExchangeRate(request: GetBudgetExchangeRateRequest): Promise<GetBudgetExchangeRateResponse>;
    getCurrencyRate(request: GetCurrencyRateRequest): Promise<GetCurrencyRateResponse>;
    getCustomizationId(request: GetCustomizationIdRequest): Promise<GetCustomizationIdResponse>;
    getDataCenterUrls(request: GetDataCenterUrlsRequest): Promise<GetDataCenterUrlsResponse>;
    getDeleted(request: GetDeletedRequest): Promise<GetDeletedResponse>;
    getItemAvailability(request: GetItemAvailabilityRequest): Promise<GetItemAvailabilityResponse>;
    getList(request: GetListRequest): Promise<GetListResponse>;
    getPostingTransactionSummary(request: GetPostingTransactionSummaryRequest): Promise<GetPostingTransactionSummaryResponse>;
    getSavedSearch(request: GetSavedSearchRequest): Promise<GetSavedSearchResponse>;
    getSelectValue(request: GetSelectValueRequest): Promise<GetSelectValueResponse>;
    getServerTime(request: GetServerTimeRequest): Promise<GetServerTimeResponse>;
    initialize(request: InitializeRequest): Promise<InitializeResponse>;
    initializeList(request: InitializeListRequest): Promise<InitializeListResponse>;
    login(request: LoginRequest): Promise<LoginResponse>;
    logout(request: LogoutRequest): Promise<LogoutResponse>;
    mapSso(request: MapSsoRequest): Promise<MapSsoResponse>;
    search(request: SearchRequest): Promise<SearchResponse>;
    searchMore(request: SearchMoreRequest): Promise<SearchMoreResponse>;
    searchMoreWithId(request: SearchMoreWithIdRequest): Promise<SearchMoreWithIdResponse>;
    searchNext(request: SearchNextRequest): Promise<SearchNextResponse>;
    ssoLogin(request: SsoLoginRequest): Promise<SsoLoginResponse>;
    update(request: UpdateRequest): Promise<UpdateResponse>;
    updateInviteeStatus(request: UpdateInviteeStatusRequest): Promise<UpdateInviteeStatusResponse>;
    updateInviteeStatusList(request: UpdateInviteeStatusListRequest): Promise<UpdateInviteeStatusListResponse>;
    updateList(request: UpdateListRequest): Promise<UpdateListResponse>;
    upsert(request: UpsertRequest): Promise<UpsertResponse>;
    upsertList(request: UpsertListRequest): Promise<UpsertListResponse>;
}
