# See the following URL for configuration documentation.
# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    ignored_updates:
      - match:
          dependency_name: "aws-xray-sdk-core"
    automerged_updates:
      - match:
          dependency_type: production
          update_type: all
      - match:
          dependency_type: development
          update_type: all
