export type TextFileEncoding =
  | "_big5"
  | "_gb2312"
  | "_gb18030"
  | "_iso88591"
  | "_macRoman"
  | "_shiftJis"
  | "_utf8"
  | "_windows1252";

export type MediaType =
  | "_APPCACHE"
  | "_AUTOCAD"
  | "_BMPIMAGE"
  | "_CERTIFICATE"
  | "_CFF"
  | "_CONFIG"
  | "_CSV"
  | "_EOT"
  | "_EXCEL"
  | "_FLASH"
  | "_FREEMARKER"
  | "_GIFIMAGE"
  | "_GZIP"
  | "_HTMLDOC"
  | "_ICON"
  | "_IMAGE"
  | "_JAVASCRIPT"
  | "_JPGIMAGE"
  | "_JSON"
  | "_LZH"
  | "_MESSAGERFC"
  | "_MISCBINARY"
  | "_MISCTEXT"
  | "_MP3"
  | "_MPEGMOVIE"
  | "_MSPROJECT"
  | "_OTF"
  | "_PDF"
  | "_PJPGIMAGE"
  | "_PLAINTEXT"
  | "_PNGIMAGE"
  | "_POSTSCRIPT"
  | "_POWERPOINT"
  | "_QUICKTIME"
  | "_RTF"
  | "_SCSS"
  | "_SMS"
  | "_STYLESHEET"
  | "_SVG"
  | "_TAR"
  | "_TARCOMP"
  | "_TIFFIMAGE"
  | "_TTF"
  | "_VISIO"
  | "_WEBAPPPAGE"
  | "_WEBAPPSCRIPT"
  | "_WOFF"
  | "_WOFF2"
  | "_WORD"
  | "_XMLDOC"
  | "_XSD"
  | "_ZIP";

export type FolderFolderType =
  | "_appPackages"
  | "_attachmentsReceived"
  | "_attachmentsSent"
  | "_certificates"
  | "_documentsAndFiles"
  | "_emailTemplates"
  | "_faxTemplates"
  | "_images"
  | "_letterTemplates"
  | "_mailMerge"
  | "_marketingTemplates"
  | "_pdfTemplates"
  | "_suitebundles"
  | "_suitecommerceAdvancedSiteTemplates"
  | "_suitescripts"
  | "_templates"
  | "_webSiteHostingFiles";

export type FileAttachFrom = "_computer" | "_web";

export type FileEncoding =
  | "_autoDetect"
  | "_shiftJis"
  | "_utf8"
  | "_windows1252";
