import * as PlatformCore from "./platform_core";
import * as PlatformCommon from "./platform_common";
import * as TransactionsCustomersTypes from "./transactions_customers_types";
import * as PlatformCommonTypes from "./platform_common_types";

export type ReturnAuthorizationSalesTeamListProps = {
  salesTeam?: ReturnAuthorizationSalesTeam[];
  replaceAll?: boolean;
};

export class ReturnAuthorizationSalesTeamList {
  salesTeam?: ReturnAuthorizationSalesTeam[];
  replaceAll?: boolean;
  constructor(props: ReturnAuthorizationSalesTeamListProps) {
    this.salesTeam = props.salesTeam;
    this.replaceAll = props.replaceAll;
  }
}

export type CreditMemoApplyProps = {
  apply?: boolean;
  doc?: number;
  applyDate?: string;
  job?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
  line?: number;
};

export class CreditMemoApply {
  apply?: boolean;
  doc?: number;
  applyDate?: string;
  job?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
  line?: number;
  constructor(props: CreditMemoApplyProps) {
    this.apply = props.apply;
    this.doc = props.doc;
    this.applyDate = props.applyDate;
    this.job = props.job;
    this.type = props.type;
    this.refNum = props.refNum;
    this.total = props.total;
    this.due = props.due;
    this.currency = props.currency;
    this.amount = props.amount;
    this.line = props.line;
  }
}

export type CustomerPaymentDepositListProps = {
  deposit?: CustomerPaymentDeposit[];
  replaceAll?: boolean;
};

export class CustomerPaymentDepositList {
  deposit?: CustomerPaymentDeposit[];
  replaceAll?: boolean;
  constructor(props: CustomerPaymentDepositListProps) {
    this.deposit = props.deposit;
    this.replaceAll = props.replaceAll;
  }
}

export type CustomerRefundApplyProps = {
  apply?: boolean;
  doc?: number;
  line?: number;
  applyDate?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
};

export class CustomerRefundApply {
  apply?: boolean;
  doc?: number;
  line?: number;
  applyDate?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
  constructor(props: CustomerRefundApplyProps) {
    this.apply = props.apply;
    this.doc = props.doc;
    this.line = props.line;
    this.applyDate = props.applyDate;
    this.type = props.type;
    this.refNum = props.refNum;
    this.total = props.total;
    this.due = props.due;
    this.currency = props.currency;
    this.amount = props.amount;
  }
}

export type ReturnAuthorizationProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  nexus?: PlatformCore.RecordRef;
  subsidiaryTaxRegNum?: PlatformCore.RecordRef;
  taxRegOverride?: boolean;
  taxDetailsOverride?: boolean;
  customForm?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  entity?: PlatformCore.RecordRef;
  vatRegNum?: string;
  tranDate?: string;
  tranId?: string;
  entityTaxRegNum?: PlatformCore.RecordRef;
  taxPointDate?: string;
  source?: string;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  subsidiary?: PlatformCore.RecordRef;
  intercoTransaction?: PlatformCore.RecordRef;
  intercoStatus?: PlatformCommonTypes.IntercoStatus;
  job?: PlatformCore.RecordRef;
  partner?: PlatformCore.RecordRef;
  otherRefNum?: string;
  leadSource?: PlatformCore.RecordRef;
  memo?: string;
  drAccount?: PlatformCore.RecordRef;
  fxAccount?: PlatformCore.RecordRef;
  salesEffectiveDate?: string;
  createdFrom?: PlatformCore.RecordRef;
  revRecSchedule?: PlatformCore.RecordRef;
  totalCostEstimate?: number;
  estGrossProfit?: number;
  estGrossProfitPercent?: number;
  revRecStartDate?: string;
  revRecEndDate?: string;
  excludeCommission?: boolean;
  exchangeRate?: number;
  currencyName?: string;
  discountItem?: PlatformCore.RecordRef;
  discountRate?: string;
  taxItem?: PlatformCore.RecordRef;
  taxRate?: number;
  toBePrinted?: boolean;
  toBeEmailed?: boolean;
  toBeFaxed?: boolean;
  messageSel?: PlatformCore.RecordRef;
  message?: string;
  billingAddress?: PlatformCommon.Address;
  billAddressList?: PlatformCore.RecordRef;
  shipAddressList?: PlatformCore.RecordRef;
  shipAddress?: string;
  salesGroup?: PlatformCore.RecordRef;
  syncSalesTeams?: boolean;
  revenueStatus?: PlatformCommonTypes.RevenueStatus;
  recognizedRevenue?: number;
  deferredRevenue?: number;
  revRecOnRevCommitment?: boolean;
  revCommitStatus?: PlatformCommonTypes.RevenueCommitStatus;
  paymentMethod?: PlatformCore.RecordRef;
  creditCard?: PlatformCore.RecordRef;
  ccNumber?: string;
  altSalesTotal?: number;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  pnRefNum?: string;
  subTotal?: number;
  discountTotal?: number;
  total?: number;
  creditCardProcessor?: PlatformCore.RecordRef;
  payPalAuthId?: string;
  payPalProcess?: boolean;
  email?: string;
  fax?: string;
  debitCardIssueNo?: string;
  isTaxable?: boolean;
  promoCode?: PlatformCore.RecordRef;
  status?: string;
  taxTotal?: number;
  tax2Total?: number;
  validFrom?: string;
  orderStatus?: TransactionsCustomersTypes.ReturnAuthorizationOrderStatus;
  salesRep?: PlatformCore.RecordRef;
  giftCert?: PlatformCore.RecordRef;
  contribPct?: string;
  giftCertTotal?: number;
  giftCertApplied?: number;
  giftCertAvailable?: number;
  tranIsVsoeBundle?: boolean;
  vsoeAutoCalc?: boolean;
  syncPartnerTeams?: boolean;
  itemList?: ReturnAuthorizationItemList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  salesTeamList?: ReturnAuthorizationSalesTeamList;
  partnersList?: ReturnAuthorizationPartnersList;
  taxDetailsList?: PlatformCommon.TaxDetailsList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class ReturnAuthorization extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  nexus?: PlatformCore.RecordRef;
  subsidiaryTaxRegNum?: PlatformCore.RecordRef;
  taxRegOverride?: boolean;
  taxDetailsOverride?: boolean;
  customForm?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  entity?: PlatformCore.RecordRef;
  vatRegNum?: string;
  tranDate?: string;
  tranId?: string;
  entityTaxRegNum?: PlatformCore.RecordRef;
  taxPointDate?: string;
  source?: string;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  subsidiary?: PlatformCore.RecordRef;
  intercoTransaction?: PlatformCore.RecordRef;
  intercoStatus?: PlatformCommonTypes.IntercoStatus;
  job?: PlatformCore.RecordRef;
  partner?: PlatformCore.RecordRef;
  otherRefNum?: string;
  leadSource?: PlatformCore.RecordRef;
  memo?: string;
  drAccount?: PlatformCore.RecordRef;
  fxAccount?: PlatformCore.RecordRef;
  salesEffectiveDate?: string;
  createdFrom?: PlatformCore.RecordRef;
  revRecSchedule?: PlatformCore.RecordRef;
  totalCostEstimate?: number;
  estGrossProfit?: number;
  estGrossProfitPercent?: number;
  revRecStartDate?: string;
  revRecEndDate?: string;
  excludeCommission?: boolean;
  exchangeRate?: number;
  currencyName?: string;
  discountItem?: PlatformCore.RecordRef;
  discountRate?: string;
  taxItem?: PlatformCore.RecordRef;
  taxRate?: number;
  toBePrinted?: boolean;
  toBeEmailed?: boolean;
  toBeFaxed?: boolean;
  messageSel?: PlatformCore.RecordRef;
  message?: string;
  billingAddress?: PlatformCommon.Address;
  billAddressList?: PlatformCore.RecordRef;
  shipAddressList?: PlatformCore.RecordRef;
  shipAddress?: string;
  salesGroup?: PlatformCore.RecordRef;
  syncSalesTeams?: boolean;
  revenueStatus?: PlatformCommonTypes.RevenueStatus;
  recognizedRevenue?: number;
  deferredRevenue?: number;
  revRecOnRevCommitment?: boolean;
  revCommitStatus?: PlatformCommonTypes.RevenueCommitStatus;
  paymentMethod?: PlatformCore.RecordRef;
  creditCard?: PlatformCore.RecordRef;
  ccNumber?: string;
  altSalesTotal?: number;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  pnRefNum?: string;
  subTotal?: number;
  discountTotal?: number;
  total?: number;
  creditCardProcessor?: PlatformCore.RecordRef;
  payPalAuthId?: string;
  payPalProcess?: boolean;
  email?: string;
  fax?: string;
  debitCardIssueNo?: string;
  isTaxable?: boolean;
  promoCode?: PlatformCore.RecordRef;
  status?: string;
  taxTotal?: number;
  tax2Total?: number;
  validFrom?: string;
  orderStatus?: TransactionsCustomersTypes.ReturnAuthorizationOrderStatus;
  salesRep?: PlatformCore.RecordRef;
  giftCert?: PlatformCore.RecordRef;
  contribPct?: string;
  giftCertTotal?: number;
  giftCertApplied?: number;
  giftCertAvailable?: number;
  tranIsVsoeBundle?: boolean;
  vsoeAutoCalc?: boolean;
  syncPartnerTeams?: boolean;
  itemList?: ReturnAuthorizationItemList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  salesTeamList?: ReturnAuthorizationSalesTeamList;
  partnersList?: ReturnAuthorizationPartnersList;
  taxDetailsList?: PlatformCommon.TaxDetailsList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: ReturnAuthorizationProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.nexus = props.nexus;
    this.subsidiaryTaxRegNum = props.subsidiaryTaxRegNum;
    this.taxRegOverride = props.taxRegOverride;
    this.taxDetailsOverride = props.taxDetailsOverride;
    this.customForm = props.customForm;
    this.currency = props.currency;
    this.entity = props.entity;
    this.vatRegNum = props.vatRegNum;
    this.tranDate = props.tranDate;
    this.tranId = props.tranId;
    this.entityTaxRegNum = props.entityTaxRegNum;
    this.taxPointDate = props.taxPointDate;
    this.source = props.source;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.subsidiary = props.subsidiary;
    this.intercoTransaction = props.intercoTransaction;
    this.intercoStatus = props.intercoStatus;
    this.job = props.job;
    this.partner = props.partner;
    this.otherRefNum = props.otherRefNum;
    this.leadSource = props.leadSource;
    this.memo = props.memo;
    this.drAccount = props.drAccount;
    this.fxAccount = props.fxAccount;
    this.salesEffectiveDate = props.salesEffectiveDate;
    this.createdFrom = props.createdFrom;
    this.revRecSchedule = props.revRecSchedule;
    this.totalCostEstimate = props.totalCostEstimate;
    this.estGrossProfit = props.estGrossProfit;
    this.estGrossProfitPercent = props.estGrossProfitPercent;
    this.revRecStartDate = props.revRecStartDate;
    this.revRecEndDate = props.revRecEndDate;
    this.excludeCommission = props.excludeCommission;
    this.exchangeRate = props.exchangeRate;
    this.currencyName = props.currencyName;
    this.discountItem = props.discountItem;
    this.discountRate = props.discountRate;
    this.taxItem = props.taxItem;
    this.taxRate = props.taxRate;
    this.toBePrinted = props.toBePrinted;
    this.toBeEmailed = props.toBeEmailed;
    this.toBeFaxed = props.toBeFaxed;
    this.messageSel = props.messageSel;
    this.message = props.message;
    this.billingAddress = props.billingAddress;
    this.billAddressList = props.billAddressList;
    this.shipAddressList = props.shipAddressList;
    this.shipAddress = props.shipAddress;
    this.salesGroup = props.salesGroup;
    this.syncSalesTeams = props.syncSalesTeams;
    this.revenueStatus = props.revenueStatus;
    this.recognizedRevenue = props.recognizedRevenue;
    this.deferredRevenue = props.deferredRevenue;
    this.revRecOnRevCommitment = props.revRecOnRevCommitment;
    this.revCommitStatus = props.revCommitStatus;
    this.paymentMethod = props.paymentMethod;
    this.creditCard = props.creditCard;
    this.ccNumber = props.ccNumber;
    this.altSalesTotal = props.altSalesTotal;
    this.ccExpireDate = props.ccExpireDate;
    this.ccName = props.ccName;
    this.ccStreet = props.ccStreet;
    this.ccZipCode = props.ccZipCode;
    this.ccApproved = props.ccApproved;
    this.pnRefNum = props.pnRefNum;
    this.subTotal = props.subTotal;
    this.discountTotal = props.discountTotal;
    this.total = props.total;
    this.creditCardProcessor = props.creditCardProcessor;
    this.payPalAuthId = props.payPalAuthId;
    this.payPalProcess = props.payPalProcess;
    this.email = props.email;
    this.fax = props.fax;
    this.debitCardIssueNo = props.debitCardIssueNo;
    this.isTaxable = props.isTaxable;
    this.promoCode = props.promoCode;
    this.status = props.status;
    this.taxTotal = props.taxTotal;
    this.tax2Total = props.tax2Total;
    this.validFrom = props.validFrom;
    this.orderStatus = props.orderStatus;
    this.salesRep = props.salesRep;
    this.giftCert = props.giftCert;
    this.contribPct = props.contribPct;
    this.giftCertTotal = props.giftCertTotal;
    this.giftCertApplied = props.giftCertApplied;
    this.giftCertAvailable = props.giftCertAvailable;
    this.tranIsVsoeBundle = props.tranIsVsoeBundle;
    this.vsoeAutoCalc = props.vsoeAutoCalc;
    this.syncPartnerTeams = props.syncPartnerTeams;
    this.itemList = props.itemList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.salesTeamList = props.salesTeamList;
    this.partnersList = props.partnersList;
    this.taxDetailsList = props.taxDetailsList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type CustomerRefundApplyListProps = {
  apply?: CustomerRefundApply[];
  replaceAll?: boolean;
};

export class CustomerRefundApplyList {
  apply?: CustomerRefundApply[];
  replaceAll?: boolean;
  constructor(props: CustomerRefundApplyListProps) {
    this.apply = props.apply;
    this.replaceAll = props.replaceAll;
  }
}

export type DepositApplicationProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  arAcct?: PlatformCore.RecordRef;
  status?: string;
  customer?: PlatformCore.RecordRef;
  tranDate?: string;
  postingPeriod?: PlatformCore.RecordRef;
  deposit?: PlatformCore.RecordRef;
  depDate?: string;
  currency?: PlatformCore.RecordRef;
  exchangeRate?: number;
  memo?: string;
  subsidiary?: PlatformCore.RecordRef;
  total?: number;
  department?: PlatformCore.RecordRef;
  applied?: number;
  clazz?: PlatformCore.RecordRef;
  unapplied?: number;
  location?: PlatformCore.RecordRef;
  tranId?: string;
  applyList?: DepositApplicationApplyList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class DepositApplication extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  arAcct?: PlatformCore.RecordRef;
  status?: string;
  customer?: PlatformCore.RecordRef;
  tranDate?: string;
  postingPeriod?: PlatformCore.RecordRef;
  deposit?: PlatformCore.RecordRef;
  depDate?: string;
  currency?: PlatformCore.RecordRef;
  exchangeRate?: number;
  memo?: string;
  subsidiary?: PlatformCore.RecordRef;
  total?: number;
  department?: PlatformCore.RecordRef;
  applied?: number;
  clazz?: PlatformCore.RecordRef;
  unapplied?: number;
  location?: PlatformCore.RecordRef;
  tranId?: string;
  applyList?: DepositApplicationApplyList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: DepositApplicationProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.arAcct = props.arAcct;
    this.status = props.status;
    this.customer = props.customer;
    this.tranDate = props.tranDate;
    this.postingPeriod = props.postingPeriod;
    this.deposit = props.deposit;
    this.depDate = props.depDate;
    this.currency = props.currency;
    this.exchangeRate = props.exchangeRate;
    this.memo = props.memo;
    this.subsidiary = props.subsidiary;
    this.total = props.total;
    this.department = props.department;
    this.applied = props.applied;
    this.clazz = props.clazz;
    this.unapplied = props.unapplied;
    this.location = props.location;
    this.tranId = props.tranId;
    this.applyList = props.applyList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type CustomerPaymentApplyListProps = {
  apply?: CustomerPaymentApply[];
  replaceAll?: boolean;
};

export class CustomerPaymentApplyList {
  apply?: CustomerPaymentApply[];
  replaceAll?: boolean;
  constructor(props: CustomerPaymentApplyListProps) {
    this.apply = props.apply;
    this.replaceAll = props.replaceAll;
  }
}

export type ChargeSearchProps = {
  basic?: PlatformCommon.ChargeSearchBasic;
  billingAccountJoin?: PlatformCommon.BillingAccountSearchBasic;
  billingScheduleJoin?: PlatformCommon.BillingScheduleSearchBasic;
  chargeEmployeeJoin?: PlatformCommon.EmployeeSearchBasic;
  customerJoin?: PlatformCommon.CustomerSearchBasic;
  invoiceJoin?: PlatformCommon.TransactionSearchBasic;
  itemJoin?: PlatformCommon.ItemSearchBasic;
  jobJoin?: PlatformCommon.JobSearchBasic;
  salesOrderJoin?: PlatformCommon.TransactionSearchBasic;
  timeJoin?: PlatformCommon.TimeBillSearchBasic;
  transactionJoin?: PlatformCommon.TransactionSearchBasic;
  usageJoin?: PlatformCommon.UsageSearchBasic;
  userJoin?: PlatformCommon.EmployeeSearchBasic;
  customSearchJoin?: PlatformCommon.CustomSearchJoin[];
};

export class ChargeSearch extends PlatformCore.SearchRecord {
  basic?: PlatformCommon.ChargeSearchBasic;
  billingAccountJoin?: PlatformCommon.BillingAccountSearchBasic;
  billingScheduleJoin?: PlatformCommon.BillingScheduleSearchBasic;
  chargeEmployeeJoin?: PlatformCommon.EmployeeSearchBasic;
  customerJoin?: PlatformCommon.CustomerSearchBasic;
  invoiceJoin?: PlatformCommon.TransactionSearchBasic;
  itemJoin?: PlatformCommon.ItemSearchBasic;
  jobJoin?: PlatformCommon.JobSearchBasic;
  salesOrderJoin?: PlatformCommon.TransactionSearchBasic;
  timeJoin?: PlatformCommon.TimeBillSearchBasic;
  transactionJoin?: PlatformCommon.TransactionSearchBasic;
  usageJoin?: PlatformCommon.UsageSearchBasic;
  userJoin?: PlatformCommon.EmployeeSearchBasic;
  customSearchJoin?: PlatformCommon.CustomSearchJoin[];
  constructor(props: ChargeSearchProps) {
    super();
    this.basic = props.basic;
    this.billingAccountJoin = props.billingAccountJoin;
    this.billingScheduleJoin = props.billingScheduleJoin;
    this.chargeEmployeeJoin = props.chargeEmployeeJoin;
    this.customerJoin = props.customerJoin;
    this.invoiceJoin = props.invoiceJoin;
    this.itemJoin = props.itemJoin;
    this.jobJoin = props.jobJoin;
    this.salesOrderJoin = props.salesOrderJoin;
    this.timeJoin = props.timeJoin;
    this.transactionJoin = props.transactionJoin;
    this.usageJoin = props.usageJoin;
    this.userJoin = props.userJoin;
    this.customSearchJoin = props.customSearchJoin;
  }
}

export type CreditMemoProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  nexus?: PlatformCore.RecordRef;
  subsidiaryTaxRegNum?: PlatformCore.RecordRef;
  taxRegOverride?: boolean;
  taxDetailsOverride?: boolean;
  customForm?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  entity?: PlatformCore.RecordRef;
  vatRegNum?: string;
  tranDate?: string;
  tranId?: string;
  entityTaxRegNum?: PlatformCore.RecordRef;
  taxPointDate?: string;
  createdFrom?: PlatformCore.RecordRef;
  postingPeriod?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  subsidiary?: PlatformCore.RecordRef;
  job?: PlatformCore.RecordRef;
  salesRep?: PlatformCore.RecordRef;
  partner?: PlatformCore.RecordRef;
  contribPct?: string;
  otherRefNum?: string;
  memo?: string;
  excludeCommission?: boolean;
  leadSource?: PlatformCore.RecordRef;
  balance?: number;
  account?: PlatformCore.RecordRef;
  exchangeRate?: number;
  onCreditHold?: string;
  amountPaid?: number;
  salesEffectiveDate?: string;
  totalCostEstimate?: number;
  estGrossProfit?: number;
  estGrossProfitPercent?: number;
  currencyName?: string;
  promoCode?: PlatformCore.RecordRef;
  amountRemaining?: number;
  discountItem?: PlatformCore.RecordRef;
  source?: string;
  discountRate?: string;
  isTaxable?: boolean;
  taxItem?: PlatformCore.RecordRef;
  taxRate?: number;
  unapplied?: number;
  autoApply?: boolean;
  applied?: number;
  toBePrinted?: boolean;
  toBeEmailed?: boolean;
  email?: string;
  toBeFaxed?: boolean;
  fax?: string;
  messageSel?: PlatformCore.RecordRef;
  message?: string;
  billingAddress?: PlatformCommon.Address;
  billAddressList?: PlatformCore.RecordRef;
  shipMethod?: PlatformCore.RecordRef;
  shippingCost?: number;
  shippingTax1Rate?: number;
  shippingTaxCode?: PlatformCore.RecordRef;
  handlingTaxCode?: PlatformCore.RecordRef;
  shippingTax2Rate?: string;
  handlingTax1Rate?: number;
  handlingTax2Rate?: string;
  handlingCost?: number;
  subTotal?: number;
  discountTotal?: number;
  revenueStatus?: PlatformCommonTypes.RevenueStatus;
  recognizedRevenue?: number;
  deferredRevenue?: number;
  revRecOnRevCommitment?: boolean;
  taxTotal?: number;
  tax2Total?: number;
  altShippingCost?: number;
  altHandlingCost?: number;
  isMultiShipTo?: boolean;
  total?: number;
  salesGroup?: PlatformCore.RecordRef;
  syncSalesTeams?: boolean;
  status?: string;
  giftCert?: PlatformCore.RecordRef;
  giftCertTotal?: number;
  giftCertApplied?: number;
  giftCertAvailable?: number;
  tranIsVsoeBundle?: boolean;
  vsoeAutoCalc?: boolean;
  syncPartnerTeams?: boolean;
  salesTeamList?: CreditMemoSalesTeamList;
  itemList?: CreditMemoItemList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  partnersList?: CreditMemoPartnersList;
  applyList?: CreditMemoApplyList;
  taxDetailsList?: PlatformCommon.TaxDetailsList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class CreditMemo extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  nexus?: PlatformCore.RecordRef;
  subsidiaryTaxRegNum?: PlatformCore.RecordRef;
  taxRegOverride?: boolean;
  taxDetailsOverride?: boolean;
  customForm?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  entity?: PlatformCore.RecordRef;
  vatRegNum?: string;
  tranDate?: string;
  tranId?: string;
  entityTaxRegNum?: PlatformCore.RecordRef;
  taxPointDate?: string;
  createdFrom?: PlatformCore.RecordRef;
  postingPeriod?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  subsidiary?: PlatformCore.RecordRef;
  job?: PlatformCore.RecordRef;
  salesRep?: PlatformCore.RecordRef;
  partner?: PlatformCore.RecordRef;
  contribPct?: string;
  otherRefNum?: string;
  memo?: string;
  excludeCommission?: boolean;
  leadSource?: PlatformCore.RecordRef;
  balance?: number;
  account?: PlatformCore.RecordRef;
  exchangeRate?: number;
  onCreditHold?: string;
  amountPaid?: number;
  salesEffectiveDate?: string;
  totalCostEstimate?: number;
  estGrossProfit?: number;
  estGrossProfitPercent?: number;
  currencyName?: string;
  promoCode?: PlatformCore.RecordRef;
  amountRemaining?: number;
  discountItem?: PlatformCore.RecordRef;
  source?: string;
  discountRate?: string;
  isTaxable?: boolean;
  taxItem?: PlatformCore.RecordRef;
  taxRate?: number;
  unapplied?: number;
  autoApply?: boolean;
  applied?: number;
  toBePrinted?: boolean;
  toBeEmailed?: boolean;
  email?: string;
  toBeFaxed?: boolean;
  fax?: string;
  messageSel?: PlatformCore.RecordRef;
  message?: string;
  billingAddress?: PlatformCommon.Address;
  billAddressList?: PlatformCore.RecordRef;
  shipMethod?: PlatformCore.RecordRef;
  shippingCost?: number;
  shippingTax1Rate?: number;
  shippingTaxCode?: PlatformCore.RecordRef;
  handlingTaxCode?: PlatformCore.RecordRef;
  shippingTax2Rate?: string;
  handlingTax1Rate?: number;
  handlingTax2Rate?: string;
  handlingCost?: number;
  subTotal?: number;
  discountTotal?: number;
  revenueStatus?: PlatformCommonTypes.RevenueStatus;
  recognizedRevenue?: number;
  deferredRevenue?: number;
  revRecOnRevCommitment?: boolean;
  taxTotal?: number;
  tax2Total?: number;
  altShippingCost?: number;
  altHandlingCost?: number;
  isMultiShipTo?: boolean;
  total?: number;
  salesGroup?: PlatformCore.RecordRef;
  syncSalesTeams?: boolean;
  status?: string;
  giftCert?: PlatformCore.RecordRef;
  giftCertTotal?: number;
  giftCertApplied?: number;
  giftCertAvailable?: number;
  tranIsVsoeBundle?: boolean;
  vsoeAutoCalc?: boolean;
  syncPartnerTeams?: boolean;
  salesTeamList?: CreditMemoSalesTeamList;
  itemList?: CreditMemoItemList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  partnersList?: CreditMemoPartnersList;
  applyList?: CreditMemoApplyList;
  taxDetailsList?: PlatformCommon.TaxDetailsList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: CreditMemoProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.nexus = props.nexus;
    this.subsidiaryTaxRegNum = props.subsidiaryTaxRegNum;
    this.taxRegOverride = props.taxRegOverride;
    this.taxDetailsOverride = props.taxDetailsOverride;
    this.customForm = props.customForm;
    this.currency = props.currency;
    this.entity = props.entity;
    this.vatRegNum = props.vatRegNum;
    this.tranDate = props.tranDate;
    this.tranId = props.tranId;
    this.entityTaxRegNum = props.entityTaxRegNum;
    this.taxPointDate = props.taxPointDate;
    this.createdFrom = props.createdFrom;
    this.postingPeriod = props.postingPeriod;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.subsidiary = props.subsidiary;
    this.job = props.job;
    this.salesRep = props.salesRep;
    this.partner = props.partner;
    this.contribPct = props.contribPct;
    this.otherRefNum = props.otherRefNum;
    this.memo = props.memo;
    this.excludeCommission = props.excludeCommission;
    this.leadSource = props.leadSource;
    this.balance = props.balance;
    this.account = props.account;
    this.exchangeRate = props.exchangeRate;
    this.onCreditHold = props.onCreditHold;
    this.amountPaid = props.amountPaid;
    this.salesEffectiveDate = props.salesEffectiveDate;
    this.totalCostEstimate = props.totalCostEstimate;
    this.estGrossProfit = props.estGrossProfit;
    this.estGrossProfitPercent = props.estGrossProfitPercent;
    this.currencyName = props.currencyName;
    this.promoCode = props.promoCode;
    this.amountRemaining = props.amountRemaining;
    this.discountItem = props.discountItem;
    this.source = props.source;
    this.discountRate = props.discountRate;
    this.isTaxable = props.isTaxable;
    this.taxItem = props.taxItem;
    this.taxRate = props.taxRate;
    this.unapplied = props.unapplied;
    this.autoApply = props.autoApply;
    this.applied = props.applied;
    this.toBePrinted = props.toBePrinted;
    this.toBeEmailed = props.toBeEmailed;
    this.email = props.email;
    this.toBeFaxed = props.toBeFaxed;
    this.fax = props.fax;
    this.messageSel = props.messageSel;
    this.message = props.message;
    this.billingAddress = props.billingAddress;
    this.billAddressList = props.billAddressList;
    this.shipMethod = props.shipMethod;
    this.shippingCost = props.shippingCost;
    this.shippingTax1Rate = props.shippingTax1Rate;
    this.shippingTaxCode = props.shippingTaxCode;
    this.handlingTaxCode = props.handlingTaxCode;
    this.shippingTax2Rate = props.shippingTax2Rate;
    this.handlingTax1Rate = props.handlingTax1Rate;
    this.handlingTax2Rate = props.handlingTax2Rate;
    this.handlingCost = props.handlingCost;
    this.subTotal = props.subTotal;
    this.discountTotal = props.discountTotal;
    this.revenueStatus = props.revenueStatus;
    this.recognizedRevenue = props.recognizedRevenue;
    this.deferredRevenue = props.deferredRevenue;
    this.revRecOnRevCommitment = props.revRecOnRevCommitment;
    this.taxTotal = props.taxTotal;
    this.tax2Total = props.tax2Total;
    this.altShippingCost = props.altShippingCost;
    this.altHandlingCost = props.altHandlingCost;
    this.isMultiShipTo = props.isMultiShipTo;
    this.total = props.total;
    this.salesGroup = props.salesGroup;
    this.syncSalesTeams = props.syncSalesTeams;
    this.status = props.status;
    this.giftCert = props.giftCert;
    this.giftCertTotal = props.giftCertTotal;
    this.giftCertApplied = props.giftCertApplied;
    this.giftCertAvailable = props.giftCertAvailable;
    this.tranIsVsoeBundle = props.tranIsVsoeBundle;
    this.vsoeAutoCalc = props.vsoeAutoCalc;
    this.syncPartnerTeams = props.syncPartnerTeams;
    this.salesTeamList = props.salesTeamList;
    this.itemList = props.itemList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.partnersList = props.partnersList;
    this.applyList = props.applyList;
    this.taxDetailsList = props.taxDetailsList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type ChargeSearchAdvancedProps = {
  criteria?: ChargeSearch;
  columns?: ChargeSearchRow;
  savedSearchId?: string;
  savedSearchScriptId?: string;
};

export class ChargeSearchAdvanced extends PlatformCore.SearchRecord {
  criteria?: ChargeSearch;
  columns?: ChargeSearchRow;
  savedSearchId?: string;
  savedSearchScriptId?: string;
  constructor(props: ChargeSearchAdvancedProps) {
    super();
    this.criteria = props.criteria;
    this.columns = props.columns;
    this.savedSearchId = props.savedSearchId;
    this.savedSearchScriptId = props.savedSearchScriptId;
  }
}

export type ReturnAuthorizationItemListProps = {
  item?: ReturnAuthorizationItem[];
  replaceAll?: boolean;
};

export class ReturnAuthorizationItemList {
  item?: ReturnAuthorizationItem[];
  replaceAll?: boolean;
  constructor(props: ReturnAuthorizationItemListProps) {
    this.item = props.item;
    this.replaceAll = props.replaceAll;
  }
}

export type CashRefundItemProps = {
  job?: PlatformCore.RecordRef;
  item?: PlatformCore.RecordRef;
  line?: number;
  orderLine?: number;
  quantity?: number;
  units?: PlatformCore.RecordRef;
  inventoryDetail?: PlatformCommon.InventoryDetail;
  binNumbers?: string;
  serialNumbers?: string;
  description?: string;
  price?: PlatformCore.RecordRef;
  rate?: string;
  amount?: number;
  taxCode?: PlatformCore.RecordRef;
  taxRate1?: string;
  taxRate2?: string;
  tax1Amt?: number;
  grossAmt?: number;
  isTaxable?: boolean;
  options?: PlatformCore.CustomFieldList;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  revRecSchedule?: PlatformCore.RecordRef;
  revRecStartDate?: string;
  revRecEndDate?: string;
  catchUpPeriod?: PlatformCore.RecordRef;
  deferRevRec?: boolean;
  giftCertFrom?: string;
  costEstimateType?: PlatformCommonTypes.ItemCostEstimateType;
  costEstimate?: number;
  taxDetailsReference?: string;
  giftCertRecipientName?: string;
  giftCertRecipientEmail?: string;
  giftCertMessage?: string;
  taxAmount?: number;
  giftCertNumber?: string;
  vsoeSopGroup?: PlatformCommonTypes.VsoeSopGroup;
  vsoeIsEstimate?: boolean;
  vsoePrice?: number;
  vsoeAmount?: number;
  vsoeAllocation?: number;
  vsoeDeferral?: PlatformCommonTypes.VsoeDeferral;
  vsoePermitDiscount?: PlatformCommonTypes.VsoePermitDiscount;
  vsoeDelivered?: boolean;
  chargeType?: PlatformCore.RecordRef;
  chargesList?: PlatformCore.RecordRefList;
  customFieldList?: PlatformCore.CustomFieldList;
};

export class CashRefundItem {
  job?: PlatformCore.RecordRef;
  item?: PlatformCore.RecordRef;
  line?: number;
  orderLine?: number;
  quantity?: number;
  units?: PlatformCore.RecordRef;
  inventoryDetail?: PlatformCommon.InventoryDetail;
  binNumbers?: string;
  serialNumbers?: string;
  description?: string;
  price?: PlatformCore.RecordRef;
  rate?: string;
  amount?: number;
  taxCode?: PlatformCore.RecordRef;
  taxRate1?: string;
  taxRate2?: string;
  tax1Amt?: number;
  grossAmt?: number;
  isTaxable?: boolean;
  options?: PlatformCore.CustomFieldList;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  revRecSchedule?: PlatformCore.RecordRef;
  revRecStartDate?: string;
  revRecEndDate?: string;
  catchUpPeriod?: PlatformCore.RecordRef;
  deferRevRec?: boolean;
  giftCertFrom?: string;
  costEstimateType?: PlatformCommonTypes.ItemCostEstimateType;
  costEstimate?: number;
  taxDetailsReference?: string;
  giftCertRecipientName?: string;
  giftCertRecipientEmail?: string;
  giftCertMessage?: string;
  taxAmount?: number;
  giftCertNumber?: string;
  vsoeSopGroup?: PlatformCommonTypes.VsoeSopGroup;
  vsoeIsEstimate?: boolean;
  vsoePrice?: number;
  vsoeAmount?: number;
  vsoeAllocation?: number;
  vsoeDeferral?: PlatformCommonTypes.VsoeDeferral;
  vsoePermitDiscount?: PlatformCommonTypes.VsoePermitDiscount;
  vsoeDelivered?: boolean;
  chargeType?: PlatformCore.RecordRef;
  chargesList?: PlatformCore.RecordRefList;
  customFieldList?: PlatformCore.CustomFieldList;
  constructor(props: CashRefundItemProps) {
    this.job = props.job;
    this.item = props.item;
    this.line = props.line;
    this.orderLine = props.orderLine;
    this.quantity = props.quantity;
    this.units = props.units;
    this.inventoryDetail = props.inventoryDetail;
    this.binNumbers = props.binNumbers;
    this.serialNumbers = props.serialNumbers;
    this.description = props.description;
    this.price = props.price;
    this.rate = props.rate;
    this.amount = props.amount;
    this.taxCode = props.taxCode;
    this.taxRate1 = props.taxRate1;
    this.taxRate2 = props.taxRate2;
    this.tax1Amt = props.tax1Amt;
    this.grossAmt = props.grossAmt;
    this.isTaxable = props.isTaxable;
    this.options = props.options;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.revRecSchedule = props.revRecSchedule;
    this.revRecStartDate = props.revRecStartDate;
    this.revRecEndDate = props.revRecEndDate;
    this.catchUpPeriod = props.catchUpPeriod;
    this.deferRevRec = props.deferRevRec;
    this.giftCertFrom = props.giftCertFrom;
    this.costEstimateType = props.costEstimateType;
    this.costEstimate = props.costEstimate;
    this.taxDetailsReference = props.taxDetailsReference;
    this.giftCertRecipientName = props.giftCertRecipientName;
    this.giftCertRecipientEmail = props.giftCertRecipientEmail;
    this.giftCertMessage = props.giftCertMessage;
    this.taxAmount = props.taxAmount;
    this.giftCertNumber = props.giftCertNumber;
    this.vsoeSopGroup = props.vsoeSopGroup;
    this.vsoeIsEstimate = props.vsoeIsEstimate;
    this.vsoePrice = props.vsoePrice;
    this.vsoeAmount = props.vsoeAmount;
    this.vsoeAllocation = props.vsoeAllocation;
    this.vsoeDeferral = props.vsoeDeferral;
    this.vsoePermitDiscount = props.vsoePermitDiscount;
    this.vsoeDelivered = props.vsoeDelivered;
    this.chargeType = props.chargeType;
    this.chargesList = props.chargesList;
    this.customFieldList = props.customFieldList;
  }
}

export type CustomerRefundProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  status?: string;
  transactionNumber?: string;
  customer?: PlatformCore.RecordRef;
  customForm?: PlatformCore.RecordRef;
  balance?: number;
  arAcct?: PlatformCore.RecordRef;
  currencyName?: string;
  exchangeRate?: number;
  address?: string;
  total?: number;
  currency?: PlatformCore.RecordRef;
  tranDate?: string;
  voidJournal?: PlatformCore.RecordRef;
  postingPeriod?: PlatformCore.RecordRef;
  memo?: string;
  paymentMethod?: PlatformCore.RecordRef;
  account?: PlatformCore.RecordRef;
  toBePrinted?: boolean;
  tranId?: string;
  debitCardIssueNo?: string;
  creditCardProcessor?: PlatformCore.RecordRef;
  chargeIt?: boolean;
  pnRefNum?: string;
  validFrom?: string;
  subsidiary?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CustomerRefundHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CustomerRefundPaymentOperation;
  dynamicDescriptor?: string;
  creditCard?: PlatformCore.RecordRef;
  ccIsPurchaseCardBin?: boolean;
  ccNumber?: string;
  ccProcessAsPurchaseCard?: boolean;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  applyList?: CustomerRefundApplyList;
  depositList?: CustomerRefundDepositList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class CustomerRefund extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  status?: string;
  transactionNumber?: string;
  customer?: PlatformCore.RecordRef;
  customForm?: PlatformCore.RecordRef;
  balance?: number;
  arAcct?: PlatformCore.RecordRef;
  currencyName?: string;
  exchangeRate?: number;
  address?: string;
  total?: number;
  currency?: PlatformCore.RecordRef;
  tranDate?: string;
  voidJournal?: PlatformCore.RecordRef;
  postingPeriod?: PlatformCore.RecordRef;
  memo?: string;
  paymentMethod?: PlatformCore.RecordRef;
  account?: PlatformCore.RecordRef;
  toBePrinted?: boolean;
  tranId?: string;
  debitCardIssueNo?: string;
  creditCardProcessor?: PlatformCore.RecordRef;
  chargeIt?: boolean;
  pnRefNum?: string;
  validFrom?: string;
  subsidiary?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CustomerRefundHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CustomerRefundPaymentOperation;
  dynamicDescriptor?: string;
  creditCard?: PlatformCore.RecordRef;
  ccIsPurchaseCardBin?: boolean;
  ccNumber?: string;
  ccProcessAsPurchaseCard?: boolean;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  applyList?: CustomerRefundApplyList;
  depositList?: CustomerRefundDepositList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: CustomerRefundProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.status = props.status;
    this.transactionNumber = props.transactionNumber;
    this.customer = props.customer;
    this.customForm = props.customForm;
    this.balance = props.balance;
    this.arAcct = props.arAcct;
    this.currencyName = props.currencyName;
    this.exchangeRate = props.exchangeRate;
    this.address = props.address;
    this.total = props.total;
    this.currency = props.currency;
    this.tranDate = props.tranDate;
    this.voidJournal = props.voidJournal;
    this.postingPeriod = props.postingPeriod;
    this.memo = props.memo;
    this.paymentMethod = props.paymentMethod;
    this.account = props.account;
    this.toBePrinted = props.toBePrinted;
    this.tranId = props.tranId;
    this.debitCardIssueNo = props.debitCardIssueNo;
    this.creditCardProcessor = props.creditCardProcessor;
    this.chargeIt = props.chargeIt;
    this.pnRefNum = props.pnRefNum;
    this.validFrom = props.validFrom;
    this.subsidiary = props.subsidiary;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.paymentOption = props.paymentOption;
    this.inputAuthCode = props.inputAuthCode;
    this.inputReferenceCode = props.inputReferenceCode;
    this.checkNumber = props.checkNumber;
    this.paymentCardCsc = props.paymentCardCsc;
    this.paymentProcessingProfile = props.paymentProcessingProfile;
    this.handlingMode = props.handlingMode;
    this.outputAuthCode = props.outputAuthCode;
    this.outputReferenceCode = props.outputReferenceCode;
    this.paymentOperation = props.paymentOperation;
    this.dynamicDescriptor = props.dynamicDescriptor;
    this.creditCard = props.creditCard;
    this.ccIsPurchaseCardBin = props.ccIsPurchaseCardBin;
    this.ccNumber = props.ccNumber;
    this.ccProcessAsPurchaseCard = props.ccProcessAsPurchaseCard;
    this.ccExpireDate = props.ccExpireDate;
    this.ccName = props.ccName;
    this.ccStreet = props.ccStreet;
    this.ccZipCode = props.ccZipCode;
    this.ccApproved = props.ccApproved;
    this.applyList = props.applyList;
    this.depositList = props.depositList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type ReturnAuthorizationItemProps = {
  job?: PlatformCore.RecordRef;
  item?: PlatformCore.RecordRef;
  orderLine?: number;
  line?: number;
  quantity?: number;
  quantityReceived?: number;
  quantityBilled?: number;
  units?: PlatformCore.RecordRef;
  inventoryDetail?: PlatformCommon.InventoryDetail;
  description?: string;
  serialNumbers?: string;
  price?: PlatformCore.RecordRef;
  rate?: string;
  amount?: number;
  options?: PlatformCore.CustomFieldList;
  revRecTermInMonths?: number;
  deferRevRec?: boolean;
  isClosed?: boolean;
  isDropShipment?: boolean;
  inventoryLocation?: PlatformCore.RecordRef;
  inventorySubsidiary?: PlatformCore.RecordRef;
  catchUpPeriod?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  costEstimateType?: PlatformCommonTypes.ItemCostEstimateType;
  costEstimate?: number;
  taxDetailsReference?: string;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  revRecSchedule?: PlatformCore.RecordRef;
  revRecStartDate?: string;
  revRecEndDate?: string;
  taxCode?: PlatformCore.RecordRef;
  taxRate1?: number;
  taxRate2?: number;
  tax1Amt?: number;
  grossAmt?: number;
  isTaxable?: boolean;
  giftCertFrom?: string;
  giftCertRecipientName?: string;
  giftCertRecipientEmail?: string;
  giftCertMessage?: string;
  giftCertNumber?: string;
  vsoeSopGroup?: PlatformCommonTypes.VsoeSopGroup;
  vsoeIsEstimate?: boolean;
  vsoePrice?: number;
  vsoeAmount?: number;
  altSalesAmt?: number;
  taxAmount?: number;
  vsoeAllocation?: number;
  vsoeDeferral?: PlatformCommonTypes.VsoeDeferral;
  vsoePermitDiscount?: PlatformCommonTypes.VsoePermitDiscount;
  vsoeDelivered?: boolean;
  customFieldList?: PlatformCore.CustomFieldList;
};

export class ReturnAuthorizationItem {
  job?: PlatformCore.RecordRef;
  item?: PlatformCore.RecordRef;
  orderLine?: number;
  line?: number;
  quantity?: number;
  quantityReceived?: number;
  quantityBilled?: number;
  units?: PlatformCore.RecordRef;
  inventoryDetail?: PlatformCommon.InventoryDetail;
  description?: string;
  serialNumbers?: string;
  price?: PlatformCore.RecordRef;
  rate?: string;
  amount?: number;
  options?: PlatformCore.CustomFieldList;
  revRecTermInMonths?: number;
  deferRevRec?: boolean;
  isClosed?: boolean;
  isDropShipment?: boolean;
  inventoryLocation?: PlatformCore.RecordRef;
  inventorySubsidiary?: PlatformCore.RecordRef;
  catchUpPeriod?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  costEstimateType?: PlatformCommonTypes.ItemCostEstimateType;
  costEstimate?: number;
  taxDetailsReference?: string;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  revRecSchedule?: PlatformCore.RecordRef;
  revRecStartDate?: string;
  revRecEndDate?: string;
  taxCode?: PlatformCore.RecordRef;
  taxRate1?: number;
  taxRate2?: number;
  tax1Amt?: number;
  grossAmt?: number;
  isTaxable?: boolean;
  giftCertFrom?: string;
  giftCertRecipientName?: string;
  giftCertRecipientEmail?: string;
  giftCertMessage?: string;
  giftCertNumber?: string;
  vsoeSopGroup?: PlatformCommonTypes.VsoeSopGroup;
  vsoeIsEstimate?: boolean;
  vsoePrice?: number;
  vsoeAmount?: number;
  altSalesAmt?: number;
  taxAmount?: number;
  vsoeAllocation?: number;
  vsoeDeferral?: PlatformCommonTypes.VsoeDeferral;
  vsoePermitDiscount?: PlatformCommonTypes.VsoePermitDiscount;
  vsoeDelivered?: boolean;
  customFieldList?: PlatformCore.CustomFieldList;
  constructor(props: ReturnAuthorizationItemProps) {
    this.job = props.job;
    this.item = props.item;
    this.orderLine = props.orderLine;
    this.line = props.line;
    this.quantity = props.quantity;
    this.quantityReceived = props.quantityReceived;
    this.quantityBilled = props.quantityBilled;
    this.units = props.units;
    this.inventoryDetail = props.inventoryDetail;
    this.description = props.description;
    this.serialNumbers = props.serialNumbers;
    this.price = props.price;
    this.rate = props.rate;
    this.amount = props.amount;
    this.options = props.options;
    this.revRecTermInMonths = props.revRecTermInMonths;
    this.deferRevRec = props.deferRevRec;
    this.isClosed = props.isClosed;
    this.isDropShipment = props.isDropShipment;
    this.inventoryLocation = props.inventoryLocation;
    this.inventorySubsidiary = props.inventorySubsidiary;
    this.catchUpPeriod = props.catchUpPeriod;
    this.department = props.department;
    this.costEstimateType = props.costEstimateType;
    this.costEstimate = props.costEstimate;
    this.taxDetailsReference = props.taxDetailsReference;
    this.clazz = props.clazz;
    this.location = props.location;
    this.revRecSchedule = props.revRecSchedule;
    this.revRecStartDate = props.revRecStartDate;
    this.revRecEndDate = props.revRecEndDate;
    this.taxCode = props.taxCode;
    this.taxRate1 = props.taxRate1;
    this.taxRate2 = props.taxRate2;
    this.tax1Amt = props.tax1Amt;
    this.grossAmt = props.grossAmt;
    this.isTaxable = props.isTaxable;
    this.giftCertFrom = props.giftCertFrom;
    this.giftCertRecipientName = props.giftCertRecipientName;
    this.giftCertRecipientEmail = props.giftCertRecipientEmail;
    this.giftCertMessage = props.giftCertMessage;
    this.giftCertNumber = props.giftCertNumber;
    this.vsoeSopGroup = props.vsoeSopGroup;
    this.vsoeIsEstimate = props.vsoeIsEstimate;
    this.vsoePrice = props.vsoePrice;
    this.vsoeAmount = props.vsoeAmount;
    this.altSalesAmt = props.altSalesAmt;
    this.taxAmount = props.taxAmount;
    this.vsoeAllocation = props.vsoeAllocation;
    this.vsoeDeferral = props.vsoeDeferral;
    this.vsoePermitDiscount = props.vsoePermitDiscount;
    this.vsoeDelivered = props.vsoeDelivered;
    this.customFieldList = props.customFieldList;
  }
}

export type CustomerPaymentDepositProps = {
  apply?: boolean;
  doc?: number;
  line?: number;
  depositDate?: string;
  refNum?: string;
  total?: number;
  remaining?: number;
  currency?: string;
  amount?: number;
};

export class CustomerPaymentDeposit {
  apply?: boolean;
  doc?: number;
  line?: number;
  depositDate?: string;
  refNum?: string;
  total?: number;
  remaining?: number;
  currency?: string;
  amount?: number;
  constructor(props: CustomerPaymentDepositProps) {
    this.apply = props.apply;
    this.doc = props.doc;
    this.line = props.line;
    this.depositDate = props.depositDate;
    this.refNum = props.refNum;
    this.total = props.total;
    this.remaining = props.remaining;
    this.currency = props.currency;
    this.amount = props.amount;
  }
}

export type CustomerPaymentProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  customForm?: PlatformCore.RecordRef;
  arAcct?: PlatformCore.RecordRef;
  customer?: PlatformCore.RecordRef;
  balance?: number;
  pending?: number;
  currency?: PlatformCore.RecordRef;
  payment?: number;
  autoApply?: boolean;
  tranDate?: string;
  tranId?: string;
  postingPeriod?: PlatformCore.RecordRef;
  paymentMethod?: PlatformCore.RecordRef;
  ccIsPurchaseCardBin?: boolean;
  memo?: string;
  ccProcessAsPurchaseCard?: boolean;
  checkNum?: string;
  currencyName?: string;
  exchangeRate?: number;
  creditCard?: PlatformCore.RecordRef;
  chargeIt?: boolean;
  ccNumber?: string;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  authCode?: string;
  ccAvsStreetMatch?: PlatformCommonTypes.AvsMatchCode;
  ccAvsZipMatch?: PlatformCommonTypes.AvsMatchCode;
  isRecurringPayment?: boolean;
  ccSecurityCode?: string;
  ignoreAvs?: boolean;
  ccSecurityCodeMatch?: PlatformCommonTypes.AvsMatchCode;
  threeDStatusCode?: string;
  pnRefNum?: string;
  creditCardProcessor?: PlatformCore.RecordRef;
  debitCardIssueNo?: string;
  validFrom?: string;
  undepFunds?: boolean;
  account?: PlatformCore.RecordRef;
  total?: number;
  subsidiary?: PlatformCore.RecordRef;
  applied?: number;
  unapplied?: number;
  clazz?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CustomerPaymentHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CustomerPaymentPaymentOperation;
  dynamicDescriptor?: string;
  status?: string;
  applyList?: CustomerPaymentApplyList;
  creditList?: CustomerPaymentCreditList;
  depositList?: CustomerPaymentDepositList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class CustomerPayment extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  customForm?: PlatformCore.RecordRef;
  arAcct?: PlatformCore.RecordRef;
  customer?: PlatformCore.RecordRef;
  balance?: number;
  pending?: number;
  currency?: PlatformCore.RecordRef;
  payment?: number;
  autoApply?: boolean;
  tranDate?: string;
  tranId?: string;
  postingPeriod?: PlatformCore.RecordRef;
  paymentMethod?: PlatformCore.RecordRef;
  ccIsPurchaseCardBin?: boolean;
  memo?: string;
  ccProcessAsPurchaseCard?: boolean;
  checkNum?: string;
  currencyName?: string;
  exchangeRate?: number;
  creditCard?: PlatformCore.RecordRef;
  chargeIt?: boolean;
  ccNumber?: string;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  authCode?: string;
  ccAvsStreetMatch?: PlatformCommonTypes.AvsMatchCode;
  ccAvsZipMatch?: PlatformCommonTypes.AvsMatchCode;
  isRecurringPayment?: boolean;
  ccSecurityCode?: string;
  ignoreAvs?: boolean;
  ccSecurityCodeMatch?: PlatformCommonTypes.AvsMatchCode;
  threeDStatusCode?: string;
  pnRefNum?: string;
  creditCardProcessor?: PlatformCore.RecordRef;
  debitCardIssueNo?: string;
  validFrom?: string;
  undepFunds?: boolean;
  account?: PlatformCore.RecordRef;
  total?: number;
  subsidiary?: PlatformCore.RecordRef;
  applied?: number;
  unapplied?: number;
  clazz?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CustomerPaymentHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CustomerPaymentPaymentOperation;
  dynamicDescriptor?: string;
  status?: string;
  applyList?: CustomerPaymentApplyList;
  creditList?: CustomerPaymentCreditList;
  depositList?: CustomerPaymentDepositList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: CustomerPaymentProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.customForm = props.customForm;
    this.arAcct = props.arAcct;
    this.customer = props.customer;
    this.balance = props.balance;
    this.pending = props.pending;
    this.currency = props.currency;
    this.payment = props.payment;
    this.autoApply = props.autoApply;
    this.tranDate = props.tranDate;
    this.tranId = props.tranId;
    this.postingPeriod = props.postingPeriod;
    this.paymentMethod = props.paymentMethod;
    this.ccIsPurchaseCardBin = props.ccIsPurchaseCardBin;
    this.memo = props.memo;
    this.ccProcessAsPurchaseCard = props.ccProcessAsPurchaseCard;
    this.checkNum = props.checkNum;
    this.currencyName = props.currencyName;
    this.exchangeRate = props.exchangeRate;
    this.creditCard = props.creditCard;
    this.chargeIt = props.chargeIt;
    this.ccNumber = props.ccNumber;
    this.ccExpireDate = props.ccExpireDate;
    this.ccName = props.ccName;
    this.ccStreet = props.ccStreet;
    this.ccZipCode = props.ccZipCode;
    this.ccApproved = props.ccApproved;
    this.authCode = props.authCode;
    this.ccAvsStreetMatch = props.ccAvsStreetMatch;
    this.ccAvsZipMatch = props.ccAvsZipMatch;
    this.isRecurringPayment = props.isRecurringPayment;
    this.ccSecurityCode = props.ccSecurityCode;
    this.ignoreAvs = props.ignoreAvs;
    this.ccSecurityCodeMatch = props.ccSecurityCodeMatch;
    this.threeDStatusCode = props.threeDStatusCode;
    this.pnRefNum = props.pnRefNum;
    this.creditCardProcessor = props.creditCardProcessor;
    this.debitCardIssueNo = props.debitCardIssueNo;
    this.validFrom = props.validFrom;
    this.undepFunds = props.undepFunds;
    this.account = props.account;
    this.total = props.total;
    this.subsidiary = props.subsidiary;
    this.applied = props.applied;
    this.unapplied = props.unapplied;
    this.clazz = props.clazz;
    this.department = props.department;
    this.location = props.location;
    this.paymentOption = props.paymentOption;
    this.inputAuthCode = props.inputAuthCode;
    this.inputReferenceCode = props.inputReferenceCode;
    this.checkNumber = props.checkNumber;
    this.paymentCardCsc = props.paymentCardCsc;
    this.paymentProcessingProfile = props.paymentProcessingProfile;
    this.handlingMode = props.handlingMode;
    this.outputAuthCode = props.outputAuthCode;
    this.outputReferenceCode = props.outputReferenceCode;
    this.paymentOperation = props.paymentOperation;
    this.dynamicDescriptor = props.dynamicDescriptor;
    this.status = props.status;
    this.applyList = props.applyList;
    this.creditList = props.creditList;
    this.depositList = props.depositList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type CreditMemoApplyListProps = {
  apply?: CreditMemoApply[];
  replaceAll?: boolean;
};

export class CreditMemoApplyList {
  apply?: CreditMemoApply[];
  replaceAll?: boolean;
  constructor(props: CreditMemoApplyListProps) {
    this.apply = props.apply;
    this.replaceAll = props.replaceAll;
  }
}

export type CashRefundSalesTeamProps = {
  employee?: PlatformCore.RecordRef;
  salesRole?: PlatformCore.RecordRef;
  isPrimary?: boolean;
  contribution?: number;
};

export class CashRefundSalesTeam {
  employee?: PlatformCore.RecordRef;
  salesRole?: PlatformCore.RecordRef;
  isPrimary?: boolean;
  contribution?: number;
  constructor(props: CashRefundSalesTeamProps) {
    this.employee = props.employee;
    this.salesRole = props.salesRole;
    this.isPrimary = props.isPrimary;
    this.contribution = props.contribution;
  }
}

export type CustomerPaymentCreditProps = {
  apply?: boolean;
  doc?: number;
  line?: number;
  creditDate?: string;
  type?: string;
  refNum?: string;
  appliedTo?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
};

export class CustomerPaymentCredit {
  apply?: boolean;
  doc?: number;
  line?: number;
  creditDate?: string;
  type?: string;
  refNum?: string;
  appliedTo?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
  constructor(props: CustomerPaymentCreditProps) {
    this.apply = props.apply;
    this.doc = props.doc;
    this.line = props.line;
    this.creditDate = props.creditDate;
    this.type = props.type;
    this.refNum = props.refNum;
    this.appliedTo = props.appliedTo;
    this.total = props.total;
    this.due = props.due;
    this.currency = props.currency;
    this.amount = props.amount;
  }
}

export type CustomerDepositProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  status?: string;
  customer?: PlatformCore.RecordRef;
  salesOrder?: PlatformCore.RecordRef;
  customForm?: PlatformCore.RecordRef;
  payment?: number;
  currency?: PlatformCore.RecordRef;
  tranDate?: string;
  postingPeriod?: PlatformCore.RecordRef;
  paymentMethod?: PlatformCore.RecordRef;
  ccIsPurchaseCardBin?: boolean;
  memo?: string;
  ccProcessAsPurchaseCard?: boolean;
  currencyName?: string;
  exchangeRate?: number;
  checkNum?: string;
  creditCardProcessor?: PlatformCore.RecordRef;
  creditCard?: PlatformCore.RecordRef;
  ccSecurityCode?: string;
  ccNumber?: string;
  subsidiary?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CustomerDepositHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CustomerDepositPaymentOperation;
  dynamicDescriptor?: string;
  ccExpireDate?: string;
  debitCardIssueNo?: string;
  validFrom?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  chargeIt?: boolean;
  ccApproved?: boolean;
  pnRefNum?: string;
  authCode?: string;
  ccAvsStreetMatch?: PlatformCommonTypes.AvsMatchCode;
  softDescriptor?: string;
  ccAvsZipMatch?: PlatformCommonTypes.AvsMatchCode;
  isRecurringPayment?: boolean;
  ccSecurityCodeMatch?: PlatformCommonTypes.AvsMatchCode;
  threeDStatusCode?: string;
  ignoreAvs?: boolean;
  account?: PlatformCore.RecordRef;
  undepFunds?: boolean;
  tranId?: string;
  applyList?: CustomerDepositApplyList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class CustomerDeposit extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  status?: string;
  customer?: PlatformCore.RecordRef;
  salesOrder?: PlatformCore.RecordRef;
  customForm?: PlatformCore.RecordRef;
  payment?: number;
  currency?: PlatformCore.RecordRef;
  tranDate?: string;
  postingPeriod?: PlatformCore.RecordRef;
  paymentMethod?: PlatformCore.RecordRef;
  ccIsPurchaseCardBin?: boolean;
  memo?: string;
  ccProcessAsPurchaseCard?: boolean;
  currencyName?: string;
  exchangeRate?: number;
  checkNum?: string;
  creditCardProcessor?: PlatformCore.RecordRef;
  creditCard?: PlatformCore.RecordRef;
  ccSecurityCode?: string;
  ccNumber?: string;
  subsidiary?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CustomerDepositHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CustomerDepositPaymentOperation;
  dynamicDescriptor?: string;
  ccExpireDate?: string;
  debitCardIssueNo?: string;
  validFrom?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  chargeIt?: boolean;
  ccApproved?: boolean;
  pnRefNum?: string;
  authCode?: string;
  ccAvsStreetMatch?: PlatformCommonTypes.AvsMatchCode;
  softDescriptor?: string;
  ccAvsZipMatch?: PlatformCommonTypes.AvsMatchCode;
  isRecurringPayment?: boolean;
  ccSecurityCodeMatch?: PlatformCommonTypes.AvsMatchCode;
  threeDStatusCode?: string;
  ignoreAvs?: boolean;
  account?: PlatformCore.RecordRef;
  undepFunds?: boolean;
  tranId?: string;
  applyList?: CustomerDepositApplyList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: CustomerDepositProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.status = props.status;
    this.customer = props.customer;
    this.salesOrder = props.salesOrder;
    this.customForm = props.customForm;
    this.payment = props.payment;
    this.currency = props.currency;
    this.tranDate = props.tranDate;
    this.postingPeriod = props.postingPeriod;
    this.paymentMethod = props.paymentMethod;
    this.ccIsPurchaseCardBin = props.ccIsPurchaseCardBin;
    this.memo = props.memo;
    this.ccProcessAsPurchaseCard = props.ccProcessAsPurchaseCard;
    this.currencyName = props.currencyName;
    this.exchangeRate = props.exchangeRate;
    this.checkNum = props.checkNum;
    this.creditCardProcessor = props.creditCardProcessor;
    this.creditCard = props.creditCard;
    this.ccSecurityCode = props.ccSecurityCode;
    this.ccNumber = props.ccNumber;
    this.subsidiary = props.subsidiary;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.paymentOption = props.paymentOption;
    this.inputAuthCode = props.inputAuthCode;
    this.inputReferenceCode = props.inputReferenceCode;
    this.checkNumber = props.checkNumber;
    this.paymentCardCsc = props.paymentCardCsc;
    this.paymentProcessingProfile = props.paymentProcessingProfile;
    this.handlingMode = props.handlingMode;
    this.outputAuthCode = props.outputAuthCode;
    this.outputReferenceCode = props.outputReferenceCode;
    this.paymentOperation = props.paymentOperation;
    this.dynamicDescriptor = props.dynamicDescriptor;
    this.ccExpireDate = props.ccExpireDate;
    this.debitCardIssueNo = props.debitCardIssueNo;
    this.validFrom = props.validFrom;
    this.ccName = props.ccName;
    this.ccStreet = props.ccStreet;
    this.ccZipCode = props.ccZipCode;
    this.chargeIt = props.chargeIt;
    this.ccApproved = props.ccApproved;
    this.pnRefNum = props.pnRefNum;
    this.authCode = props.authCode;
    this.ccAvsStreetMatch = props.ccAvsStreetMatch;
    this.softDescriptor = props.softDescriptor;
    this.ccAvsZipMatch = props.ccAvsZipMatch;
    this.isRecurringPayment = props.isRecurringPayment;
    this.ccSecurityCodeMatch = props.ccSecurityCodeMatch;
    this.threeDStatusCode = props.threeDStatusCode;
    this.ignoreAvs = props.ignoreAvs;
    this.account = props.account;
    this.undepFunds = props.undepFunds;
    this.tranId = props.tranId;
    this.applyList = props.applyList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type CustomerDepositApplyListProps = {
  customerDepositApply?: CustomerDepositApply[];
  replaceAll?: boolean;
};

export class CustomerDepositApplyList {
  customerDepositApply?: CustomerDepositApply[];
  replaceAll?: boolean;
  constructor(props: CustomerDepositApplyListProps) {
    this.customerDepositApply = props.customerDepositApply;
    this.replaceAll = props.replaceAll;
  }
}

export type DepositApplicationApplyListProps = {
  apply?: DepositApplicationApply[];
  replaceAll?: boolean;
};

export class DepositApplicationApplyList {
  apply?: DepositApplicationApply[];
  replaceAll?: boolean;
  constructor(props: DepositApplicationApplyListProps) {
    this.apply = props.apply;
    this.replaceAll = props.replaceAll;
  }
}

export type CustomerPaymentApplyProps = {
  apply?: boolean;
  doc?: number;
  line?: number;
  applyDate?: string;
  job?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  discDate?: string;
  discAmt?: number;
  disc?: number;
  amount?: number;
};

export class CustomerPaymentApply {
  apply?: boolean;
  doc?: number;
  line?: number;
  applyDate?: string;
  job?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  discDate?: string;
  discAmt?: number;
  disc?: number;
  amount?: number;
  constructor(props: CustomerPaymentApplyProps) {
    this.apply = props.apply;
    this.doc = props.doc;
    this.line = props.line;
    this.applyDate = props.applyDate;
    this.job = props.job;
    this.type = props.type;
    this.refNum = props.refNum;
    this.total = props.total;
    this.due = props.due;
    this.currency = props.currency;
    this.discDate = props.discDate;
    this.discAmt = props.discAmt;
    this.disc = props.disc;
    this.amount = props.amount;
  }
}

export type ReturnAuthorizationPartnersListProps = {
  partners?: PlatformCommon.Partners[];
  replaceAll?: boolean;
};

export class ReturnAuthorizationPartnersList {
  partners?: PlatformCommon.Partners[];
  replaceAll?: boolean;
  constructor(props: ReturnAuthorizationPartnersListProps) {
    this.partners = props.partners;
    this.replaceAll = props.replaceAll;
  }
}

export type CashRefundSalesTeamListProps = {
  salesTeam?: CashRefundSalesTeam[];
  replaceAll?: boolean;
};

export class CashRefundSalesTeamList {
  salesTeam?: CashRefundSalesTeam[];
  replaceAll?: boolean;
  constructor(props: CashRefundSalesTeamListProps) {
    this.salesTeam = props.salesTeam;
    this.replaceAll = props.replaceAll;
  }
}

export type CreditMemoItemProps = {
  job?: PlatformCore.RecordRef;
  item?: PlatformCore.RecordRef;
  orderLine?: number;
  line?: number;
  quantity?: number;
  description?: string;
  binNumbers?: string;
  price?: PlatformCore.RecordRef;
  rate?: string;
  amount?: number;
  isTaxable?: boolean;
  options?: PlatformCore.CustomFieldList;
  shipAddress?: PlatformCore.RecordRef;
  shipCarrier?: PlatformCommonTypes.ShippingCarrier;
  shipMethod?: PlatformCore.RecordRef;
  taxCode?: PlatformCore.RecordRef;
  taxRate1?: number;
  taxRate2?: number;
  tax1Amt?: number;
  grossAmt?: number;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  costEstimateType?: PlatformCommonTypes.ItemCostEstimateType;
  costEstimate?: number;
  taxDetailsReference?: string;
  revRecSchedule?: PlatformCore.RecordRef;
  revRecStartDate?: string;
  revRecTermInMonths?: number;
  revRecEndDate?: string;
  units?: PlatformCore.RecordRef;
  inventoryDetail?: PlatformCommon.InventoryDetail;
  serialNumbers?: string;
  deferRevRec?: boolean;
  giftCertFrom?: string;
  giftCertRecipientName?: string;
  giftCertRecipientEmail?: string;
  giftCertMessage?: string;
  taxAmount?: number;
  giftCertNumber?: string;
  vsoeSopGroup?: PlatformCommonTypes.VsoeSopGroup;
  vsoeIsEstimate?: boolean;
  vsoePrice?: number;
  vsoeAmount?: number;
  vsoeAllocation?: number;
  vsoeDeferral?: PlatformCommonTypes.VsoeDeferral;
  vsoePermitDiscount?: PlatformCommonTypes.VsoePermitDiscount;
  vsoeDelivered?: boolean;
  catchUpPeriod?: PlatformCore.RecordRef;
  chargeType?: PlatformCore.RecordRef;
  subscriptionLine?: PlatformCore.RecordRef;
  chargesList?: PlatformCore.RecordRefList;
  customFieldList?: PlatformCore.CustomFieldList;
};

export class CreditMemoItem {
  job?: PlatformCore.RecordRef;
  item?: PlatformCore.RecordRef;
  orderLine?: number;
  line?: number;
  quantity?: number;
  description?: string;
  binNumbers?: string;
  price?: PlatformCore.RecordRef;
  rate?: string;
  amount?: number;
  isTaxable?: boolean;
  options?: PlatformCore.CustomFieldList;
  shipAddress?: PlatformCore.RecordRef;
  shipCarrier?: PlatformCommonTypes.ShippingCarrier;
  shipMethod?: PlatformCore.RecordRef;
  taxCode?: PlatformCore.RecordRef;
  taxRate1?: number;
  taxRate2?: number;
  tax1Amt?: number;
  grossAmt?: number;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  costEstimateType?: PlatformCommonTypes.ItemCostEstimateType;
  costEstimate?: number;
  taxDetailsReference?: string;
  revRecSchedule?: PlatformCore.RecordRef;
  revRecStartDate?: string;
  revRecTermInMonths?: number;
  revRecEndDate?: string;
  units?: PlatformCore.RecordRef;
  inventoryDetail?: PlatformCommon.InventoryDetail;
  serialNumbers?: string;
  deferRevRec?: boolean;
  giftCertFrom?: string;
  giftCertRecipientName?: string;
  giftCertRecipientEmail?: string;
  giftCertMessage?: string;
  taxAmount?: number;
  giftCertNumber?: string;
  vsoeSopGroup?: PlatformCommonTypes.VsoeSopGroup;
  vsoeIsEstimate?: boolean;
  vsoePrice?: number;
  vsoeAmount?: number;
  vsoeAllocation?: number;
  vsoeDeferral?: PlatformCommonTypes.VsoeDeferral;
  vsoePermitDiscount?: PlatformCommonTypes.VsoePermitDiscount;
  vsoeDelivered?: boolean;
  catchUpPeriod?: PlatformCore.RecordRef;
  chargeType?: PlatformCore.RecordRef;
  subscriptionLine?: PlatformCore.RecordRef;
  chargesList?: PlatformCore.RecordRefList;
  customFieldList?: PlatformCore.CustomFieldList;
  constructor(props: CreditMemoItemProps) {
    this.job = props.job;
    this.item = props.item;
    this.orderLine = props.orderLine;
    this.line = props.line;
    this.quantity = props.quantity;
    this.description = props.description;
    this.binNumbers = props.binNumbers;
    this.price = props.price;
    this.rate = props.rate;
    this.amount = props.amount;
    this.isTaxable = props.isTaxable;
    this.options = props.options;
    this.shipAddress = props.shipAddress;
    this.shipCarrier = props.shipCarrier;
    this.shipMethod = props.shipMethod;
    this.taxCode = props.taxCode;
    this.taxRate1 = props.taxRate1;
    this.taxRate2 = props.taxRate2;
    this.tax1Amt = props.tax1Amt;
    this.grossAmt = props.grossAmt;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.costEstimateType = props.costEstimateType;
    this.costEstimate = props.costEstimate;
    this.taxDetailsReference = props.taxDetailsReference;
    this.revRecSchedule = props.revRecSchedule;
    this.revRecStartDate = props.revRecStartDate;
    this.revRecTermInMonths = props.revRecTermInMonths;
    this.revRecEndDate = props.revRecEndDate;
    this.units = props.units;
    this.inventoryDetail = props.inventoryDetail;
    this.serialNumbers = props.serialNumbers;
    this.deferRevRec = props.deferRevRec;
    this.giftCertFrom = props.giftCertFrom;
    this.giftCertRecipientName = props.giftCertRecipientName;
    this.giftCertRecipientEmail = props.giftCertRecipientEmail;
    this.giftCertMessage = props.giftCertMessage;
    this.taxAmount = props.taxAmount;
    this.giftCertNumber = props.giftCertNumber;
    this.vsoeSopGroup = props.vsoeSopGroup;
    this.vsoeIsEstimate = props.vsoeIsEstimate;
    this.vsoePrice = props.vsoePrice;
    this.vsoeAmount = props.vsoeAmount;
    this.vsoeAllocation = props.vsoeAllocation;
    this.vsoeDeferral = props.vsoeDeferral;
    this.vsoePermitDiscount = props.vsoePermitDiscount;
    this.vsoeDelivered = props.vsoeDelivered;
    this.catchUpPeriod = props.catchUpPeriod;
    this.chargeType = props.chargeType;
    this.subscriptionLine = props.subscriptionLine;
    this.chargesList = props.chargesList;
    this.customFieldList = props.customFieldList;
  }
}

export type CashRefundItemListProps = {
  item?: CashRefundItem[];
  replaceAll?: boolean;
};

export class CashRefundItemList {
  item?: CashRefundItem[];
  replaceAll?: boolean;
  constructor(props: CashRefundItemListProps) {
    this.item = props.item;
    this.replaceAll = props.replaceAll;
  }
}

export type CashRefundPartnersListProps = {
  partners?: PlatformCommon.Partners[];
  replaceAll?: boolean;
};

export class CashRefundPartnersList {
  partners?: PlatformCommon.Partners[];
  replaceAll?: boolean;
  constructor(props: CashRefundPartnersListProps) {
    this.partners = props.partners;
    this.replaceAll = props.replaceAll;
  }
}

export type CreditMemoSalesTeamProps = {
  employee?: PlatformCore.RecordRef;
  salesRole?: PlatformCore.RecordRef;
  isPrimary?: boolean;
  contribution?: number;
};

export class CreditMemoSalesTeam {
  employee?: PlatformCore.RecordRef;
  salesRole?: PlatformCore.RecordRef;
  isPrimary?: boolean;
  contribution?: number;
  constructor(props: CreditMemoSalesTeamProps) {
    this.employee = props.employee;
    this.salesRole = props.salesRole;
    this.isPrimary = props.isPrimary;
    this.contribution = props.contribution;
  }
}

export type CashRefundProps = {
  createdDate?: string;
  lastModifiedDate?: string;
  nexus?: PlatformCore.RecordRef;
  subsidiaryTaxRegNum?: PlatformCore.RecordRef;
  taxRegOverride?: boolean;
  taxDetailsOverride?: boolean;
  customForm?: PlatformCore.RecordRef;
  entity?: PlatformCore.RecordRef;
  vatRegNum?: string;
  tranDate?: string;
  tranId?: string;
  entityTaxRegNum?: PlatformCore.RecordRef;
  taxPointDate?: string;
  source?: string;
  createdFrom?: PlatformCore.RecordRef;
  postingPeriod?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  leadSource?: PlatformCore.RecordRef;
  subsidiary?: PlatformCore.RecordRef;
  salesRep?: PlatformCore.RecordRef;
  partner?: PlatformCore.RecordRef;
  contribPct?: string;
  otherRefNum?: string;
  memo?: string;
  salesEffectiveDate?: string;
  refundCheck?: boolean;
  toPrint2?: boolean;
  excludeCommission?: boolean;
  totalCostEstimate?: number;
  estGrossProfit?: number;
  estGrossProfitPercent?: number;
  account?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  exchangeRate?: number;
  currencyName?: string;
  promoCode?: PlatformCore.RecordRef;
  discountItem?: PlatformCore.RecordRef;
  discountRate?: string;
  isTaxable?: boolean;
  taxItem?: PlatformCore.RecordRef;
  taxRate?: number;
  toBePrinted?: boolean;
  toBeEmailed?: boolean;
  email?: string;
  toBeFaxed?: boolean;
  fax?: string;
  messageSel?: PlatformCore.RecordRef;
  message?: string;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CashRefundHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CashRefundPaymentOperation;
  dynamicDescriptor?: string;
  billingAddress?: PlatformCommon.Address;
  billAddressList?: PlatformCore.RecordRef;
  shipMethod?: PlatformCore.RecordRef;
  shippingTaxCode?: PlatformCore.RecordRef;
  shippingTax1Rate?: number;
  shippingTax2Rate?: string;
  shippingCost?: number;
  handlingTaxCode?: PlatformCore.RecordRef;
  handlingTax1Rate?: number;
  handlingTax2Rate?: string;
  handlingCost?: number;
  salesGroup?: PlatformCore.RecordRef;
  syncSalesTeams?: boolean;
  paymentMethod?: PlatformCore.RecordRef;
  revenueStatus?: PlatformCommonTypes.RevenueStatus;
  recognizedRevenue?: number;
  deferredRevenue?: number;
  revRecOnRevCommitment?: boolean;
  creditCard?: PlatformCore.RecordRef;
  chargeIt?: boolean;
  ccNumber?: string;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  creditCardProcessor?: PlatformCore.RecordRef;
  debitCardIssueNo?: string;
  pnRefNum?: string;
  validFrom?: string;
  payPalTranId?: string;
  subTotal?: number;
  ccIsPurchaseCardBin?: boolean;
  discountTotal?: number;
  ccProcessAsPurchaseCard?: boolean;
  taxTotal?: number;
  tax2Total?: number;
  altShippingCost?: number;
  payPalStatus?: string;
  altHandlingCost?: number;
  total?: number;
  payPalAuthId?: string;
  status?: string;
  job?: PlatformCore.RecordRef;
  giftCert?: PlatformCore.RecordRef;
  giftCertTotal?: number;
  giftCertApplied?: number;
  giftCertAvailable?: number;
  tranIsVsoeBundle?: boolean;
  payPalProcess?: boolean;
  vsoeAutoCalc?: boolean;
  syncPartnerTeams?: boolean;
  itemList?: CashRefundItemList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  salesTeamList?: CashRefundSalesTeamList;
  partnersList?: CashRefundPartnersList;
  taxDetailsList?: PlatformCommon.TaxDetailsList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class CashRefund extends PlatformCore.Record {
  createdDate?: string;
  lastModifiedDate?: string;
  nexus?: PlatformCore.RecordRef;
  subsidiaryTaxRegNum?: PlatformCore.RecordRef;
  taxRegOverride?: boolean;
  taxDetailsOverride?: boolean;
  customForm?: PlatformCore.RecordRef;
  entity?: PlatformCore.RecordRef;
  vatRegNum?: string;
  tranDate?: string;
  tranId?: string;
  entityTaxRegNum?: PlatformCore.RecordRef;
  taxPointDate?: string;
  source?: string;
  createdFrom?: PlatformCore.RecordRef;
  postingPeriod?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  leadSource?: PlatformCore.RecordRef;
  subsidiary?: PlatformCore.RecordRef;
  salesRep?: PlatformCore.RecordRef;
  partner?: PlatformCore.RecordRef;
  contribPct?: string;
  otherRefNum?: string;
  memo?: string;
  salesEffectiveDate?: string;
  refundCheck?: boolean;
  toPrint2?: boolean;
  excludeCommission?: boolean;
  totalCostEstimate?: number;
  estGrossProfit?: number;
  estGrossProfitPercent?: number;
  account?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  exchangeRate?: number;
  currencyName?: string;
  promoCode?: PlatformCore.RecordRef;
  discountItem?: PlatformCore.RecordRef;
  discountRate?: string;
  isTaxable?: boolean;
  taxItem?: PlatformCore.RecordRef;
  taxRate?: number;
  toBePrinted?: boolean;
  toBeEmailed?: boolean;
  email?: string;
  toBeFaxed?: boolean;
  fax?: string;
  messageSel?: PlatformCore.RecordRef;
  message?: string;
  paymentOption?: PlatformCore.RecordRef;
  inputAuthCode?: string;
  inputReferenceCode?: string;
  checkNumber?: string;
  paymentCardCsc?: string;
  paymentProcessingProfile?: PlatformCore.RecordRef;
  handlingMode?: TransactionsCustomersTypes.CashRefundHandlingMode;
  outputAuthCode?: string;
  outputReferenceCode?: string;
  paymentOperation?: TransactionsCustomersTypes.CashRefundPaymentOperation;
  dynamicDescriptor?: string;
  billingAddress?: PlatformCommon.Address;
  billAddressList?: PlatformCore.RecordRef;
  shipMethod?: PlatformCore.RecordRef;
  shippingTaxCode?: PlatformCore.RecordRef;
  shippingTax1Rate?: number;
  shippingTax2Rate?: string;
  shippingCost?: number;
  handlingTaxCode?: PlatformCore.RecordRef;
  handlingTax1Rate?: number;
  handlingTax2Rate?: string;
  handlingCost?: number;
  salesGroup?: PlatformCore.RecordRef;
  syncSalesTeams?: boolean;
  paymentMethod?: PlatformCore.RecordRef;
  revenueStatus?: PlatformCommonTypes.RevenueStatus;
  recognizedRevenue?: number;
  deferredRevenue?: number;
  revRecOnRevCommitment?: boolean;
  creditCard?: PlatformCore.RecordRef;
  chargeIt?: boolean;
  ccNumber?: string;
  ccExpireDate?: string;
  ccName?: string;
  ccStreet?: string;
  ccZipCode?: string;
  ccApproved?: boolean;
  creditCardProcessor?: PlatformCore.RecordRef;
  debitCardIssueNo?: string;
  pnRefNum?: string;
  validFrom?: string;
  payPalTranId?: string;
  subTotal?: number;
  ccIsPurchaseCardBin?: boolean;
  discountTotal?: number;
  ccProcessAsPurchaseCard?: boolean;
  taxTotal?: number;
  tax2Total?: number;
  altShippingCost?: number;
  payPalStatus?: string;
  altHandlingCost?: number;
  total?: number;
  payPalAuthId?: string;
  status?: string;
  job?: PlatformCore.RecordRef;
  giftCert?: PlatformCore.RecordRef;
  giftCertTotal?: number;
  giftCertApplied?: number;
  giftCertAvailable?: number;
  tranIsVsoeBundle?: boolean;
  payPalProcess?: boolean;
  vsoeAutoCalc?: boolean;
  syncPartnerTeams?: boolean;
  itemList?: CashRefundItemList;
  accountingBookDetailList?: PlatformCommon.AccountingBookDetailList;
  salesTeamList?: CashRefundSalesTeamList;
  partnersList?: CashRefundPartnersList;
  taxDetailsList?: PlatformCommon.TaxDetailsList;
  customFieldList?: PlatformCore.CustomFieldList;
  internalId?: string;
  externalId?: string;
  constructor(props: CashRefundProps) {
    super(props);
    this.createdDate = props.createdDate;
    this.lastModifiedDate = props.lastModifiedDate;
    this.nexus = props.nexus;
    this.subsidiaryTaxRegNum = props.subsidiaryTaxRegNum;
    this.taxRegOverride = props.taxRegOverride;
    this.taxDetailsOverride = props.taxDetailsOverride;
    this.customForm = props.customForm;
    this.entity = props.entity;
    this.vatRegNum = props.vatRegNum;
    this.tranDate = props.tranDate;
    this.tranId = props.tranId;
    this.entityTaxRegNum = props.entityTaxRegNum;
    this.taxPointDate = props.taxPointDate;
    this.source = props.source;
    this.createdFrom = props.createdFrom;
    this.postingPeriod = props.postingPeriod;
    this.department = props.department;
    this.clazz = props.clazz;
    this.location = props.location;
    this.leadSource = props.leadSource;
    this.subsidiary = props.subsidiary;
    this.salesRep = props.salesRep;
    this.partner = props.partner;
    this.contribPct = props.contribPct;
    this.otherRefNum = props.otherRefNum;
    this.memo = props.memo;
    this.salesEffectiveDate = props.salesEffectiveDate;
    this.refundCheck = props.refundCheck;
    this.toPrint2 = props.toPrint2;
    this.excludeCommission = props.excludeCommission;
    this.totalCostEstimate = props.totalCostEstimate;
    this.estGrossProfit = props.estGrossProfit;
    this.estGrossProfitPercent = props.estGrossProfitPercent;
    this.account = props.account;
    this.currency = props.currency;
    this.exchangeRate = props.exchangeRate;
    this.currencyName = props.currencyName;
    this.promoCode = props.promoCode;
    this.discountItem = props.discountItem;
    this.discountRate = props.discountRate;
    this.isTaxable = props.isTaxable;
    this.taxItem = props.taxItem;
    this.taxRate = props.taxRate;
    this.toBePrinted = props.toBePrinted;
    this.toBeEmailed = props.toBeEmailed;
    this.email = props.email;
    this.toBeFaxed = props.toBeFaxed;
    this.fax = props.fax;
    this.messageSel = props.messageSel;
    this.message = props.message;
    this.paymentOption = props.paymentOption;
    this.inputAuthCode = props.inputAuthCode;
    this.inputReferenceCode = props.inputReferenceCode;
    this.checkNumber = props.checkNumber;
    this.paymentCardCsc = props.paymentCardCsc;
    this.paymentProcessingProfile = props.paymentProcessingProfile;
    this.handlingMode = props.handlingMode;
    this.outputAuthCode = props.outputAuthCode;
    this.outputReferenceCode = props.outputReferenceCode;
    this.paymentOperation = props.paymentOperation;
    this.dynamicDescriptor = props.dynamicDescriptor;
    this.billingAddress = props.billingAddress;
    this.billAddressList = props.billAddressList;
    this.shipMethod = props.shipMethod;
    this.shippingTaxCode = props.shippingTaxCode;
    this.shippingTax1Rate = props.shippingTax1Rate;
    this.shippingTax2Rate = props.shippingTax2Rate;
    this.shippingCost = props.shippingCost;
    this.handlingTaxCode = props.handlingTaxCode;
    this.handlingTax1Rate = props.handlingTax1Rate;
    this.handlingTax2Rate = props.handlingTax2Rate;
    this.handlingCost = props.handlingCost;
    this.salesGroup = props.salesGroup;
    this.syncSalesTeams = props.syncSalesTeams;
    this.paymentMethod = props.paymentMethod;
    this.revenueStatus = props.revenueStatus;
    this.recognizedRevenue = props.recognizedRevenue;
    this.deferredRevenue = props.deferredRevenue;
    this.revRecOnRevCommitment = props.revRecOnRevCommitment;
    this.creditCard = props.creditCard;
    this.chargeIt = props.chargeIt;
    this.ccNumber = props.ccNumber;
    this.ccExpireDate = props.ccExpireDate;
    this.ccName = props.ccName;
    this.ccStreet = props.ccStreet;
    this.ccZipCode = props.ccZipCode;
    this.ccApproved = props.ccApproved;
    this.creditCardProcessor = props.creditCardProcessor;
    this.debitCardIssueNo = props.debitCardIssueNo;
    this.pnRefNum = props.pnRefNum;
    this.validFrom = props.validFrom;
    this.payPalTranId = props.payPalTranId;
    this.subTotal = props.subTotal;
    this.ccIsPurchaseCardBin = props.ccIsPurchaseCardBin;
    this.discountTotal = props.discountTotal;
    this.ccProcessAsPurchaseCard = props.ccProcessAsPurchaseCard;
    this.taxTotal = props.taxTotal;
    this.tax2Total = props.tax2Total;
    this.altShippingCost = props.altShippingCost;
    this.payPalStatus = props.payPalStatus;
    this.altHandlingCost = props.altHandlingCost;
    this.total = props.total;
    this.payPalAuthId = props.payPalAuthId;
    this.status = props.status;
    this.job = props.job;
    this.giftCert = props.giftCert;
    this.giftCertTotal = props.giftCertTotal;
    this.giftCertApplied = props.giftCertApplied;
    this.giftCertAvailable = props.giftCertAvailable;
    this.tranIsVsoeBundle = props.tranIsVsoeBundle;
    this.payPalProcess = props.payPalProcess;
    this.vsoeAutoCalc = props.vsoeAutoCalc;
    this.syncPartnerTeams = props.syncPartnerTeams;
    this.itemList = props.itemList;
    this.accountingBookDetailList = props.accountingBookDetailList;
    this.salesTeamList = props.salesTeamList;
    this.partnersList = props.partnersList;
    this.taxDetailsList = props.taxDetailsList;
    this.customFieldList = props.customFieldList;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type CustomerDepositApplyProps = {
  doc?: number;
  line?: number;
  apply?: boolean;
  applyDate?: string;
  type?: string;
  refNum?: string;
  total?: number;
  amount?: number;
  job?: string;
};

export class CustomerDepositApply {
  doc?: number;
  line?: number;
  apply?: boolean;
  applyDate?: string;
  type?: string;
  refNum?: string;
  total?: number;
  amount?: number;
  job?: string;
  constructor(props: CustomerDepositApplyProps) {
    this.doc = props.doc;
    this.line = props.line;
    this.apply = props.apply;
    this.applyDate = props.applyDate;
    this.type = props.type;
    this.refNum = props.refNum;
    this.total = props.total;
    this.amount = props.amount;
    this.job = props.job;
  }
}

export type ChargeSearchRowProps = {
  basic?: PlatformCommon.ChargeSearchRowBasic;
  billingAccountJoin?: PlatformCommon.BillingAccountSearchRowBasic;
  billingScheduleJoin?: PlatformCommon.BillingScheduleSearchRowBasic;
  chargeEmployeeJoin?: PlatformCommon.EmployeeSearchRowBasic;
  customerJoin?: PlatformCommon.CustomerSearchRowBasic;
  invoiceJoin?: PlatformCommon.TransactionSearchRowBasic;
  itemJoin?: PlatformCommon.ItemSearchRowBasic;
  jobJoin?: PlatformCommon.JobSearchRowBasic;
  salesOrderJoin?: PlatformCommon.TransactionSearchRowBasic;
  timeJoin?: PlatformCommon.TimeBillSearchRowBasic;
  transactionJoin?: PlatformCommon.TransactionSearchRowBasic;
  usageJoin?: PlatformCommon.UsageSearchRowBasic;
  userJoin?: PlatformCommon.EmployeeSearchRowBasic;
  customSearchJoin?: PlatformCommon.CustomSearchRowBasic[];
};

export class ChargeSearchRow extends PlatformCore.SearchRow {
  basic?: PlatformCommon.ChargeSearchRowBasic;
  billingAccountJoin?: PlatformCommon.BillingAccountSearchRowBasic;
  billingScheduleJoin?: PlatformCommon.BillingScheduleSearchRowBasic;
  chargeEmployeeJoin?: PlatformCommon.EmployeeSearchRowBasic;
  customerJoin?: PlatformCommon.CustomerSearchRowBasic;
  invoiceJoin?: PlatformCommon.TransactionSearchRowBasic;
  itemJoin?: PlatformCommon.ItemSearchRowBasic;
  jobJoin?: PlatformCommon.JobSearchRowBasic;
  salesOrderJoin?: PlatformCommon.TransactionSearchRowBasic;
  timeJoin?: PlatformCommon.TimeBillSearchRowBasic;
  transactionJoin?: PlatformCommon.TransactionSearchRowBasic;
  usageJoin?: PlatformCommon.UsageSearchRowBasic;
  userJoin?: PlatformCommon.EmployeeSearchRowBasic;
  customSearchJoin?: PlatformCommon.CustomSearchRowBasic[];
  constructor(props: ChargeSearchRowProps) {
    super();
    this.basic = props.basic;
    this.billingAccountJoin = props.billingAccountJoin;
    this.billingScheduleJoin = props.billingScheduleJoin;
    this.chargeEmployeeJoin = props.chargeEmployeeJoin;
    this.customerJoin = props.customerJoin;
    this.invoiceJoin = props.invoiceJoin;
    this.itemJoin = props.itemJoin;
    this.jobJoin = props.jobJoin;
    this.salesOrderJoin = props.salesOrderJoin;
    this.timeJoin = props.timeJoin;
    this.transactionJoin = props.transactionJoin;
    this.usageJoin = props.usageJoin;
    this.userJoin = props.userJoin;
    this.customSearchJoin = props.customSearchJoin;
  }
}

export type CreditMemoSalesTeamListProps = {
  salesTeam?: CreditMemoSalesTeam[];
  replaceAll?: boolean;
};

export class CreditMemoSalesTeamList {
  salesTeam?: CreditMemoSalesTeam[];
  replaceAll?: boolean;
  constructor(props: CreditMemoSalesTeamListProps) {
    this.salesTeam = props.salesTeam;
    this.replaceAll = props.replaceAll;
  }
}

export type CustomerPaymentCreditListProps = {
  credit?: CustomerPaymentCredit[];
  replaceAll?: boolean;
};

export class CustomerPaymentCreditList {
  credit?: CustomerPaymentCredit[];
  replaceAll?: boolean;
  constructor(props: CustomerPaymentCreditListProps) {
    this.credit = props.credit;
    this.replaceAll = props.replaceAll;
  }
}

export type ReturnAuthorizationSalesTeamProps = {
  employee?: PlatformCore.RecordRef;
  salesRole?: PlatformCore.RecordRef;
  isPrimary?: boolean;
  contribution?: number;
};

export class ReturnAuthorizationSalesTeam {
  employee?: PlatformCore.RecordRef;
  salesRole?: PlatformCore.RecordRef;
  isPrimary?: boolean;
  contribution?: number;
  constructor(props: ReturnAuthorizationSalesTeamProps) {
    this.employee = props.employee;
    this.salesRole = props.salesRole;
    this.isPrimary = props.isPrimary;
    this.contribution = props.contribution;
  }
}

export type CreditMemoPartnersListProps = {
  partners?: PlatformCommon.Partners[];
  replaceAll?: boolean;
};

export class CreditMemoPartnersList {
  partners?: PlatformCommon.Partners[];
  replaceAll?: boolean;
  constructor(props: CreditMemoPartnersListProps) {
    this.partners = props.partners;
    this.replaceAll = props.replaceAll;
  }
}

export type CreditMemoItemListProps = {
  item?: CreditMemoItem[];
  replaceAll?: boolean;
};

export class CreditMemoItemList {
  item?: CreditMemoItem[];
  replaceAll?: boolean;
  constructor(props: CreditMemoItemListProps) {
    this.item = props.item;
    this.replaceAll = props.replaceAll;
  }
}

export type CustomerRefundDepositProps = {
  apply?: boolean;
  doc?: number;
  line?: number;
  depositDate?: string;
  refNum?: string;
  total?: number;
  remaining?: number;
  currency?: string;
  amount?: number;
};

export class CustomerRefundDeposit {
  apply?: boolean;
  doc?: number;
  line?: number;
  depositDate?: string;
  refNum?: string;
  total?: number;
  remaining?: number;
  currency?: string;
  amount?: number;
  constructor(props: CustomerRefundDepositProps) {
    this.apply = props.apply;
    this.doc = props.doc;
    this.line = props.line;
    this.depositDate = props.depositDate;
    this.refNum = props.refNum;
    this.total = props.total;
    this.remaining = props.remaining;
    this.currency = props.currency;
    this.amount = props.amount;
  }
}

export type CustomerRefundDepositListProps = {
  customerRefundDeposit?: CustomerRefundDeposit[];
  replaceAll?: boolean;
};

export class CustomerRefundDepositList {
  customerRefundDeposit?: CustomerRefundDeposit[];
  replaceAll?: boolean;
  constructor(props: CustomerRefundDepositListProps) {
    this.customerRefundDeposit = props.customerRefundDeposit;
    this.replaceAll = props.replaceAll;
  }
}

export type ChargeProps = {
  customForm?: PlatformCore.RecordRef;
  salesOrder?: PlatformCore.RecordRef;
  billTo?: PlatformCore.RecordRef;
  billingAccount?: PlatformCore.RecordRef;
  stage?: TransactionsCustomersTypes.ChargeStage;
  chargeDate?: string;
  use?: TransactionsCustomersTypes.ChargeUse;
  chargeType?: PlatformCore.RecordRef;
  projectTask?: PlatformCore.RecordRef;
  description?: string;
  createdDate?: string;
  timeRecord?: PlatformCore.RecordRef;
  rate?: string;
  quantity?: number;
  amount?: number;
  billingItem?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  transaction?: PlatformCore.RecordRef;
  transactionLine?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  salesOrderLine?: PlatformCore.RecordRef;
  subscriptionLine?: PlatformCore.RecordRef;
  invoice?: PlatformCore.RecordRef;
  invoiceLine?: PlatformCore.RecordRef;
  rule?: PlatformCore.RecordRef;
  runId?: string;
  internalId?: string;
  externalId?: string;
} & PlatformCore.RecordProps;

export class Charge extends PlatformCore.Record {
  customForm?: PlatformCore.RecordRef;
  salesOrder?: PlatformCore.RecordRef;
  billTo?: PlatformCore.RecordRef;
  billingAccount?: PlatformCore.RecordRef;
  stage?: TransactionsCustomersTypes.ChargeStage;
  chargeDate?: string;
  use?: TransactionsCustomersTypes.ChargeUse;
  chargeType?: PlatformCore.RecordRef;
  projectTask?: PlatformCore.RecordRef;
  description?: string;
  createdDate?: string;
  timeRecord?: PlatformCore.RecordRef;
  rate?: string;
  quantity?: number;
  amount?: number;
  billingItem?: PlatformCore.RecordRef;
  currency?: PlatformCore.RecordRef;
  transaction?: PlatformCore.RecordRef;
  transactionLine?: PlatformCore.RecordRef;
  clazz?: PlatformCore.RecordRef;
  department?: PlatformCore.RecordRef;
  location?: PlatformCore.RecordRef;
  salesOrderLine?: PlatformCore.RecordRef;
  subscriptionLine?: PlatformCore.RecordRef;
  invoice?: PlatformCore.RecordRef;
  invoiceLine?: PlatformCore.RecordRef;
  rule?: PlatformCore.RecordRef;
  runId?: string;
  internalId?: string;
  externalId?: string;
  constructor(props: ChargeProps) {
    super(props);
    this.customForm = props.customForm;
    this.salesOrder = props.salesOrder;
    this.billTo = props.billTo;
    this.billingAccount = props.billingAccount;
    this.stage = props.stage;
    this.chargeDate = props.chargeDate;
    this.use = props.use;
    this.chargeType = props.chargeType;
    this.projectTask = props.projectTask;
    this.description = props.description;
    this.createdDate = props.createdDate;
    this.timeRecord = props.timeRecord;
    this.rate = props.rate;
    this.quantity = props.quantity;
    this.amount = props.amount;
    this.billingItem = props.billingItem;
    this.currency = props.currency;
    this.transaction = props.transaction;
    this.transactionLine = props.transactionLine;
    this.clazz = props.clazz;
    this.department = props.department;
    this.location = props.location;
    this.salesOrderLine = props.salesOrderLine;
    this.subscriptionLine = props.subscriptionLine;
    this.invoice = props.invoice;
    this.invoiceLine = props.invoiceLine;
    this.rule = props.rule;
    this.runId = props.runId;
    this.internalId = props.internalId;
    this.externalId = props.externalId;
  }
}

export type DepositApplicationApplyProps = {
  doc?: number;
  line?: number;
  apply?: boolean;
  applyDate?: string;
  job?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
};

export class DepositApplicationApply {
  doc?: number;
  line?: number;
  apply?: boolean;
  applyDate?: string;
  job?: string;
  type?: string;
  refNum?: string;
  total?: number;
  due?: number;
  currency?: string;
  amount?: number;
  constructor(props: DepositApplicationApplyProps) {
    this.doc = props.doc;
    this.line = props.line;
    this.apply = props.apply;
    this.applyDate = props.applyDate;
    this.job = props.job;
    this.type = props.type;
    this.refNum = props.refNum;
    this.total = props.total;
    this.due = props.due;
    this.currency = props.currency;
    this.amount = props.amount;
  }
}
