name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.ENG_GITHUB_TOKEN }}
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.STEDI_ENGINEERING_PUBLIC_REPO_GPG_PASSPHRASE}}
          git-user-signingkey: true
          git-commit-gpgsign: true
        id: import_gpg
      - run: 'echo "email: ${{ steps.import_gpg.outputs.email }}"'
        env: {}
      - name: Release
        env:
          GIT_AUTHOR_NAME: ${{steps.import_gpg.outputs.name}}
          GIT_COMMITTER_NAME: ${{steps.import_gpg.outputs.name}}
          GIT_AUTHOR_EMAIL: ${{steps.import_gpg.outputs.email}}
          GIT_COMMITTER_EMAIL: ${{steps.import_gpg.outputs.email}}
          GITHUB_TOKEN: ${{ secrets.ENG_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
